<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais</title>
  <meta name="description" content="Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais" />
  
  <meta name="twitter:description" content="Capítulo 20 Análise de variância de um fator | Estatística nas Ciências Ambientais" />
  

<meta name="author" content="Fabio Cop Ferreira" />
<meta name="author" content="fabiocopf@gmail.com; fcferreira@unifesp.br" />
<meta name="author" content="Instituto do Mar, Universidade Federal de São Paulo" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modlinear.html"/>
<link rel="next" href="anovafatorial.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.20/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estatística nas Ciências Ambientais</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Índice</a></li>
<li class="part"><span><b>I Estatística descritiva</b></span></li>
<li class="chapter" data-level="1" data-path="estrdados.html"><a href="estrdados.html"><i class="fa fa-check"></i><b>1</b> Estrutura e tipo de dados</a>
<ul>
<li class="chapter" data-level="1.1" data-path="estrdados.html"><a href="estrdados.html#unidades-amostrais-e-descritores"><i class="fa fa-check"></i><b>1.1</b> Unidades amostrais e descritores</a></li>
<li class="chapter" data-level="1.2" data-path="estrdados.html"><a href="estrdados.html#tipos-de-dados"><i class="fa fa-check"></i><b>1.2</b> Tipos de dados</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="estrdados.html"><a href="estrdados.html#variáveis-qualitativas"><i class="fa fa-check"></i><b>1.2.1</b> Variáveis qualitativas</a></li>
<li class="chapter" data-level="1.2.2" data-path="estrdados.html"><a href="estrdados.html#variáveis-quantitativas"><i class="fa fa-check"></i><b>1.2.2</b> Variáveis quantitativas</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="estrdados.html"><a href="estrdados.html#níveis-de-mensuração"><i class="fa fa-check"></i><b>1.3</b> Níveis de mensuração</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="procdados.html"><a href="procdados.html"><i class="fa fa-check"></i><b>2</b> Processamento de dados</a>
<ul>
<li class="chapter" data-level="2.1" data-path="procdados.html"><a href="procdados.html#criando-o-diretório-de-trabalho"><i class="fa fa-check"></i><b>2.1</b> Criando o diretório de trabalho</a></li>
<li class="chapter" data-level="2.2" data-path="procdados.html"><a href="procdados.html#iniciando-o-projeto-intro_estatistica"><i class="fa fa-check"></i><b>2.2</b> Iniciando o projeto <code>Intro_estatistica</code></a></li>
<li class="chapter" data-level="2.3" data-path="procdados.html"><a href="procdados.html#instalação-de-pacotes"><i class="fa fa-check"></i><b>2.3</b> Instalação de pacotes</a></li>
<li class="chapter" data-level="2.4" data-path="procdados.html"><a href="procdados.html#carregando-os-pacotes"><i class="fa fa-check"></i><b>2.4</b> Carregando os pacotes</a></li>
<li class="chapter" data-level="2.5" data-path="procdados.html"><a href="procdados.html#importanto-a-base-de-dados"><i class="fa fa-check"></i><b>2.5</b> Importanto a base de dados</a></li>
<li class="chapter" data-level="2.6" data-path="procdados.html"><a href="procdados.html#verificando-a-base-de-dados"><i class="fa fa-check"></i><b>2.6</b> Verificando a base de dados</a></li>
<li class="chapter" data-level="2.7" data-path="procdados.html"><a href="procdados.html#reorganizando-a-base-de-dados"><i class="fa fa-check"></i><b>2.7</b> Reorganizando a base de dados</a></li>
<li class="chapter" data-level="2.8" data-path="procdados.html"><a href="procdados.html#selecionando-colunas-da-tabela"><i class="fa fa-check"></i><b>2.8</b> Selecionando colunas da tabela</a></li>
<li class="chapter" data-level="2.9" data-path="procdados.html"><a href="procdados.html#filtrando-linhas-da-tabela"><i class="fa fa-check"></i><b>2.9</b> Filtrando linhas da tabela</a></li>
<li class="chapter" data-level="2.10" data-path="procdados.html"><a href="procdados.html#adicionando-ou-modificando-colunas"><i class="fa fa-check"></i><b>2.10</b> Adicionando ou modificando colunas</a></li>
<li class="chapter" data-level="2.11" data-path="procdados.html"><a href="procdados.html#renomeando-colunas"><i class="fa fa-check"></i><b>2.11</b> Renomeando colunas</a></li>
<li class="chapter" data-level="2.12" data-path="procdados.html"><a href="procdados.html#outras-operações-para-processamento-e-transformação-de-dados"><i class="fa fa-check"></i><b>2.12</b> Outras operações para processamento e transformação de dados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="varqualit.html"><a href="varqualit.html"><i class="fa fa-check"></i><b>3</b> Descrevendo variáveis qualitativas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="varqualit.html"><a href="varqualit.html#representação-em-tabelas-de-frequência"><i class="fa fa-check"></i><b>3.1</b> Representação em tabelas de frequência</a></li>
<li class="chapter" data-level="3.2" data-path="varqualit.html"><a href="varqualit.html#tabelas-de-frequência-para-variáveis-categóricas-ordenadas"><i class="fa fa-check"></i><b>3.2</b> Tabelas de frequência para variáveis categóricas ordenadas</a></li>
<li class="chapter" data-level="3.3" data-path="varqualit.html"><a href="varqualit.html#representação-gráfica"><i class="fa fa-check"></i><b>3.3</b> Representação gráfica</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="varqualit.html"><a href="varqualit.html#criando-um-gráfico-no-ggplot2"><i class="fa fa-check"></i><b>3.3.1</b> Criando um gráfico no <code>ggplot2</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="varquant.html"><a href="varquant.html"><i class="fa fa-check"></i><b>4</b> Descrevendo variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="varquant.html"><a href="varquant.html#tabelas-de-frequência-para-variáveis-quantitativas"><i class="fa fa-check"></i><b>4.1</b> Tabelas de frequência para variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="varquant.html"><a href="varquant.html#alterando-o-tamanho-dos-intervalos-de-classe"><i class="fa fa-check"></i><b>4.1.1</b> Alterando o tamanho dos intervalos de classe</a></li>
<li class="chapter" data-level="4.1.2" data-path="varquant.html"><a href="varquant.html#tabela-de-frequência-para-cpue"><i class="fa fa-check"></i><b>4.1.2</b> Tabela de frequência para <code>CPUE</code></a></li>
<li class="chapter" data-level="4.1.3" data-path="varquant.html"><a href="varquant.html#tabela-de-frequência-acumulada"><i class="fa fa-check"></i><b>4.1.3</b> Tabela de frequência acumulada</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="varquant.html"><a href="varquant.html#representação-gráfica-histogramas"><i class="fa fa-check"></i><b>4.2</b> Representação gráfica: histogramas</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="varquant.html"><a href="varquant.html#representando-frequências-acumuladas"><i class="fa fa-check"></i><b>4.2.1</b> Representando frequências acumuladas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tendcentral.html"><a href="tendcentral.html"><i class="fa fa-check"></i><b>5</b> Medidas de tendência central</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tendcentral.html"><a href="tendcentral.html#média-aritmética"><i class="fa fa-check"></i><b>5.1</b> Média aritmética</a></li>
<li class="chapter" data-level="5.2" data-path="tendcentral.html"><a href="tendcentral.html#mediana"><i class="fa fa-check"></i><b>5.2</b> Mediana</a></li>
<li class="chapter" data-level="5.3" data-path="tendcentral.html"><a href="tendcentral.html#moda"><i class="fa fa-check"></i><b>5.3</b> Moda</a></li>
<li class="chapter" data-level="5.4" data-path="tendcentral.html"><a href="tendcentral.html#ponto-médio"><i class="fa fa-check"></i><b>5.4</b> Ponto médio</a></li>
<li class="chapter" data-level="5.5" data-path="tendcentral.html"><a href="tendcentral.html#efeito-da-assimetria-sobre-os-descritores-de-tendência-central"><i class="fa fa-check"></i><b>5.5</b> Efeito da assimetria sobre os descritores de tendência central</a></li>
<li class="chapter" data-level="5.6" data-path="tendcentral.html"><a href="tendcentral.html#obtendo-medidas-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>5.6</b> Obtendo medidas de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variacao.html"><a href="variacao.html"><i class="fa fa-check"></i><b>6</b> Medidas de variação</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variacao.html"><a href="variacao.html#variância"><i class="fa fa-check"></i><b>6.1</b> Variância</a></li>
<li class="chapter" data-level="6.2" data-path="variacao.html"><a href="variacao.html#desvio-padrão"><i class="fa fa-check"></i><b>6.2</b> Desvio padrão</a></li>
<li class="chapter" data-level="6.3" data-path="variacao.html"><a href="variacao.html#coeficiente-de-variação"><i class="fa fa-check"></i><b>6.3</b> Coeficiente de variação</a></li>
<li class="chapter" data-level="6.4" data-path="variacao.html"><a href="variacao.html#amplitude-de-variação"><i class="fa fa-check"></i><b>6.4</b> Amplitude de variação</a></li>
<li class="chapter" data-level="6.5" data-path="variacao.html"><a href="variacao.html#obtendo-medidas-variação-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>6.5</b> Obtendo medidas variação de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="quartis.html"><a href="quartis.html"><i class="fa fa-check"></i><b>7</b> Medidas de posição: quartis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="quartis.html"><a href="quartis.html#cálculo-dos-quartis-na-posição-j-q_j-para-j-1-2-e-3"><i class="fa fa-check"></i><b>7.1</b> Cálculo dos quartis na posição <span class="math inline">\(j\)</span> (<span class="math inline">\(Q_j\)</span>, para <span class="math inline">\(j = 1\)</span>, <span class="math inline">\(2\)</span> e <span class="math inline">\(3\)</span>)</a></li>
<li class="chapter" data-level="7.2" data-path="quartis.html"><a href="quartis.html#cálculo-dos-quartis-no-r"><i class="fa fa-check"></i><b>7.2</b> Cálculo dos quartis no R</a></li>
<li class="chapter" data-level="7.3" data-path="quartis.html"><a href="quartis.html#obtendo-os-quartis-a-partir-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>7.3</b> Obtendo os quartis a partir de uma tabela de dados</a></li>
<li class="chapter" data-level="7.4" data-path="quartis.html"><a href="quartis.html#regresentação-gráfica-dos-quartis-boxplots"><i class="fa fa-check"></i><b>7.4</b> Regresentação gráfica dos quartis: Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="escorez.html"><a href="escorez.html"><i class="fa fa-check"></i><b>8</b> Medidas de posição: índice Z</a>
<ul>
<li class="chapter" data-level="8.1" data-path="escorez.html"><a href="escorez.html#interpretando-o-valor-de-z"><i class="fa fa-check"></i><b>8.1</b> Interpretando o valor de <span class="math inline">\(Z\)</span></a></li>
<li class="chapter" data-level="8.2" data-path="escorez.html"><a href="escorez.html#realizando-a-transformação-z-a-partir-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>8.2</b> Realizando a transformação <span class="math inline">\(Z\)</span> a partir de uma tabela de dados</a></li>
<li class="chapter" data-level="8.3" data-path="escorez.html"><a href="escorez.html#valores-esperados-de-z-em-uma-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>8.3</b> Valores esperados de <span class="math inline">\(Z\)</span> em uma distribuição normal padronizada</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="biquali.html"><a href="biquali.html"><i class="fa fa-check"></i><b>9</b> Análise bidimensional: variáveis qualitativas</a>
<ul>
<li class="chapter" data-level="9.1" data-path="biquali.html"><a href="biquali.html#tabelas-de-contingência"><i class="fa fa-check"></i><b>9.1</b> Tabelas de contingência</a></li>
<li class="chapter" data-level="9.2" data-path="biquali.html"><a href="biquali.html#o-gráfico-de-barras-para-duas-variáveis-qualitativas"><i class="fa fa-check"></i><b>9.2</b> O gráfico de barras para duas variáveis qualitativas</a></li>
<li class="chapter" data-level="9.3" data-path="biquali.html"><a href="biquali.html#medindo-a-discrepância-com-o-índice-de-chi2-de-pearson"><i class="fa fa-check"></i><b>9.3</b> Medindo a discrepância com o índice de <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="9.4" data-path="biquali.html"><a href="biquali.html#o-índice-de-chi2-em-uma-tabela-de-contigência"><i class="fa fa-check"></i><b>9.4</b> O índice de <span class="math inline">\(\chi^2\)</span> em uma tabela de contigência</a></li>
<li class="chapter" data-level="9.5" data-path="biquali.html"><a href="biquali.html#valores-de-chi2-quando-existe-associação"><i class="fa fa-check"></i><b>9.5</b> Valores de <span class="math inline">\(\chi^2\)</span> quando existe associação</a></li>
<li class="chapter" data-level="9.6" data-path="biquali.html"><a href="biquali.html#variações-do-índice-de-chi2"><i class="fa fa-check"></i><b>9.6</b> Variações do índice de <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="9.7" data-path="biquali.html"><a href="biquali.html#obtendo-o-índice-de-chi2-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>9.7</b> Obtendo o índice de <span class="math inline">\(\chi^2\)</span> de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="biquant.html"><a href="biquant.html"><i class="fa fa-check"></i><b>10</b> Análise bidimensional: variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="10.1" data-path="biquant.html"><a href="biquant.html#covariância-entre-y-e-x"><i class="fa fa-check"></i><b>10.1</b> Covariância entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="10.2" data-path="biquant.html"><a href="biquant.html#coeficiente-de-correlação-linear-de-pearson-r"><i class="fa fa-check"></i><b>10.2</b> Coeficiente de correlação linear de Pearson <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="10.3" data-path="biquant.html"><a href="biquant.html#exemplo"><i class="fa fa-check"></i><b>10.3</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="biquantquali.html"><a href="biquantquali.html"><i class="fa fa-check"></i><b>11</b> Análise bidimensional: variáveis quantitativas e qualitativas</a>
<ul>
<li class="chapter" data-level="11.1" data-path="biquantquali.html"><a href="biquantquali.html#visualizando-a-distribuição-de-y-em-diferentes-grupos"><i class="fa fa-check"></i><b>11.1</b> Visualizando a distribuição de <span class="math inline">\(Y\)</span> em diferentes grupos</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="biquantquali.html"><a href="biquantquali.html#boxplots-para-os-níveis-do-tratamento"><i class="fa fa-check"></i><b>11.1.1</b> Boxplots para os níveis do tratamento</a></li>
<li class="chapter" data-level="11.1.2" data-path="biquantquali.html"><a href="biquantquali.html#o-gráfico-de-erros"><i class="fa fa-check"></i><b>11.1.2</b> O gráfico de erros</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="biquantquali.html"><a href="biquantquali.html#partição-das-soma-dos-quadrados"><i class="fa fa-check"></i><b>11.2</b> Partição das Soma dos Quadrados</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="biquantquali.html"><a href="biquantquali.html#a-característica-aditiva-das-somas-dos-quadrados"><i class="fa fa-check"></i><b>11.2.1</b> A característica aditiva das somas dos quadrados</a></li>
<li class="chapter" data-level="11.2.2" data-path="biquantquali.html"><a href="biquantquali.html#medindo-a-associação-entre-y-e-x"><i class="fa fa-check"></i><b>11.2.2</b> Medindo a associação entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="11.2.3" data-path="biquantquali.html"><a href="biquantquali.html#o-coeficiente-de-determinação-r2"><i class="fa fa-check"></i><b>11.2.3</b> O coeficiente de determinação (<span class="math inline">\(R^2\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="biquantquali.html"><a href="biquantquali.html#voltando-ao-conjundo-de-dados-medley.csv"><i class="fa fa-check"></i><b>11.3</b> Voltando ao conjundo de dados <code>medley.csv</code></a></li>
</ul></li>
<li class="part"><span><b>II Amostragem e Delineamento</b></span></li>
<li class="chapter" data-level="12" data-path="popamostra.html"><a href="popamostra.html"><i class="fa fa-check"></i><b>12</b> Descrevendo populações e amostras</a>
<ul>
<li class="chapter" data-level="12.1" data-path="popamostra.html"><a href="popamostra.html#população-amostra-e-unidade-amostral"><i class="fa fa-check"></i><b>12.1</b> População, amostra e unidade amostral</a></li>
<li class="chapter" data-level="12.2" data-path="popamostra.html"><a href="popamostra.html#distribuição-de-frequências-na-população-estatística"><i class="fa fa-check"></i><b>12.2</b> Distribuição de frequências na população estatística</a></li>
<li class="chapter" data-level="12.3" data-path="popamostra.html"><a href="popamostra.html#distribuições-de-frequências-na-amostra"><i class="fa fa-check"></i><b>12.3</b> Distribuições de frequências na amostra</a></li>
<li class="chapter" data-level="12.4" data-path="popamostra.html"><a href="popamostra.html#parâmetros-e-estimadores"><i class="fa fa-check"></i><b>12.4</b> Parâmetros e estimadores</a></li>
<li class="chapter" data-level="12.5" data-path="popamostra.html"><a href="popamostra.html#amostragem-e-inferência"><i class="fa fa-check"></i><b>12.5</b> Amostragem e inferência</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="amostrmedias.html"><a href="amostrmedias.html"><i class="fa fa-check"></i><b>13</b> Amostrando uma População Estatística</a>
<ul>
<li class="chapter" data-level="13.1" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>13.1</b> Amostragem aleatória simples</a></li>
<li class="chapter" data-level="13.2" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-estratificada"><i class="fa fa-check"></i><b>13.2</b> Amostragem aleatória estratificada</a></li>
<li class="chapter" data-level="13.3" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-sistemática"><i class="fa fa-check"></i><b>13.3</b> Amostragem sistemática</a></li>
<li class="chapter" data-level="13.4" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral-acurácia-e-precisão"><i class="fa fa-check"></i><b>13.4</b> Erro amostral, acurácia e precisão</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral"><i class="fa fa-check"></i><b>13.4.1</b> Erro amostral</a></li>
<li class="chapter" data-level="13.4.2" data-path="amostrmedias.html"><a href="amostrmedias.html#acurácia"><i class="fa fa-check"></i><b>13.4.2</b> Acurácia</a></li>
<li class="chapter" data-level="13.4.3" data-path="amostrmedias.html"><a href="amostrmedias.html#precisão-o-erro-padrão-da-média-sigmaoverlinex"><i class="fa fa-check"></i><b>13.4.3</b> Precisão: o erro padrão da média (<span class="math inline">\(\sigma^{\overline{X}}\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Inferência Estatística e Teste de Hipóteses</b></span></li>
<li class="chapter" data-level="14" data-path="normdist.html"><a href="normdist.html"><i class="fa fa-check"></i><b>14</b> O modelo da distribuição normal</a>
<ul>
<li class="chapter" data-level="14.1" data-path="normdist.html"><a href="normdist.html#o-modelo-normal-de-probabilidades"><i class="fa fa-check"></i><b>14.1</b> O modelo normal de probabilidades</a></li>
<li class="chapter" data-level="14.2" data-path="normdist.html"><a href="normdist.html#entendendo-a-função-normal-de-densidade-de-probabilidade"><i class="fa fa-check"></i><b>14.2</b> Entendendo a função normal de densidade de probabilidade</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="normdist.html"><a href="normdist.html#calculando-de-fx-no-r-a-função-dnorm"><i class="fa fa-check"></i><b>14.2.1</b> Calculando de <span class="math inline">\(f(x)\)</span> no R: a função <code>dnorm()</code></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="normdist.html"><a href="normdist.html#cálculo-de-probabilidade-com-a-função-normal-de-densidade"><i class="fa fa-check"></i><b>14.3</b> Cálculo de probabilidade com a função normal de densidade</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="normdist.html"><a href="normdist.html#calculando-probabilidades-no-r-a-função-pnorm"><i class="fa fa-check"></i><b>14.3.1</b> Calculando probabilidades no R: a função <code>pnorm()</code></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="normdist.html"><a href="normdist.html#a-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>14.4</b> A distribuição normal padronizada</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="normdist.html"><a href="normdist.html#probabilidades-em-uma-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>14.4.1</b> Probabilidades em uma distribuição normal padronizada</a></li>
<li class="chapter" data-level="14.4.2" data-path="normdist.html"><a href="normdist.html#tabela-z"><i class="fa fa-check"></i><b>14.4.2</b> Tabela <span class="math inline">\(Z\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="normdist.html"><a href="normdist.html#exercícios-resolvidos"><i class="fa fa-check"></i><b>14.5</b> Exercícios resolvidos</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="normdist.html"><a href="normdist.html#distribuição-de-comprimento"><i class="fa fa-check"></i><b>14.5.1</b> Distribuição de comprimento</a></li>
<li class="chapter" data-level="14.5.2" data-path="normdist.html"><a href="normdist.html#intervalos-em-uma-distribuição-normal"><i class="fa fa-check"></i><b>14.5.2</b> Intervalos em uma distribuição normal</a></li>
<li class="chapter" data-level="14.5.3" data-path="normdist.html"><a href="normdist.html#quantos-desvios-padrões"><i class="fa fa-check"></i><b>14.5.3</b> Quantos desvios padrões?</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="normdist.html"><a href="normdist.html#exercícios-propostos"><i class="fa fa-check"></i><b>14.6</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="tcl.html"><a href="tcl.html"><i class="fa fa-check"></i><b>15</b> Distribuição das médias amostrais</a>
<ul>
<li class="chapter" data-level="15.1" data-path="tcl.html"><a href="tcl.html#teorema-central-do-limite"><i class="fa fa-check"></i><b>15.1</b> Teorema Central do Limite</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="tcl.html"><a href="tcl.html#probabilidades-na-amostra-original-e-na-distribuição-de-médias"><i class="fa fa-check"></i><b>15.1.1</b> Probabilidades na amostra original e na distribuição de médias</a></li>
<li class="chapter" data-level="15.1.2" data-path="tcl.html"><a href="tcl.html#distribuições-não-normais"><i class="fa fa-check"></i><b>15.1.2</b> Distribuições não-normais</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="tcl.html"><a href="tcl.html#exercícios-resolvidos-1"><i class="fa fa-check"></i><b>15.2</b> Exercícios resolvidos:</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="tcl.html"><a href="tcl.html#tamanho-médio-de-robalos-no-mercado-de-peixes"><i class="fa fa-check"></i><b>15.2.1</b> Tamanho médio de robalos no mercado de peixes</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="tcl.html"><a href="tcl.html#exercícios-propostos-1"><i class="fa fa-check"></i><b>15.3</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="inferenc.html"><a href="inferenc.html"><i class="fa fa-check"></i><b>16</b> Estimando a média populacional</a>
<ul>
<li class="chapter" data-level="16.1" data-path="inferenc.html"><a href="inferenc.html#estimação-pontual-e-estimação-intervalar"><i class="fa fa-check"></i><b>16.1</b> Estimação pontual e estimação intervalar</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="inferenc.html"><a href="inferenc.html#intervalo-de-confiança"><i class="fa fa-check"></i><b>16.1.1</b> Intervalo de confiança</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="inferenc.html"><a href="inferenc.html#introdução-à-suficiência-amostral"><i class="fa fa-check"></i><b>16.2</b> Introdução à suficiência amostral</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="inferenc.html"><a href="inferenc.html#nível-de-acurácia-desejado-margem-de-erro-e-nível-de-confiança-na-estimativa"><i class="fa fa-check"></i><b>16.2.1</b> Nível de acurácia desejado (margem de erro) e nível de confiança na estimativa</a></li>
<li class="chapter" data-level="16.2.2" data-path="inferenc.html"><a href="inferenc.html#determinando-o-tamanho-de-uma-amostra"><i class="fa fa-check"></i><b>16.2.2</b> Determinando o tamanho de uma amostra</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="th.html"><a href="th.html"><i class="fa fa-check"></i><b>17</b> Introdução ao Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="17.1" data-path="th.html"><a href="th.html#probabilidade-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>17.1</b> Probabilidade e teste de hipóteses</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="th.html"><a href="th.html#a-necessidade-de-um-modelo-de-distribuição-das-médias-amostrais"><i class="fa fa-check"></i><b>17.1.1</b> A necessidade de um modelo de distribuição das médias amostrais</a></li>
<li class="chapter" data-level="17.1.2" data-path="th.html"><a href="th.html#definindo-o-limite-de-rejeição-para-h_0"><i class="fa fa-check"></i><b>17.1.2</b> Definindo o limite de rejeição para <span class="math inline">\(H_0\)</span></a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="th.html"><a href="th.html#exemplificando-um-teste-de-hipóteses-o-teste-z"><i class="fa fa-check"></i><b>17.2</b> Exemplificando um teste de hipóteses: o teste z</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="th.html"><a href="th.html#tomada-de-decisão-sobre-h_0-nível-de-significância"><i class="fa fa-check"></i><b>17.2.1</b> Tomada de decisão sobre <span class="math inline">\(H_0\)</span>: nível de significância</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="th.html"><a href="th.html#erros-de-decisão-em-um-teste-de-hipóteses"><i class="fa fa-check"></i><b>17.3</b> Erros de decisão em um teste de hipóteses</a></li>
<li class="chapter" data-level="17.4" data-path="th.html"><a href="th.html#estabelecendo-a-hipótese-alternativa-testes-bicaudais-e-unicaudais"><i class="fa fa-check"></i><b>17.4</b> Estabelecendo a hipótese alternativa: testes Bicaudais e Unicaudais</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="testet.html"><a href="testet.html"><i class="fa fa-check"></i><b>18</b> Teste t de Student</a>
<ul>
<li class="chapter" data-level="18.1" data-path="testet.html"><a href="testet.html#teste-t-para-uma-média-populacional"><i class="fa fa-check"></i><b>18.1</b> Teste t para uma média populacional</a></li>
<li class="chapter" data-level="18.2" data-path="testet.html"><a href="testet.html#graus-de-liberdade"><i class="fa fa-check"></i><b>18.2</b> Graus de liberdade</a></li>
<li class="chapter" data-level="18.3" data-path="testet.html"><a href="testet.html#probabilidades-no-teste-t-de-student-a-tabela-t"><i class="fa fa-check"></i><b>18.3</b> Probabilidades no teste <span class="math inline">\(t\)</span> de Student: a tabela <span class="math inline">\(t\)</span></a></li>
<li class="chapter" data-level="18.4" data-path="testet.html"><a href="testet.html#teste-t-para-comparação-de-duas-médias-independentes"><i class="fa fa-check"></i><b>18.4</b> Teste t para comparação de duas médias independentes</a></li>
</ul></li>
<li class="part"><span><b>IV Modelos Lineares Clássicos</b></span></li>
<li class="chapter" data-level="19" data-path="modlinear.html"><a href="modlinear.html"><i class="fa fa-check"></i><b>19</b> Modelos lineares</a>
<ul>
<li class="chapter" data-level="19.1" data-path="modlinear.html"><a href="modlinear.html#simulando-um-modelo-linear-no-r"><i class="fa fa-check"></i><b>19.1</b> Simulando um modelo linear no R</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="modlinear.html"><a href="modlinear.html#o-modelo-de-regressão"><i class="fa fa-check"></i><b>19.1.1</b> O Modelo de Regressão</a></li>
<li class="chapter" data-level="19.1.2" data-path="modlinear.html"><a href="modlinear.html#modelo-de-anova"><i class="fa fa-check"></i><b>19.1.2</b> Modelo de ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>20</b> Análise de variância de um fator</a>
<ul>
<li class="chapter" data-level="20.1" data-path="anova.html"><a href="anova.html#o-modelo-da-anova-e-as-hipóteses-estatísticas"><i class="fa fa-check"></i><b>20.1</b> O modelo da ANOVA e as hipóteses estatísticas</a></li>
<li class="chapter" data-level="20.2" data-path="anova.html"><a href="anova.html#partição-da-soma-dos-quadrados"><i class="fa fa-check"></i><b>20.2</b> Partição da soma dos quadrados</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="anova.html"><a href="anova.html#a-característica-aditiva-das-somas-dos-quadrados-1"><i class="fa fa-check"></i><b>20.2.1</b> A característica aditiva das somas dos quadrados</a></li>
<li class="chapter" data-level="20.2.2" data-path="anova.html"><a href="anova.html#medindo-a-associação-entre-y-e-x-1"><i class="fa fa-check"></i><b>20.2.2</b> Medindo a associação entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="anova.html"><a href="anova.html#quadrados-médios-e-graus-de-liberdade"><i class="fa fa-check"></i><b>20.3</b> Quadrados médios e graus de liberdade</a></li>
<li class="chapter" data-level="20.4" data-path="anova.html"><a href="anova.html#estatística-f-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>20.4</b> Estatística <span class="math inline">\(F\)</span> e teste de hipóteses</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="anova.html"><a href="anova.html#nível-de-significância"><i class="fa fa-check"></i><b>20.4.1</b> Nível de significância</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="anova.html"><a href="anova.html#um-exemplo-de-anova"><i class="fa fa-check"></i><b>20.5</b> Um exemplo de ANOVA</a></li>
<li class="chapter" data-level="20.6" data-path="anova.html"><a href="anova.html#testes-a-posteriori-de-comparação-de-médias"><i class="fa fa-check"></i><b>20.6</b> Testes a <em>posteriori</em> de comparação de médias</a></li>
<li class="chapter" data-level="20.7" data-path="anova.html"><a href="anova.html#ajustando-a-anova-no-r"><i class="fa fa-check"></i><b>20.7</b> Ajustando a ANOVA no R</a></li>
<li class="chapter" data-level="20.8" data-path="anova.html"><a href="anova.html#pressupostos-da-anova"><i class="fa fa-check"></i><b>20.8</b> Pressupostos da ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="anovafatorial.html"><a href="anovafatorial.html"><i class="fa fa-check"></i><b>21</b> Análise de variância fatorial</a></li>
<li class="chapter" data-level="22" data-path="regressao.html"><a href="regressao.html"><i class="fa fa-check"></i><b>22</b> Regressão linear e correlação</a>
<ul>
<li class="chapter" data-level="22.1" data-path="regressao.html"><a href="regressao.html#modelo-geral-de-regressão"><i class="fa fa-check"></i><b>22.1</b> Modelo geral de regressão</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="regressao.html"><a href="regressao.html#porção-determinística"><i class="fa fa-check"></i><b>22.1.1</b> Porção determinística</a></li>
<li class="chapter" data-level="22.1.2" data-path="regressao.html"><a href="regressao.html#porção-estocástica"><i class="fa fa-check"></i><b>22.1.2</b> Porção estocástica</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="regressao.html"><a href="regressao.html#ajuste-dos-dados-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>22.2</b> Ajuste dos dados ao modelo de regressão</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="regressao.html"><a href="regressao.html#método-dos-mínimos-quadrados"><i class="fa fa-check"></i><b>22.2.1</b> Método dos mínimos quadrados</a></li>
<li class="chapter" data-level="22.2.2" data-path="regressao.html"><a href="regressao.html#variâncias-covariâncias-e-coeficientes-da-regressão"><i class="fa fa-check"></i><b>22.2.2</b> Variâncias, covariâncias e coeficientes da regressão</a></li>
<li class="chapter" data-level="22.2.3" data-path="regressao.html"><a href="regressao.html#exemplo-de-ajuste-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>22.2.3</b> Exemplo de ajuste ao modelo de regressão</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="regressao.html"><a href="regressao.html#testes-de-hipóteses-na-regressão-linear-simples"><i class="fa fa-check"></i><b>22.3</b> Testes de hipóteses na regressão linear simples</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="regressao.html"><a href="regressao.html#teste-sobre-beta_1"><i class="fa fa-check"></i><b>22.3.1</b> Teste sobre <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="22.3.2" data-path="regressao.html"><a href="regressao.html#análise-de-variância-da-regressão"><i class="fa fa-check"></i><b>22.3.2</b> Análise de variância da regressão</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="regressao.html"><a href="regressao.html#coeficiente-de-determinação-r2"><i class="fa fa-check"></i><b>22.4</b> Coeficiente de determinação <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="22.5" data-path="regressao.html"><a href="regressao.html#intervalo-de-confiança-de-y"><i class="fa fa-check"></i><b>22.5</b> Intervalo de confiança de <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="22.6" data-path="regressao.html"><a href="regressao.html#pressupostos-da-regressão-linear-simples"><i class="fa fa-check"></i><b>22.6</b> Pressupostos da regressão linear simples</a>
<ul>
<li class="chapter" data-level="22.6.1" data-path="regressao.html"><a href="regressao.html#relação-funcional-linear"><i class="fa fa-check"></i><b>22.6.1</b> Relação funcional linear</a></li>
<li class="chapter" data-level="22.6.2" data-path="regressao.html"><a href="regressao.html#independência"><i class="fa fa-check"></i><b>22.6.2</b> Independência</a></li>
<li class="chapter" data-level="22.6.3" data-path="regressao.html"><a href="regressao.html#variável-x-é-medida-sem-erros"><i class="fa fa-check"></i><b>22.6.3</b> Variável <span class="math inline">\(X\)</span> é medida sem erros</a></li>
<li class="chapter" data-level="22.6.4" data-path="regressao.html"><a href="regressao.html#distribuição-normal-dos-resíduos"><i class="fa fa-check"></i><b>22.6.4</b> Distribuição normal dos resíduos</a></li>
<li class="chapter" data-level="22.6.5" data-path="regressao.html"><a href="regressao.html#variância-residual-constante"><i class="fa fa-check"></i><b>22.6.5</b> Variância residual constante</a></li>
</ul></li>
<li class="chapter" data-level="22.7" data-path="regressao.html"><a href="regressao.html#diagnósticos-da-regressão"><i class="fa fa-check"></i><b>22.7</b> Diagnósticos da regressão</a>
<ul>
<li class="chapter" data-level="22.7.1" data-path="regressao.html"><a href="regressao.html#gráfico-de-resíduos"><i class="fa fa-check"></i><b>22.7.1</b> Gráfico de resíduos</a></li>
<li class="chapter" data-level="22.7.2" data-path="regressao.html"><a href="regressao.html#histograma-dos-resíduos"><i class="fa fa-check"></i><b>22.7.2</b> Histograma dos resíduos</a></li>
</ul></li>
<li class="chapter" data-level="22.8" data-path="regressao.html"><a href="regressao.html#coeficiente-de-correlação-de-pearson-r"><i class="fa fa-check"></i><b>22.8</b> Coeficiente de correlação de Pearson <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="22.8.1" data-path="regressao.html"><a href="regressao.html#teste-de-hipóteses-para-r"><i class="fa fa-check"></i><b>22.8.1</b> Teste de hipóteses para <span class="math inline">\(r\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="regresmultipla.html"><a href="regresmultipla.html"><i class="fa fa-check"></i><b>23</b> Regressão linear múltipla</a></li>
<li class="chapter" data-level="24" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>24</b> Análise de covariância</a></li>
<li class="chapter" data-level="25" data-path="repanova.html"><a href="repanova.html"><i class="fa fa-check"></i><b>25</b> Análise de variância de medidas repetidas</a></li>
<li class="part"><span><b>V Fundamentos de probabilidade</b></span></li>
<li class="chapter" data-level="26" data-path="espacoamostral.html"><a href="espacoamostral.html"><i class="fa fa-check"></i><b>26</b> O espaço de possibilidades de um experimento</a>
<ul>
<li class="chapter" data-level="26.1" data-path="espacoamostral.html"><a href="espacoamostral.html#probabilidades-de-um-evento"><i class="fa fa-check"></i><b>26.1</b> Probabilidades de um evento</a>
<ul>
<li class="chapter" data-level="26.1.1" data-path="espacoamostral.html"><a href="espacoamostral.html#estimando-as-probabilidades-de-um-evento-por-amostragem"><i class="fa fa-check"></i><b>26.1.1</b> Estimando as probabilidades de um evento por amostragem</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="probregras.html"><a href="probregras.html"><i class="fa fa-check"></i><b>27</b> Combinando as probabilidades de eventos</a>
<ul>
<li class="chapter" data-level="27.1" data-path="probregras.html"><a href="probregras.html#eventos-complexos"><i class="fa fa-check"></i><b>27.1</b> Eventos complexos</a>
<ul>
<li class="chapter" data-level="27.1.1" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-venn"><i class="fa fa-check"></i><b>27.1.1</b> Representação de eventos: diagrama de Venn</a></li>
<li class="chapter" data-level="27.1.2" data-path="probregras.html"><a href="probregras.html#probabilidade-de-eventos-simples"><i class="fa fa-check"></i><b>27.1.2</b> Probabilidade de eventos simples</a></li>
<li class="chapter" data-level="27.1.3" data-path="probregras.html"><a href="probregras.html#probabilidade-da-união-de-eventos"><i class="fa fa-check"></i><b>27.1.3</b> Probabilidade da união de eventos</a></li>
<li class="chapter" data-level="27.1.4" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-árvore"><i class="fa fa-check"></i><b>27.1.4</b> Representação de eventos: diagrama de árvore</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="28" data-path="probcondind.html"><a href="probcondind.html"><i class="fa fa-check"></i><b>28</b> Probabilidade condicional e independência</a>
<ul>
<li class="chapter" data-level="28.1" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes"><i class="fa fa-check"></i><b>28.1</b> Eventos independentes</a>
<ul>
<li class="chapter" data-level="28.1.1" data-path="probcondind.html"><a href="probcondind.html#um-exemplo-de-eventos-independentes"><i class="fa fa-check"></i><b>28.1.1</b> Um exemplo de eventos independentes</a></li>
</ul></li>
<li class="chapter" data-level="28.2" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes-vs-mutuamente-exclusivos"><i class="fa fa-check"></i><b>28.2</b> Eventos independentes <em>vs</em> mutuamente exclusivos</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="tbayes.html"><a href="tbayes.html"><i class="fa fa-check"></i><b>29</b> Teorema de Bayes: atualizando o conhecimento</a>
<ul>
<li class="chapter" data-level="29.1" data-path="tbayes.html"><a href="tbayes.html#teorema-de-bayes"><i class="fa fa-check"></i><b>29.1</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="29.2" data-path="tbayes.html"><a href="tbayes.html#teorema-da-probabilidade-total"><i class="fa fa-check"></i><b>29.2</b> Teorema da probabilidade total</a></li>
<li class="chapter" data-level="29.3" data-path="tbayes.html"><a href="tbayes.html#o-problema-da-detecção-de-espécies"><i class="fa fa-check"></i><b>29.3</b> O problema da detecção de espécies</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="tbayes.html"><a href="tbayes.html#razão-de-verossimilhança-inferência-bayesiana-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>29.3.1</b> Razão de verossimilhança, inferência bayesiana e teste de hipóteses</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Modelos Probabilísticos, verossimilhança e inferência bayesiana</b></span></li>
<li class="chapter" data-level="30" data-path="va.html"><a href="va.html"><i class="fa fa-check"></i><b>30</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos discretos</em></a>
<ul>
<li class="chapter" data-level="30.1" data-path="va.html"><a href="va.html#experimento-1-sucessos-e-fracassos"><i class="fa fa-check"></i><b>30.1</b> <em>Experimento 1</em>: Sucessos e fracassos</a>
<ul>
<li><a href="va.html#a-distribuição-de-probabilidade-de-y">A distribuição de probabilidade de <span class="math inline">\(Y\)</span></a></li>
<li><a href="va.html#uma-expressão-geral-para-py-y">Uma expressão geral para <span class="math inline">\(P(Y = y)\)</span></a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#função-de-distribuição-acumulada"><i class="fa fa-check"></i>Função de distribuição acumulada</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#estruturas-previsíveis-para-um-experimento-aleatório"><i class="fa fa-check"></i>Estruturas previsíveis para um experimento aleatório</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#alterando-os-parâmetros-do-modelo"><i class="fa fa-check"></i>Alterando os parâmetros do modelo</a></li>
</ul></li>
<li class="chapter" data-level="30.2" data-path="va.html"><a href="va.html#experimento-2-o-custo-de-1-sucesso"><i class="fa fa-check"></i><b>30.2</b> <em>Experimento 2</em>: O custo de 1 sucesso</a></li>
<li class="chapter" data-level="30.3" data-path="va.html"><a href="va.html#experimento-3-uma-sequência-de-sucessos"><i class="fa fa-check"></i><b>30.3</b> <em>Experimento 3</em>: Uma sequência de sucessos</a></li>
<li class="chapter" data-level="30.4" data-path="va.html"><a href="va.html#experimento-4-quantas-marcas-na-amostra"><i class="fa fa-check"></i><b>30.4</b> <em>Experimento 4</em>: Quantas marcas na amostra!</a></li>
<li class="chapter" data-level="30.5" data-path="va.html"><a href="va.html#experimento-5-contagem-por-unidade-de-área-tempo-.."><i class="fa fa-check"></i><b>30.5</b> <em>Experimento 5</em>: Contagem por unidade de área, tempo, …..</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="vacont.html"><a href="vacont.html"><i class="fa fa-check"></i><b>31</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos contínuos</em></a>
<ul>
<li class="chapter" data-level="31.1" data-path="vacont.html"><a href="vacont.html#alguns-fenômenos-têm-distribuição-normal"><i class="fa fa-check"></i><b>31.1</b> Alguns fenômenos têm distribuição normal</a></li>
<li class="chapter" data-level="31.2" data-path="vacont.html"><a href="vacont.html#outros-são-altamente-assimétricos"><i class="fa fa-check"></i><b>31.2</b> Outros são altamente assimétricos</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="detmodel.html"><a href="detmodel.html"><i class="fa fa-check"></i><b>32</b> Alguns modelos são determinísticos</a>
<ul>
<li class="chapter" data-level="32.1" data-path="detmodel.html"><a href="detmodel.html#modelo-linear"><i class="fa fa-check"></i><b>32.1</b> Modelo linear</a></li>
<li class="chapter" data-level="32.2" data-path="detmodel.html"><a href="detmodel.html#função-potência"><i class="fa fa-check"></i><b>32.2</b> Função potência</a></li>
<li class="chapter" data-level="32.3" data-path="detmodel.html"><a href="detmodel.html#modelo-de-michaelis-menten-ou-resposta-funcional-do-tipo-ii"><i class="fa fa-check"></i><b>32.3</b> Modelo de Michaelis-Menten (ou Resposta funcional do tipo II)</a></li>
<li class="chapter" data-level="32.4" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iii"><i class="fa fa-check"></i><b>32.4</b> Resposta funcional do tipo III</a></li>
<li class="chapter" data-level="32.5" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iv"><i class="fa fa-check"></i><b>32.5</b> Resposta funcional do tipo IV</a></li>
<li class="chapter" data-level="32.6" data-path="detmodel.html"><a href="detmodel.html#função-hiperbólica"><i class="fa fa-check"></i><b>32.6</b> Função hiperbólica</a></li>
<li class="chapter" data-level="32.7" data-path="detmodel.html"><a href="detmodel.html#função-exponencial"><i class="fa fa-check"></i><b>32.7</b> Função exponencial</a></li>
<li class="chapter" data-level="32.8" data-path="detmodel.html"><a href="detmodel.html#função-logística"><i class="fa fa-check"></i><b>32.8</b> Função logística</a></li>
<li class="chapter" data-level="32.9" data-path="detmodel.html"><a href="detmodel.html#modelo-monomolecular"><i class="fa fa-check"></i><b>32.9</b> Modelo monomolecular</a></li>
<li class="chapter" data-level="32.10" data-path="detmodel.html"><a href="detmodel.html#modelo-de-ricker"><i class="fa fa-check"></i><b>32.10</b> Modelo de Ricker</a></li>
<li class="chapter" data-level="32.11" data-path="detmodel.html"><a href="detmodel.html#modelo-de-gompertz"><i class="fa fa-check"></i><b>32.11</b> Modelo de Gompertz</a></li>
<li class="chapter" data-level="32.12" data-path="detmodel.html"><a href="detmodel.html#modelo-de-von-bertalanffy"><i class="fa fa-check"></i><b>32.12</b> Modelo de von Bertalanffy</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="modelstat.html"><a href="modelstat.html"><i class="fa fa-check"></i><b>33</b> As partes estocásticas e determinísticas de um modelo estatístico</a>
<ul>
<li class="chapter" data-level="33.1" data-path="modelstat.html"><a href="modelstat.html#a-parcela-aleatória"><i class="fa fa-check"></i><b>33.1</b> A parcela aleatória</a></li>
<li class="chapter" data-level="33.2" data-path="modelstat.html"><a href="modelstat.html#a-parcela-determinística"><i class="fa fa-check"></i><b>33.2</b> A parcela determinística</a></li>
<li class="chapter" data-level="33.3" data-path="modelstat.html"><a href="modelstat.html#mais-um-modelo-binomial-taxa-de-mortalidade-em-testes-dose-resposta"><i class="fa fa-check"></i><b>33.3</b> Mais um modelo Binomial: taxa de mortalidade em testes dose-resposta</a></li>
<li class="chapter" data-level="33.4" data-path="modelstat.html"><a href="modelstat.html#o-modelo-estatístico-da-regressão-linear"><i class="fa fa-check"></i><b>33.4</b> O modelo estatístico da regressão linear</a></li>
</ul></li>
<li class="chapter" data-level="34" data-path="emv.html"><a href="emv.html"><i class="fa fa-check"></i><b>34</b> Estimando os parâmetros: a ideia da Máxima Verossimilhança</a></li>
<li class="chapter" data-level="35" data-path="aic.html"><a href="aic.html"><i class="fa fa-check"></i><b>35</b> Comparando modelos: uma questão de parcimônia</a></li>
<li class="chapter" data-level="36" data-path="statbayes.html"><a href="statbayes.html"><i class="fa fa-check"></i><b>36</b> Da verossimilhança à estatística Bayesiana</a></li>
<li class="chapter" data-level="37" data-path="varmodels.html"><a href="varmodels.html"><i class="fa fa-check"></i><b>37</b> Uma variedade de modelos estatísticos: modelando a variância</a></li>
<li class="chapter" data-level="38" data-path="nindep.html"><a href="nindep.html"><i class="fa fa-check"></i><b>38</b> Uma variedade de modelos estatísticos: modelando os resíduos</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística nas Ciências Ambientais</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova" class="section level1" number="20">
<h1><span class="header-section-number">Capítulo 20</span> Análise de variância de um fator</h1>
<p>A <em>Análise de Variância</em> (<strong>ANOVA</strong>) desenvolvida por <a href="https://en.wikipedia.org/wiki/Ronald_Fisher" target="_blank">R. A. Fisher</a> aplica-se à uma classe de desenho experimental em que a variável resposta <span class="math inline">\(Y\)</span> é <em>contínua</em> e a variável explanatória <span class="math inline">\(X\)</span> é <em>categórica</em> com <span class="math inline">\(2\)</span> ou mais níveis. A ANOVA permite testarmos a hipótese de que duas ou mais médias amostrais (<span class="math inline">\(\overline{Y}_i\)</span>) possam ter sido obtidas de uma mesma população estatística com média <span class="math inline">\(\mu\)</span>. Alternativamente, podemos concluir que as médias amostrais diferem umas das outras, de tal forma que devemos assumir que foram amostradas a partir de <strong>diferentes populações estatísticas</strong>, nas quais ao menos um <span class="math inline">\(\mu_i\)</span> seja diferente dos demais. Iremos denominar estas duas possibilidades de <strong>hipótese estatísticas</strong> sobre a relação entre as médias populacionais.</p>
<div id="o-modelo-da-anova-e-as-hipóteses-estatísticas" class="section level2" number="20.1">
<h2><span class="header-section-number">20.1</span> O modelo da ANOVA e as hipóteses estatísticas</h2>
<p>O modelo pode ser representado por:</p>
<p><span class="math display">\[Y_{ij} = \mu + A_i + \epsilon_{ij}\]</span></p>
<p>onde <span class="math inline">\(Y_{ij}\)</span> é a variável resposta associada à observação <span class="math inline">\(i\)</span> do tratamento <span class="math inline">\(j\)</span>, <span class="math inline">\(\mu\)</span> representa a média geral e <span class="math inline">\(A_i\)</span> o efeito do tratamento <span class="math inline">\(i\)</span>. O termo <span class="math inline">\(\epsilon_{ij}\)</span> é denominado de <strong>resíduo</strong> (ou <em>erro</em>) associado a cada observação, que assumimos ter distribuição normal com média zero e variância constante.</p>
<p><span class="math inline">\(\epsilon \sim \mathcal{N}(0, \sigma^2)\)</span></p>
<hr />
<p>As hipóteses estatísticas no modelo de ANOVA são:</p>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2 = \mu_3 =.... = \mu_k\)</span> (HIPÓTESE NULA)</p>
<p><span class="math inline">\(H_a\)</span>: ao menos um par de médias é diferente (HIPÓTESE ALTERNATIVA)</p>
<hr />
<p>A hipótese nula (<span class="math inline">\(H_0\)</span>) define a ausência de diferenças entre as médias populacionais enquanto a hipótese alternativa (<span class="math inline">\(H_a\)</span>) refere-se a qualquer possibilidade diferente de <span class="math inline">\(H_0\)</span>. Se temos exatamente dois níveis em <span class="math inline">\(X\)</span>, a comparação de médias pode ser feita por meio de um teste <span class="math inline">\(t\)</span>. A ANOVA deve ser utilizada quando temos <strong>mais</strong> de dois níveis em <span class="math inline">\(X\)</span>. Neste sentido, o teste <span class="math inline">\(t\)</span> é um caso particular da ANOVA.</p>
</div>
<div id="partição-da-soma-dos-quadrados" class="section level2" number="20.2">
<h2><span class="header-section-number">20.2</span> Partição da soma dos quadrados</h2>
<p>A ANOVA consiste basicamente da <strong>partição da soma dos quadrados</strong> (Capítulo <a href="biquantquali.html#biquantquali">11</a>) seguida da construção de um teste estatístico apropriado (o teste <span class="math inline">\(F\)</span>) para verificar as plasibilidade de <span class="math inline">\(H_0\)</span>. Apresentaremos aqui um exemplo simples descrito na figura e na tabela abaixo para descrever o ajuste da ANOVA.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-343-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Para deixarmos claro as notações que iremos adotar adiante neste capítulo vamos definir que:</p>
<ul>
<li>Temos <span class="math inline">\(k = 3\)</span> grupos (<code>A</code>, <code>B</code> ou <code>C</code>) e para cada grupo <span class="math inline">\(n = 5\)</span> observações. Denotamos por <span class="math inline">\(n_{ij}\)</span> o número de observações dentro de cada grupo, em que <span class="math inline">\(i\)</span> é a <em>i-ésima</em> observação (<span class="math inline">\(i = 1\)</span> a <span class="math inline">\(5\)</span>) do <em>j-ésimo</em> grupo (<span class="math inline">\(j = 1\)</span> a <span class="math inline">\(3\)</span> - grupos <code>A</code> ao <code>C</code>). Neste exemplo, o número de observações em cada grupo é o mesmo (<span class="math inline">\(n_1 = n_2 = n_3 = n\)</span>), de modo que o total de observações é dado por:</li>
</ul>
<p><span class="math inline">\(N = k \times n = n_1 + n_2 + n_3 = 15\)</span></p>
<ul>
<li><p>A média de cada grupo será denotada por <span class="math inline">\(\overline{Y}_j\)</span>, que neste exemplo são: <span class="math inline">\(\overline{Y}_1 = 20.64\)</span> (grupo <code>A</code>), <span class="math inline">\(\overline{Y}_2 = 28.68\)</span> (grupo <code>B</code>) e <span class="math inline">\(\overline{Y}_3 = 12.18\)</span> (grupo <code>C</code>). Estas médias <strong>estimam</strong> as quantias <span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\mu_2\)</span> e <span class="math inline">\(\mu_3\)</span> sobre as quais versam as hipóteses do modelo.</p></li>
<li><p>Vamos denotar por <span class="math inline">\(\overline{\overline{Y}}\)</span> a <strong>Grande Média</strong>, isto é, a média geral de todas as observações independente do grupo de origem e que é utilizada para <strong>estimar</strong> <span class="math inline">\(\mu\)</span>.</p></li>
</ul>
<p><span class="math display">\[\overline{\overline{Y}} = \sum_{j = 1}^{k}\sum_{i = 1}^{n}\frac{Y_{ij}}{N} = \frac{\overline{Y_1} + \overline{Y_2} + \overline{Y_3}}{3} = 20.5\]</span></p>
<p>Podemos agora observar estes elementos no gráfico de dispersão.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-344-1.png" width="672" /></p>
<p>Para ajustar o modelo de ANOVA a estes dados precisamos calcular <span class="math inline">\(3\)</span> quantias: i - a <strong>Soma dos Quadrados Totais</strong> (<span class="math inline">\(SQ_{Total}\)</span>), ii - a <strong>Soma dos Quadrados dos Tratamentos</strong> <span class="math inline">\(SQ_{Trat}\)</span> e iii - a <strong>Soma dos Quadrados dos Resíduos</strong> <span class="math inline">\(SQ_{Res}\)</span>.</p>
<ol style="list-style-type: lower-roman">
<li><strong>Soma dos Quadrados Totais</strong> <span class="math inline">\(SQ_{Total}\)</span>: mede as diferenças entre <span class="math inline">\(Y_{ij}\)</span> e <span class="math inline">\(\overline{\overline{Y}}\)</span>. Temos nesta expressão o somatório dos desvios ao quadrado de todas as observações com relação à grande média <strong>independente</strong> do grupo de origem de cada observação.</li>
</ol>
<p><span class="math display">\[SQ_{Total} = \sum_{j = 1}^{k}\sum_{i = 1}^{n}(Y_{ij} - \overline{\overline{Y}})^2\]</span></p>
<ol start="2" style="list-style-type: lower-roman">
<li><strong>Soma dos Quadrados dos Tratamentos</strong> <span class="math inline">\(SQ_{Trat}\)</span>: mede as diferenças entre as <strong>médias dos tratamentos</strong> <span class="math inline">\(\overline{Y}_j\)</span> e <span class="math inline">\(\overline{\overline{Y}}\)</span>, sendo portanto os desvios ao quadrado da média de cada tratamento subtraída da grande média. <span class="math inline">\(SQ_{Trat}\)</span> também é chamada de soma dos quadrados <strong>entre grupos</strong> ou <strong>entre tratamentos</strong></li>
</ol>
<p><span class="math display">\[SQ_{Trat} = \sum_{j = 1}^{k}\sum_{i = 1}^{n_{j}}(\overline{Y}_{j} - \overline{\overline{Y}})^2 = \sum_{j = 1}^{k}n_{j}(\overline{Y}_{j} - \overline{\overline{Y}})^2\]</span></p>
<ol start="3" style="list-style-type: lower-roman">
<li><strong>Soma dos Quadrados dos Resíduos</strong> <span class="math inline">\(SQ_{Res}\)</span>: mede as diferenças entre cada observação <span class="math inline">\(Y_{ij}\)</span> e a média de seu próprio grupo <span class="math inline">\(\overline{Y}_{j}\)</span>. <span class="math inline">\(SQ_{Res}\)</span> também é chamada de soma dos quadrados <strong>dentro dos grupos</strong> ou <strong>dentro dos tratamentos</strong></li>
</ol>
<p><span class="math display">\[SQ_{Res} = \sum_{j = 1}^{k}\sum_{i = 1}^{n_{j}}(Y_{ij} - \overline{Y}_{j})^2\]</span></p>
<div id="a-característica-aditiva-das-somas-dos-quadrados-1" class="section level3" number="20.2.1">
<h3><span class="header-section-number">20.2.1</span> A característica aditiva das somas dos quadrados</h3>
<p>A partição da soma dos quadrados consiste em decompor a <strong>variação total</strong> do experimento em uma parcela atribuída à variação <strong>entre tratamentos</strong> e outra parcela da variação <strong>dentro dos tratamentos</strong>. Isto é possível pois as somas dos quadrados definidas acima podem ser expressas de forma aditiva como:</p>
<hr />
<p><span class="math display">\[SQ_{Total} = SQ_{Trat} + SQ_{Res}\]</span></p>
<hr />
<blockquote>
<p>Deste modo, é possível demostrar que:</p>
<p><span class="math inline">\(\sum_{j = 1}^{k}\sum_{i = 1}^{n}(Y_{ij} - \overline{\overline{Y}})^2 = \sum_{j = 1}^{k}n_{j}(Y_{j} - \overline{\overline{Y}})^2 + \sum_{j = 1}^{k}\sum_{i = 1}^{n}(Y_{ij} - \overline{Y}_{j})^2\)</span></p>
</blockquote>
</div>
<div id="medindo-a-associação-entre-y-e-x-1" class="section level3" number="20.2.2">
<h3><span class="header-section-number">20.2.2</span> Medindo a associação entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></h3>
<p>A característica aditiva das somas dos quadrados pode ser utilizada para mensurar o grau de dependência de <span class="math inline">\(Y_{ij}\)</span> com respeito aos diferentes tratamentos. Compare as duas figuras abaixo:</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-346-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>A soma dos quadrados dentro dos grupos é a mesma nas duas figuras (<span class="math inline">\(SQ_{Res} = 362.6\)</span>). No entanto, na figura da esquerda, em que as médias dos tratamentos são similares (e consequentemente próximas à grande média), a soma dos quadrados entre os tratamentos é muito menor (<span class="math inline">\(SQ_{Trat}^{esquerda} = 15.8\)</span>) que na figura da direita, em que as médias dos tratamentos estão distantes entre si (<span class="math inline">\(SQ_{Trat}^{direita} = 680.8\)</span>). É desta forma que a partição das somas dos quadrados nos permite diferenciar situações em que: i - a média dos grupos <strong>depende</strong> dos níveis do tratamento (figura da direita); de situações em que ii - a média <strong>não depende</strong> dos níveis do tratamento (figura da esquerda).</p>
</div>
</div>
<div id="quadrados-médios-e-graus-de-liberdade" class="section level2" number="20.3">
<h2><span class="header-section-number">20.3</span> Quadrados médios e graus de liberdade</h2>
<p>Para que os somatórios dos quadrados expressem uma medida de variação é necessário corriglos em função dos <strong>graus de liberdade (<span class="math inline">\(gl\)</span>)</strong>, obtendo assim <strong>Quadrados médios</strong> dados abaixo:</p>
<ol style="list-style-type: decimal">
<li>Quadrado médio total (<span class="math inline">\(QM_{Total}\)</span>)</li>
</ol>
<p><span class="math display">\[QM_{Total} = \frac{SQ_{Total}}{gl_{Total}}\]</span></p>
<p>em que <span class="math inline">\(gl_{Total} = N - 1\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Quadrado médio entre tratamentos (<span class="math inline">\(QM_{Trat}\)</span>)</li>
</ol>
<p><span class="math display">\[QM_{Trat} = \frac{SQ_{Trat}}{gl_{Trat}}\]</span></p>
<p>em que <span class="math inline">\(gl_{Trat} = k - 1\)</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Quadrado médio dentro dos tratamentos (<span class="math inline">\(QM_{Res}\)</span>)</li>
</ol>
<p><span class="math display">\[QM_{Res} = \frac{SQ_{Res}}{gl_{Res}}\]</span></p>
<p>em que <span class="math inline">\(gl_{Res} = N-k\)</span></p>
<p>Assim como a soma dos quadrados, os graus de liberdade também têm característica aditiva.</p>
<p><span class="math display">\[gl_{Total} = gl_{Trat} + gl_{Res} = (k - 1) + (N - K) = N - 1\]</span></p>
<p>Os quadrados médios que são estimativas de variâncias. Compare por exemplo a expressão do <span class="math inline">\(QM_{Total}\)</span> com a fórmula da variância amostral (<span class="math inline">\(s^2\)</span>) (Capítulo <a href="variacao.html#variacao">6</a>) e verá que excetuando mudanças de notação, as expressões são essencialmente as mesmas.</p>
</div>
<div id="estatística-f-e-teste-de-hipóteses" class="section level2" number="20.4">
<h2><span class="header-section-number">20.4</span> Estatística <span class="math inline">\(F\)</span> e teste de hipóteses</h2>
<p>Uma vez que os quadrados médios são estimativas de variância, uma estatística de teste apropriada é:</p>
<p><span class="math display">\[F_{calculado} = \frac{QM_{Trat}}{QM_{Res}}\]</span></p>
<p>A estatística <span class="math inline">\(F\)</span> (ou razão-<span class="math inline">\(F\)</span>) está associada à <strong>distribuição de probabilidades <span class="math inline">\(F\)</span></strong> e nos permite comparar a variância associada ao tratamento com a variância associada aos resíduos. Em mãos do valor de <span class="math inline">\(F_{calculado}\)</span>, o teste de hipóteses é possível após a definição do <strong>nível de significância</strong> <span class="math inline">\(\alpha\)</span>.</p>
<div id="nível-de-significância" class="section level3" number="20.4.1">
<h3><span class="header-section-number">20.4.1</span> Nível de significância</h3>
<p>Assim como discutimos nos testes <span class="math inline">\(Z\)</span> e <span class="math inline">\(t\)</span>, o valor de <span class="math inline">\(\alpha\)</span> estabelece um limite de aceitação para <span class="math inline">\(H_0\)</span>, isto é, um limite a partir do qual a estatística do teste se torna <strong>tão extrema</strong> que nos leva a assumir que <span class="math inline">\(H_0\)</span> é improvável, devendo portanto ser rejeitada em favor de <span class="math inline">\(H_a\)</span>. Este passo é possível pois o valor de <span class="math inline">\(F_{calculado}\)</span> pode ser associado à distribuição <span class="math inline">\(F\)</span> de probabilidades, o que nos permite calcular a probabilidade:</p>
<p><span class="math display">\[P(F_{calculado}) \le \alpha\]</span></p>
<p>Para facilitar a notação denominaremos <span class="math inline">\(P(F_{calculado})\)</span> simplesmente de <strong>valor de <span class="math inline">\(p\)</span></strong> expresso em vermelho na figura abaixo:</p>
<blockquote>
<p>Se <span class="math inline">\(p &gt; \alpha\)</span> –&gt; <strong>ACEITAMOS <span class="math inline">\(H_0\)</span></strong></p>
</blockquote>
<blockquote>
<p>Se <span class="math inline">\(p \le \alpha\)</span> –&gt; <strong>REJEITAMOS <span class="math inline">\(H_0\)</span></strong> (e assumimos <span class="math inline">\(H_a\)</span> como verdadeira)</p>
</blockquote>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-347-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Tradicionalmente utiliza-se <span class="math inline">\(\alpha = 0.05\)</span>. Neste caso, <span class="math inline">\(H_0\)</span> seria rejeitada somente de <span class="math inline">\(p \le 0.05\)</span>. Algumas área da medicina por eoutro lado, são tradicionais por utilizar valores de <span class="math inline">\(\alpha = 0.01\)</span>, o que torna o experimento menos sujeito ao <strong>erro do tipo I</strong> (Capítulo <a href="th.html#th">17</a>). Portanto, outros valores de <span class="math inline">\(\alpha\)</span> diferentes de <span class="math inline">\(0.05\)</span> podem ser escolhidos. O fundamental é que esta decisão, isto é, sobre o nível de significância <span class="math inline">\(\alpha\)</span> a ser adotado, seja feita <strong>previamente</strong> à obtenção dos dados.</p>
</div>
</div>
<div id="um-exemplo-de-anova" class="section level2" number="20.5">
<h2><span class="header-section-number">20.5</span> Um exemplo de ANOVA</h2>
<p>Vamos exemplificar o passo-a-passo de uma ANOVA utilizando nosso exemplo fictício. /o primeiro passo é definir as hipóteses estatpisticas e o nível de significância:</p>
<hr />
<p><span class="math inline">\(H_0: \mu_1 = \mu_2 = \mu_3\)</span></p>
<p><span class="math inline">\(H_a\)</span>: ao menos um <span class="math inline">\(\mu\)</span> é diferente</p>
<p><span class="math inline">\(\alpha = 0.05\)</span></p>
<hr />
<p>Utilizando os tados da tabela abaixo podemos obetr todas as quantias necessárias para o cálculo da ANOVA, isto é, os somatórios dos quadrados, os graus de liberdade,os quadraos médios e finalmente o valor de <span class="math inline">\(F_{calculado}\)</span></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
X
</th>
<th style="text-align:right;">
Y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
16.9
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
20.9
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
15.8
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
28.0
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
21.6
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
23.9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
30.4
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
31.7
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
30.9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
26.5
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
19.6
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
13.9
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
8.9
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
0.9
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
17.6
</td>
</tr>
</tbody>
</table>
<hr />
<p><strong>1. Somatórios dos quadrados</strong></p>
<p><span class="math inline">\(SQ_{Trat} = \sum_{j = 1}^{k}\sum_{i = 1}^{n_{j}}(\overline{Y}_{j} - \overline{\overline{Y}})^2 = 680.772\)</span></p>
<p><span class="math inline">\(SQ_{Res} = \sum_{j = 1}^{k}\sum_{i = 1}^{n_{j}}(Y_{ij} - \overline{Y}_{j})^2 = 362.568\)</span></p>
<hr />
<p><strong>2. Graus de liberdade</strong></p>
<p><span class="math inline">\(gl_{Trat} = k - 1 = 2\)</span></p>
<p><span class="math inline">\(gl_{Res} = N-k = 12\)</span></p>
<hr />
<p><strong>3. Quadrados médios</strong></p>
<p><span class="math inline">\(QM_{Trat} = \frac{SQ_{Trat}}{gl_{Trat}} = 340.386\)</span></p>
<p><span class="math inline">\(QM_{Res} = \frac{SQ_{Res}}{gl_{Res}} = 30.214\)</span></p>
<hr />
<p><strong>4. Estatística <span class="math inline">\(F\)</span></strong></p>
<p><span class="math inline">\(F_{calculado} = \frac{QM_{Trat}}{QM_{Res}} = 11.266\)</span></p>
<hr />
<p><strong>5. Tabela da ANOVA</strong></p>
<p>Estas quantias são tradicionalmente expressas em uma <strong>Tabela de ANOVA</strong> conforme abaixo:</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
680.772
</td>
<td style="text-align:right;">
340.386
</td>
<td style="text-align:right;">
11.26584
</td>
<td style="text-align:right;">
0.0017611
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
362.568
</td>
<td style="text-align:right;">
30.214
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>em que:</p>
<p><code>Df</code>: graus de liberdade</p>
<p><code>Sum Sq</code>: soma dos quadrados</p>
<p><code>Mean Sq</code>: quadrados médios</p>
<p><code>F value</code>: valor de <span class="math inline">\(F_{calculado}\)</span></p>
<p><code>Pr(&gt;F)</code>: valor de p</p>
<p>A primeira linha refere-se aos valores associados aos tratamentos e a segunda linha aos resíduos. Note que o cômputo de <span class="math inline">\(SQ_{Total}\)</span>, <span class="math inline">\(gl_{Total}\)</span> e <span class="math inline">\(QM_{Total}\)</span> não é realmente necessário.</p>
<hr />
<p>O valor de <span class="math inline">\(p = 11.265837\)</span> mostrado na tabela acima é aquele referência à área na distribuição <span class="math inline">\(F\)</span> que fica acima de <span class="math inline">\(F_{calculado}\)</span>. Poderíamos tentar observar representar este valor visualmente na distribuição <span class="math inline">\(F\)</span>, mas ele é tão pequeno, que a área em vermelho sequer aparece na figura.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-351-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Como conclusão temos que <span class="math inline">\(p \le \alpha\)</span> nos leva a <strong>REJEITAR <span class="math inline">\(H_0\)</span></strong>, pois <span class="math inline">\(F_{calculado}\)</span> é muito extremo para ser resultante da hipótese nula. Neste caso, assumimos que a <span class="math inline">\(H_a\)</span> é mais condizente com a estrutura dos dados, de modo que os tratamentos devem ser provenientes de populações estatísticas com diferentes médias <span class="math inline">\(\mu\)</span>.</p>
</div>
<div id="testes-a-posteriori-de-comparação-de-médias" class="section level2" number="20.6">
<h2><span class="header-section-number">20.6</span> Testes a <em>posteriori</em> de comparação de médias</h2>
<p>Tendo rejeitado <span class="math inline">\(H_0\)</span> concluímos que ao menos 1 par médias é diferente entre si, saber qual(is). Isto nos leva a buscar por um teste que permita fazer comparações <strong>par-a-par</strong>. Os testes a <em>posteriori</em> são uma alternativa.</p>
<p>Entre os diferentes testes a <em>posteriori</em> na literatura discutiremos o <a href="https://en.wikipedia.org/wiki/Tukey%27s_range_test" target="_blank">teste de Tukey</a>, em que o objetivo é estabelecer uma <em>Diferença Honesta Significativa</em> (<em>DHS</em>) entre um dado par de médias. Esta diferença pode ser calculada por:</p>
<p><span class="math display">\[DHS_{12} = q\sqrt{\left(\frac{1}{n_1} + \frac{1}{n_2}\right)QM_{Res}}\]</span></p>
<p>onde:</p>
<p><span class="math inline">\(q\)</span>: é um valor retirado de uma <strong>tabela estatística da distribuição de amplitude normalizada</strong> (<em>studentized range q table</em>). Para um dado <span class="math inline">\(\alpha\)</span>, o valor desejado de <span class="math inline">\(q\)</span> é encontrado cruzando a linha contento o número de grupos <span class="math inline">\(k\)</span> tratamentos do experimento com a linha contendo os graus de liberdade do resíduo (<span class="math inline">\(gl_{Res}\)</span>). Veja um exemplo desta tabela no link: <a href="https://www.real-statistics.com/statistics-tables/studentized-range-q-table/" target="_blank">Studentized Range q Table</a>;</p>
<p><span class="math inline">\(QM_{Res}\)</span>: é quadrado médio do resíduo obtido na ANOVA, e;</p>
<p><span class="math inline">\(n_1\)</span>, <span class="math inline">\(n_2\)</span>: os tamanhos amostrais de cada grupo envolvido na comparação.</p>
<p>Para um dado nível de significância <span class="math inline">\(\alpha\)</span>, a <span class="math inline">\(DHS\)</span> irá depender basicamente da variação residual do modelo de ANOVA e dos tamanhos amostrais de cada grupo. Em um experimento <strong>balanceado</strong>, isto é, onde <span class="math inline">\(n_1 = n_2 = \cdots = n_k = n\)</span>, a diferença mínima para que um par de médias seja cosiderado diferente é sempre a mesma.</p>
<p>Em nosso exemplo, a <span class="math inline">\(DHS\)</span> com <span class="math inline">\(\alpha = 0.05\)</span> será:</p>
<p><span class="math inline">\(DHS = 3.773\sqrt{\left(\frac{1}{5} + \frac{1}{5}\right)30.214} = 13.116\)</span></p>
<p>Assim, qualquer diferença entre pares de médias maior ou igual a <span class="math inline">\(13.116\)</span> será considerada <strong>estatisticamente significativa</strong>, nos levando a concluir que aqueles grupos têm médias populacionais distintas.</p>
<p>Em nosso exemplo, as médias dos grupos foram:</p>
<ul>
<li><p>Grupo <code>A</code>: <span class="math inline">\(\overline{Y}_A = 20.64\)</span></p></li>
<li><p>Grupo <code>B</code>: <span class="math inline">\(\overline{Y}_B = 28.68\)</span></p></li>
<li><p>Grupo <code>C</code>: <span class="math inline">\(\overline{Y}_C = 12.18\)</span></p></li>
</ul>
<p>E as diferenças (<span class="math inline">\(\overline{Y}_{maior} - \overline{Y}_{menor}\)</span>) entre elas:</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
A
</th>
<th style="text-align:right;">
B
</th>
<th style="text-align:right;">
C
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
8.04
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
8.46
</td>
<td style="text-align:right;">
16.5
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Das três comparações possíveis, somente a comparação entre os grupos <code>B</code> e <code>C</code> (<span class="math inline">\(\overline{Y}_B - \overline{Y}_C = 16.5\)</span>) foi maior que o limite estabelecido pelo teste de Tukey. Desta forma, concluímos que a ANOVA foi significativa e que somente os grupos <code>B</code> e <code>C</code> diferem entre si.</p>
</div>
<div id="ajustando-a-anova-no-r" class="section level2" number="20.7">
<h2><span class="header-section-number">20.7</span> Ajustando a ANOVA no R</h2>
<p>Considere que a tabela em nosso exemplo está no objeto <code>Tab</code>. A ANOVA no R é feita com o comando <code>aov</code>.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="anova.html#cb189-1" aria-hidden="true" tabindex="-1"></a>ajuste <span class="ot">=</span> <span class="fu">aov</span>(Y <span class="sc">~</span> X, <span class="at">data  =</span> Tab)</span>
<span id="cb189-2"><a href="anova.html#cb189-2" aria-hidden="true" tabindex="-1"></a>ajuste</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = Y ~ X, data = Tab)
## 
## Terms:
##                       X Residuals
## Sum of Squares  680.772   362.568
## Deg. of Freedom       2        12
## 
## Residual standard error: 5.496726
## Estimated effects may be unbalanced</code></pre>
<blockquote>
<p>A notação <code>Y ~ X</code> será muito utilizada nesta seção sobre modelos lineares e lê-se como <strong><span class="math inline">\(Y\)</span> é função de <span class="math inline">\(X\)</span></strong>.</p>
</blockquote>
<p>O comando acima fez os cálculos da ANOVA, isto é, computou as somas dos quadrados, os graus de liberdade, os quadrados médios, o <span class="math inline">\(F_{calculado}\)</span> e o valor de <span class="math inline">\(p\)</span>. Para visualizarmos a tabela da ANOVA fazemos:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="anova.html#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ajuste)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Y
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## X          2 680.77  340.39  11.266 0.001761 **
## Residuals 12 362.57   30.21                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note que os resultados coincidem com o que apresentamos anteriormente. Como o valor de <span class="math inline">\(p\)</span> foi menor que <span class="math inline">\(\alpha = 0.05\)</span>, concluimos que a ANOVA foi significativa, isto é, indicou que ao menos um par de médias difere ente si. Podemos fazer o teste a <em>posteriori</em> de Tukey com o comando:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="anova.html#cb193-1" aria-hidden="true" tabindex="-1"></a>alfa <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb193-2"><a href="anova.html#cb193-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(ajuste, <span class="at">conf.level =</span> <span class="dv">1</span><span class="sc">-</span>alfa)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Y ~ X, data = Tab)
## 
## $X
##       diff        lwr        upr     p adj
## B-A   8.04  -1.234654 17.3146545 0.0923564
## C-A  -8.46 -17.734654  0.8146545 0.0751622
## C-B -16.50 -25.774654 -7.2253455 0.0012751</code></pre>
<p>O resultado apresenta todas as comparações possíveis entre os grupos, mostrando as diferenças de médias, seus intervalos de confiança a <span class="math inline">\(95\%\)</span> e os valores de <span class="math inline">\(p\)</span>, indicando quais destas diferenças são significativas, isto é, <span class="math inline">\(p \le \alpha\)</span>. Estes resultados nos permitem concluir novamente que somente o par <code>C-B</code> difere entre si, pois <code>p adj &lt; 0.05</code>.</p>
<p>Um gráfico facilita a visualização das comparações, sobretudo em situações com muitos pares de médias envolvidos:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="anova.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(ajuste))</span></code></pre></div>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-357-1.png" width="672" /></p>
<p>Neste gráfico, as comparações em que o intervalo de confiança <strong>não inclui o zero</strong>, são consideradas significativas. Novamente, vemos que somente o grupo <code>C-B</code> tem médias estatisticamente diferentes.</p>
</div>
<div id="pressupostos-da-anova" class="section level2" number="20.8">
<h2><span class="header-section-number">20.8</span> Pressupostos da ANOVA</h2>
<p>Os pressupostos da ANOVA são:</p>
<ol style="list-style-type: decimal">
<li><p>Os observação são independentes e;</p></li>
<li><p>A variância dos resíduos é homogênea e;</p></li>
<li><p>Os resíduos têm distribuição normal com média <span class="math inline">\(0\)</span> e variância <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ol>
<p>Vamos inicialmente testar o pressuposto de homogeneidade de variâncias com um teste <span class="math inline">\(F\)</span>.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="anova.html#cb196-1" aria-hidden="true" tabindex="-1"></a>Tab <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(X) <span class="sc">%&gt;%</span> </span>
<span id="cb196-2"><a href="anova.html#cb196-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Var =</span> <span class="fu">var</span>(Y))</span></code></pre></div>
<p>Note que a maior variância é <span class="math inline">\(56.347\)</span> e a menor <span class="math inline">\(11.152\)</span>.</p>
<p>O teste <span class="math inline">\(F\)</span> consiste em dividir a maior variância pela menor:</p>
<pre><code>## 
##  F test to compare two variances
## 
## data:  Tab$Y[Tab$X == &quot;C&quot;] and Tab$Y[Tab$X == &quot;B&quot;]
## F = 5.0526, num df = 4, denom df = 4, p-value = 0.1457
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   0.526068 48.528196
## sample estimates:
## ratio of variances 
##           5.052636</code></pre>
<p>A maior variância foi 5.05 vezes maior que a menor variância e o test F sugere que esta diferença é <strong>não-significativa</strong> a <span class="math inline">\(5\%\)</span> (<span class="math inline">\(p &lt; 0.05\)</span>). Isto indica que as variâncias são homogêneas.</p>
<p>A verificação visual de que as variâncias são homogêneas pode também ser inspecionada pelo <strong>gráfico de resíduos</strong>:</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-361-1.png" width="672" /></p>
<p>Em seguida avaliamos o histograma dos resíduos e aplicamos um teste de normalidade (ex. teste de Shapiro-Wilk) para verificar se o pressuposto de normalidade pode ser aceito.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-362-1.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  rstudent(ajuste)
## W = 0.93171, p-value = 0.2894</code></pre>
<p>Neste caso, o valor de <span class="math inline">\(p &gt; 0.05\)</span> indica não haver desvio da normalidade.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modlinear.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anovafatorial.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["probest-cambientais.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
