<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais</title>
  <meta name="description" content="Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais" />
  
  <meta name="twitter:description" content="Capítulo 9 Análise bidimensional: variáveis qualitativas | Estatística nas Ciências Ambientais" />
  

<meta name="author" content="Fabio Cop Ferreira" />
<meta name="author" content="fabiocopf@gmail.com; fcferreira@unifesp.br" />
<meta name="author" content="Instituto do Mar, Universidade Federal de São Paulo" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="escorez.html"/>
<link rel="next" href="biquant.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.20/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estatística nas Ciências Ambientais</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Índice</a></li>
<li class="part"><span><b>I Estatística descritiva</b></span></li>
<li class="chapter" data-level="1" data-path="estrdados.html"><a href="estrdados.html"><i class="fa fa-check"></i><b>1</b> Estrutura e tipo de dados</a>
<ul>
<li class="chapter" data-level="1.1" data-path="estrdados.html"><a href="estrdados.html#unidades-amostrais-e-descritores"><i class="fa fa-check"></i><b>1.1</b> Unidades amostrais e descritores</a></li>
<li class="chapter" data-level="1.2" data-path="estrdados.html"><a href="estrdados.html#tipos-de-dados"><i class="fa fa-check"></i><b>1.2</b> Tipos de dados</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="estrdados.html"><a href="estrdados.html#variáveis-qualitativas"><i class="fa fa-check"></i><b>1.2.1</b> Variáveis qualitativas</a></li>
<li class="chapter" data-level="1.2.2" data-path="estrdados.html"><a href="estrdados.html#variáveis-quantitativas"><i class="fa fa-check"></i><b>1.2.2</b> Variáveis quantitativas</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="estrdados.html"><a href="estrdados.html#níveis-de-mensuração"><i class="fa fa-check"></i><b>1.3</b> Níveis de mensuração</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="procdados.html"><a href="procdados.html"><i class="fa fa-check"></i><b>2</b> Processamento de dados</a>
<ul>
<li class="chapter" data-level="2.1" data-path="procdados.html"><a href="procdados.html#criando-o-diretório-de-trabalho"><i class="fa fa-check"></i><b>2.1</b> Criando o diretório de trabalho</a></li>
<li class="chapter" data-level="2.2" data-path="procdados.html"><a href="procdados.html#iniciando-o-projeto-intro_estatistica"><i class="fa fa-check"></i><b>2.2</b> Iniciando o projeto <code>Intro_estatistica</code></a></li>
<li class="chapter" data-level="2.3" data-path="procdados.html"><a href="procdados.html#instalação-de-pacotes"><i class="fa fa-check"></i><b>2.3</b> Instalação de pacotes</a></li>
<li class="chapter" data-level="2.4" data-path="procdados.html"><a href="procdados.html#carregando-os-pacotes"><i class="fa fa-check"></i><b>2.4</b> Carregando os pacotes</a></li>
<li class="chapter" data-level="2.5" data-path="procdados.html"><a href="procdados.html#importanto-a-base-de-dados"><i class="fa fa-check"></i><b>2.5</b> Importanto a base de dados</a></li>
<li class="chapter" data-level="2.6" data-path="procdados.html"><a href="procdados.html#verificando-a-base-de-dados"><i class="fa fa-check"></i><b>2.6</b> Verificando a base de dados</a></li>
<li class="chapter" data-level="2.7" data-path="procdados.html"><a href="procdados.html#reorganizando-a-base-de-dados"><i class="fa fa-check"></i><b>2.7</b> Reorganizando a base de dados</a></li>
<li class="chapter" data-level="2.8" data-path="procdados.html"><a href="procdados.html#selecionando-colunas-da-tabela"><i class="fa fa-check"></i><b>2.8</b> Selecionando colunas da tabela</a></li>
<li class="chapter" data-level="2.9" data-path="procdados.html"><a href="procdados.html#filtrando-linhas-da-tabela"><i class="fa fa-check"></i><b>2.9</b> Filtrando linhas da tabela</a></li>
<li class="chapter" data-level="2.10" data-path="procdados.html"><a href="procdados.html#adicionando-ou-modificando-colunas"><i class="fa fa-check"></i><b>2.10</b> Adicionando ou modificando colunas</a></li>
<li class="chapter" data-level="2.11" data-path="procdados.html"><a href="procdados.html#renomeando-colunas"><i class="fa fa-check"></i><b>2.11</b> Renomeando colunas</a></li>
<li class="chapter" data-level="2.12" data-path="procdados.html"><a href="procdados.html#outras-operações-para-processamento-e-transformação-de-dados"><i class="fa fa-check"></i><b>2.12</b> Outras operações para processamento e transformação de dados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="varqualit.html"><a href="varqualit.html"><i class="fa fa-check"></i><b>3</b> Descrevendo variáveis qualitativas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="varqualit.html"><a href="varqualit.html#representação-em-tabelas-de-frequência"><i class="fa fa-check"></i><b>3.1</b> Representação em tabelas de frequência</a></li>
<li class="chapter" data-level="3.2" data-path="varqualit.html"><a href="varqualit.html#tabelas-de-frequência-para-variáveis-categóricas-ordenadas"><i class="fa fa-check"></i><b>3.2</b> Tabelas de frequência para variáveis categóricas ordenadas</a></li>
<li class="chapter" data-level="3.3" data-path="varqualit.html"><a href="varqualit.html#representação-gráfica"><i class="fa fa-check"></i><b>3.3</b> Representação gráfica</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="varqualit.html"><a href="varqualit.html#criando-um-gráfico-no-ggplot2"><i class="fa fa-check"></i><b>3.3.1</b> Criando um gráfico no <code>ggplot2</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="varquant.html"><a href="varquant.html"><i class="fa fa-check"></i><b>4</b> Descrevendo variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="varquant.html"><a href="varquant.html#tabelas-de-frequência-para-variáveis-quantitativas"><i class="fa fa-check"></i><b>4.1</b> Tabelas de frequência para variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="varquant.html"><a href="varquant.html#alterando-o-tamanho-dos-intervalos-de-classe"><i class="fa fa-check"></i><b>4.1.1</b> Alterando o tamanho dos intervalos de classe</a></li>
<li class="chapter" data-level="4.1.2" data-path="varquant.html"><a href="varquant.html#tabela-de-frequência-para-cpue"><i class="fa fa-check"></i><b>4.1.2</b> Tabela de frequência para <code>CPUE</code></a></li>
<li class="chapter" data-level="4.1.3" data-path="varquant.html"><a href="varquant.html#tabela-de-frequência-acumulada"><i class="fa fa-check"></i><b>4.1.3</b> Tabela de frequência acumulada</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="varquant.html"><a href="varquant.html#representação-gráfica-histogramas"><i class="fa fa-check"></i><b>4.2</b> Representação gráfica: histogramas</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="varquant.html"><a href="varquant.html#representando-frequências-acumuladas"><i class="fa fa-check"></i><b>4.2.1</b> Representando frequências acumuladas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tendcentral.html"><a href="tendcentral.html"><i class="fa fa-check"></i><b>5</b> Medidas de tendência central</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tendcentral.html"><a href="tendcentral.html#média-aritmética"><i class="fa fa-check"></i><b>5.1</b> Média aritmética</a></li>
<li class="chapter" data-level="5.2" data-path="tendcentral.html"><a href="tendcentral.html#mediana"><i class="fa fa-check"></i><b>5.2</b> Mediana</a></li>
<li class="chapter" data-level="5.3" data-path="tendcentral.html"><a href="tendcentral.html#moda"><i class="fa fa-check"></i><b>5.3</b> Moda</a></li>
<li class="chapter" data-level="5.4" data-path="tendcentral.html"><a href="tendcentral.html#ponto-médio"><i class="fa fa-check"></i><b>5.4</b> Ponto médio</a></li>
<li class="chapter" data-level="5.5" data-path="tendcentral.html"><a href="tendcentral.html#efeito-da-assimetria-sobre-os-descritores-de-tendência-central"><i class="fa fa-check"></i><b>5.5</b> Efeito da assimetria sobre os descritores de tendência central</a></li>
<li class="chapter" data-level="5.6" data-path="tendcentral.html"><a href="tendcentral.html#obtendo-medidas-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>5.6</b> Obtendo medidas de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="variacao.html"><a href="variacao.html"><i class="fa fa-check"></i><b>6</b> Medidas de variação</a>
<ul>
<li class="chapter" data-level="6.1" data-path="variacao.html"><a href="variacao.html#variância"><i class="fa fa-check"></i><b>6.1</b> Variância</a></li>
<li class="chapter" data-level="6.2" data-path="variacao.html"><a href="variacao.html#desvio-padrão"><i class="fa fa-check"></i><b>6.2</b> Desvio padrão</a></li>
<li class="chapter" data-level="6.3" data-path="variacao.html"><a href="variacao.html#coeficiente-de-variação"><i class="fa fa-check"></i><b>6.3</b> Coeficiente de variação</a></li>
<li class="chapter" data-level="6.4" data-path="variacao.html"><a href="variacao.html#amplitude-de-variação"><i class="fa fa-check"></i><b>6.4</b> Amplitude de variação</a></li>
<li class="chapter" data-level="6.5" data-path="variacao.html"><a href="variacao.html#obtendo-medidas-variação-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>6.5</b> Obtendo medidas variação de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="quartis.html"><a href="quartis.html"><i class="fa fa-check"></i><b>7</b> Medidas de posição: quartis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="quartis.html"><a href="quartis.html#cálculo-dos-quartis-na-posição-j-q_j-para-j-1-2-e-3"><i class="fa fa-check"></i><b>7.1</b> Cálculo dos quartis na posição <span class="math inline">\(j\)</span> (<span class="math inline">\(Q_j\)</span>, para <span class="math inline">\(j = 1\)</span>, <span class="math inline">\(2\)</span> e <span class="math inline">\(3\)</span>)</a></li>
<li class="chapter" data-level="7.2" data-path="quartis.html"><a href="quartis.html#cálculo-dos-quartis-no-r"><i class="fa fa-check"></i><b>7.2</b> Cálculo dos quartis no R</a></li>
<li class="chapter" data-level="7.3" data-path="quartis.html"><a href="quartis.html#obtendo-os-quartis-a-partir-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>7.3</b> Obtendo os quartis a partir de uma tabela de dados</a></li>
<li class="chapter" data-level="7.4" data-path="quartis.html"><a href="quartis.html#regresentação-gráfica-dos-quartis-boxplots"><i class="fa fa-check"></i><b>7.4</b> Regresentação gráfica dos quartis: Boxplots</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="escorez.html"><a href="escorez.html"><i class="fa fa-check"></i><b>8</b> Medidas de posição: índice Z</a>
<ul>
<li class="chapter" data-level="8.1" data-path="escorez.html"><a href="escorez.html#interpretando-o-valor-de-z"><i class="fa fa-check"></i><b>8.1</b> Interpretando o valor de <span class="math inline">\(Z\)</span></a></li>
<li class="chapter" data-level="8.2" data-path="escorez.html"><a href="escorez.html#realizando-a-transformação-z-a-partir-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>8.2</b> Realizando a transformação <span class="math inline">\(Z\)</span> a partir de uma tabela de dados</a></li>
<li class="chapter" data-level="8.3" data-path="escorez.html"><a href="escorez.html#valores-esperados-de-z-em-uma-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>8.3</b> Valores esperados de <span class="math inline">\(Z\)</span> em uma distribuição normal padronizada</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="biquali.html"><a href="biquali.html"><i class="fa fa-check"></i><b>9</b> Análise bidimensional: variáveis qualitativas</a>
<ul>
<li class="chapter" data-level="9.1" data-path="biquali.html"><a href="biquali.html#tabelas-de-contingência"><i class="fa fa-check"></i><b>9.1</b> Tabelas de contingência</a></li>
<li class="chapter" data-level="9.2" data-path="biquali.html"><a href="biquali.html#o-gráfico-de-barras-para-duas-variáveis-qualitativas"><i class="fa fa-check"></i><b>9.2</b> O gráfico de barras para duas variáveis qualitativas</a></li>
<li class="chapter" data-level="9.3" data-path="biquali.html"><a href="biquali.html#medindo-a-discrepância-com-o-índice-de-chi2-de-pearson"><i class="fa fa-check"></i><b>9.3</b> Medindo a discrepância com o índice de <span class="math inline">\(\chi^2\)</span> de Pearson</a></li>
<li class="chapter" data-level="9.4" data-path="biquali.html"><a href="biquali.html#o-índice-de-chi2-em-uma-tabela-de-contigência"><i class="fa fa-check"></i><b>9.4</b> O índice de <span class="math inline">\(\chi^2\)</span> em uma tabela de contigência</a></li>
<li class="chapter" data-level="9.5" data-path="biquali.html"><a href="biquali.html#valores-de-chi2-quando-existe-associação"><i class="fa fa-check"></i><b>9.5</b> Valores de <span class="math inline">\(\chi^2\)</span> quando existe associação</a></li>
<li class="chapter" data-level="9.6" data-path="biquali.html"><a href="biquali.html#variações-do-índice-de-chi2"><i class="fa fa-check"></i><b>9.6</b> Variações do índice de <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="9.7" data-path="biquali.html"><a href="biquali.html#obtendo-o-índice-de-chi2-de-uma-tabela-de-dados"><i class="fa fa-check"></i><b>9.7</b> Obtendo o índice de <span class="math inline">\(\chi^2\)</span> de uma tabela de dados</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="biquant.html"><a href="biquant.html"><i class="fa fa-check"></i><b>10</b> Análise bidimensional: variáveis quantitativas</a>
<ul>
<li class="chapter" data-level="10.1" data-path="biquant.html"><a href="biquant.html#covariância-entre-y-e-x"><i class="fa fa-check"></i><b>10.1</b> Covariância entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="10.2" data-path="biquant.html"><a href="biquant.html#coeficiente-de-correlação-linear-de-pearson-r"><i class="fa fa-check"></i><b>10.2</b> Coeficiente de correlação linear de Pearson <span class="math inline">\(r\)</span></a></li>
<li class="chapter" data-level="10.3" data-path="biquant.html"><a href="biquant.html#exemplo"><i class="fa fa-check"></i><b>10.3</b> Exemplo</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="biquantquali.html"><a href="biquantquali.html"><i class="fa fa-check"></i><b>11</b> Análise bidimensional: variáveis quantitativas e qualitativas</a>
<ul>
<li class="chapter" data-level="11.1" data-path="biquantquali.html"><a href="biquantquali.html#visualizando-a-distribuição-de-y-em-diferentes-grupos"><i class="fa fa-check"></i><b>11.1</b> Visualizando a distribuição de <span class="math inline">\(Y\)</span> em diferentes grupos</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="biquantquali.html"><a href="biquantquali.html#boxplots-para-os-níveis-do-tratamento"><i class="fa fa-check"></i><b>11.1.1</b> Boxplots para os níveis do tratamento</a></li>
<li class="chapter" data-level="11.1.2" data-path="biquantquali.html"><a href="biquantquali.html#o-gráfico-de-erros"><i class="fa fa-check"></i><b>11.1.2</b> O gráfico de erros</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="biquantquali.html"><a href="biquantquali.html#partição-das-soma-dos-quadrados"><i class="fa fa-check"></i><b>11.2</b> Partição das Soma dos Quadrados</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="biquantquali.html"><a href="biquantquali.html#a-característica-aditiva-das-somas-dos-quadrados"><i class="fa fa-check"></i><b>11.2.1</b> A característica aditiva das somas dos quadrados</a></li>
<li class="chapter" data-level="11.2.2" data-path="biquantquali.html"><a href="biquantquali.html#medindo-a-associação-entre-y-e-x"><i class="fa fa-check"></i><b>11.2.2</b> Medindo a associação entre <span class="math inline">\(Y\)</span> e <span class="math inline">\(X\)</span></a></li>
<li class="chapter" data-level="11.2.3" data-path="biquantquali.html"><a href="biquantquali.html#o-coeficiente-de-determinação-r2"><i class="fa fa-check"></i><b>11.2.3</b> O coeficiente de determinação (<span class="math inline">\(R^2\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="biquantquali.html"><a href="biquantquali.html#voltando-ao-conjundo-de-dados-medley.csv"><i class="fa fa-check"></i><b>11.3</b> Voltando ao conjundo de dados <code>medley.csv</code></a></li>
</ul></li>
<li class="part"><span><b>II Amostragem e Delineamento</b></span></li>
<li class="chapter" data-level="12" data-path="popamostra.html"><a href="popamostra.html"><i class="fa fa-check"></i><b>12</b> Descrevendo populações e amostras</a>
<ul>
<li class="chapter" data-level="12.1" data-path="popamostra.html"><a href="popamostra.html#população-amostra-e-unidade-amostral"><i class="fa fa-check"></i><b>12.1</b> População, amostra e unidade amostral</a></li>
<li class="chapter" data-level="12.2" data-path="popamostra.html"><a href="popamostra.html#distribuição-de-frequências-na-população-estatística"><i class="fa fa-check"></i><b>12.2</b> Distribuição de frequências na população estatística</a></li>
<li class="chapter" data-level="12.3" data-path="popamostra.html"><a href="popamostra.html#distribuições-de-frequências-na-amostra"><i class="fa fa-check"></i><b>12.3</b> Distribuições de frequências na amostra</a></li>
<li class="chapter" data-level="12.4" data-path="popamostra.html"><a href="popamostra.html#parâmetros-e-estimadores"><i class="fa fa-check"></i><b>12.4</b> Parâmetros e estimadores</a></li>
<li class="chapter" data-level="12.5" data-path="popamostra.html"><a href="popamostra.html#amostragem-e-inferência"><i class="fa fa-check"></i><b>12.5</b> Amostragem e inferência</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="amostrmedias.html"><a href="amostrmedias.html"><i class="fa fa-check"></i><b>13</b> Amostrando uma População Estatística</a>
<ul>
<li class="chapter" data-level="13.1" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>13.1</b> Amostragem aleatória simples</a></li>
<li class="chapter" data-level="13.2" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-estratificada"><i class="fa fa-check"></i><b>13.2</b> Amostragem aleatória estratificada</a></li>
<li class="chapter" data-level="13.3" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-sistemática"><i class="fa fa-check"></i><b>13.3</b> Amostragem sistemática</a></li>
<li class="chapter" data-level="13.4" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral-acurácia-e-precisão"><i class="fa fa-check"></i><b>13.4</b> Erro amostral, acurácia e precisão</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral"><i class="fa fa-check"></i><b>13.4.1</b> Erro amostral</a></li>
<li class="chapter" data-level="13.4.2" data-path="amostrmedias.html"><a href="amostrmedias.html#acurácia"><i class="fa fa-check"></i><b>13.4.2</b> Acurácia</a></li>
<li class="chapter" data-level="13.4.3" data-path="amostrmedias.html"><a href="amostrmedias.html#precisão-o-erro-padrão-da-média-sigmaoverlinex"><i class="fa fa-check"></i><b>13.4.3</b> Precisão: o erro padrão da média (<span class="math inline">\(\sigma^{\overline{X}}\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Inferência Estatística e Teste de Hipóteses</b></span></li>
<li class="chapter" data-level="14" data-path="normdist.html"><a href="normdist.html"><i class="fa fa-check"></i><b>14</b> O modelo da distribuição normal</a>
<ul>
<li class="chapter" data-level="14.1" data-path="normdist.html"><a href="normdist.html#o-modelo-normal-de-probabilidades"><i class="fa fa-check"></i><b>14.1</b> O modelo normal de probabilidades</a></li>
<li class="chapter" data-level="14.2" data-path="normdist.html"><a href="normdist.html#entendendo-a-função-normal-de-densidade-de-probabilidade"><i class="fa fa-check"></i><b>14.2</b> Entendendo a função normal de densidade de probabilidade</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="normdist.html"><a href="normdist.html#obtenção-de-fx-no-r-a-função-dnorm"><i class="fa fa-check"></i><b>14.2.1</b> Obtenção de <span class="math inline">\(f(x)\)</span> no R: a função <code>dnorm()</code></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="normdist.html"><a href="normdist.html#fazendo-predições-com-a-função-normal-de-densidade"><i class="fa fa-check"></i><b>14.3</b> Fazendo predições com a função normal de densidade</a></li>
<li class="chapter" data-level="14.4" data-path="normdist.html"><a href="normdist.html#a-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>14.4</b> A distribuição normal padronizada</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="normdist.html"><a href="normdist.html#probabilidades-em-uma-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>14.4.1</b> Probabilidades em uma distribuição normal padronizada</a></li>
<li class="chapter" data-level="14.4.2" data-path="normdist.html"><a href="normdist.html#tabela-z"><i class="fa fa-check"></i><b>14.4.2</b> Tabela <span class="math inline">\(Z\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="normdist.html"><a href="normdist.html#exercícios-resolvidos"><i class="fa fa-check"></i><b>14.5</b> Exercícios resolvidos</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="normdist.html"><a href="normdist.html#distribuição-de-comprimento"><i class="fa fa-check"></i><b>14.5.1</b> Distribuição de comprimento</a></li>
<li class="chapter" data-level="14.5.2" data-path="normdist.html"><a href="normdist.html#intervalos-em-uma-distribuição-normal"><i class="fa fa-check"></i><b>14.5.2</b> Intervalos em uma distribuição normal</a></li>
<li class="chapter" data-level="14.5.3" data-path="normdist.html"><a href="normdist.html#quantos-desvios-padrões"><i class="fa fa-check"></i><b>14.5.3</b> Quantos desvios padrões?</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="normdist.html"><a href="normdist.html#exercícios-propostos"><i class="fa fa-check"></i><b>14.6</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="tcl.html"><a href="tcl.html"><i class="fa fa-check"></i><b>15</b> Distribuição das médias amostrais</a>
<ul>
<li class="chapter" data-level="15.1" data-path="tcl.html"><a href="tcl.html#teorema-central-do-limite"><i class="fa fa-check"></i><b>15.1</b> Teorema Central do Limite</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="tcl.html"><a href="tcl.html#probabilidades-na-amostra-original-e-na-distribuição-de-médias"><i class="fa fa-check"></i><b>15.1.1</b> Probabilidades na amostra original e na distribuição de médias</a></li>
<li class="chapter" data-level="15.1.2" data-path="tcl.html"><a href="tcl.html#distribuições-não-normais"><i class="fa fa-check"></i><b>15.1.2</b> Distribuições não-normais</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="tcl.html"><a href="tcl.html#exercícios-resolvidos-1"><i class="fa fa-check"></i><b>15.2</b> Exercícios resolvidos:</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="tcl.html"><a href="tcl.html#tamanho-médio-de-robalos-no-mercado-de-peixes"><i class="fa fa-check"></i><b>15.2.1</b> Tamanho médio de robalos no mercado de peixes</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="tcl.html"><a href="tcl.html#exercícios-propostos-1"><i class="fa fa-check"></i><b>15.3</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="inferenc.html"><a href="inferenc.html"><i class="fa fa-check"></i><b>16</b> Inferindo sobre uma População Estatística</a>
<ul>
<li class="chapter" data-level="16.1" data-path="inferenc.html"><a href="inferenc.html#estimação-pontual-e-estimação-intervalar"><i class="fa fa-check"></i><b>16.1</b> Estimação pontual e estimação intervalar</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="inferenc.html"><a href="inferenc.html#intervalo-de-confiança"><i class="fa fa-check"></i><b>16.1.1</b> Intervalo de confiança</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="inferenc.html"><a href="inferenc.html#introdução-à-suficiência-amostral"><i class="fa fa-check"></i><b>16.2</b> Introdução à suficiência amostral</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="inferenc.html"><a href="inferenc.html#nível-de-acurácia-desejado-margem-de-erro-e-nível-de-confiança-na-estimativa"><i class="fa fa-check"></i><b>16.2.1</b> Nível de acurácia desejado (margem de erro) e nível de confiança na estimativa</a></li>
<li class="chapter" data-level="16.2.2" data-path="inferenc.html"><a href="inferenc.html#determinando-o-tamanho-de-uma-amostra"><i class="fa fa-check"></i><b>16.2.2</b> Determinando o tamanho de uma amostra</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="th.html"><a href="th.html"><i class="fa fa-check"></i><b>17</b> Introdução ao Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="17.1" data-path="th.html"><a href="th.html#probabilidade-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>17.1</b> Probabilidade e teste de hipóteses</a></li>
<li class="chapter" data-level="17.2" data-path="th.html"><a href="th.html#exemplificando-um-teste-de-hipóteses-o-teste-z"><i class="fa fa-check"></i><b>17.2</b> Exemplificando um teste de hipóteses: o teste z</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="th.html"><a href="th.html#tomada-de-decisão-sobre-h_0-nível-de-significância"><i class="fa fa-check"></i><b>17.2.1</b> Tomada de decisão sobre <span class="math inline">\(H_0\)</span>: nível de significância</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="th.html"><a href="th.html#erros-de-decisão-em-um-teste-de-hipóteses"><i class="fa fa-check"></i><b>17.3</b> Erros de decisão em um teste de hipóteses</a></li>
<li class="chapter" data-level="17.4" data-path="th.html"><a href="th.html#exemplo-de-um-teste-de-hipótese-teste-t-para-uma-média-populacional"><i class="fa fa-check"></i><b>17.4</b> Exemplo de um teste de hipótese: teste t para uma média populacional</a></li>
<li class="chapter" data-level="17.5" data-path="th.html"><a href="th.html#graus-de-liberdade"><i class="fa fa-check"></i><b>17.5</b> Graus de liberdade</a></li>
<li class="chapter" data-level="17.6" data-path="th.html"><a href="th.html#probabilidades-no-teste-t-de-student-a-tabela-t"><i class="fa fa-check"></i><b>17.6</b> Probabilidades no teste <span class="math inline">\(t\)</span> de Student: a tabela <span class="math inline">\(t\)</span></a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="testet.html"><a href="testet.html"><i class="fa fa-check"></i><b>18</b> Teste t para duas amostras</a>
<ul>
<li class="chapter" data-level="18.1" data-path="testet.html"><a href="testet.html#teste-t-para-comparação-de-duas-médias-independentes"><i class="fa fa-check"></i><b>18.1</b> Teste t para comparação de duas médias independentes</a></li>
</ul></li>
<li class="part"><span><b>IV Modelos Lineares Clássicos</b></span></li>
<li class="chapter" data-level="19" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>19</b> Análise de variância de um fator</a>
<ul>
<li class="chapter" data-level="19.1" data-path="anova.html"><a href="anova.html#o-modelo-da-anova"><i class="fa fa-check"></i><b>19.1</b> O modelo da ANOVA</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="anova.html"><a href="anova.html#quadrados-médios"><i class="fa fa-check"></i><b>19.1.1</b> Quadrados médios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="anovafatorial.html"><a href="anovafatorial.html"><i class="fa fa-check"></i><b>20</b> Análise de variância fatorial</a></li>
<li class="chapter" data-level="21" data-path="regressao.html"><a href="regressao.html"><i class="fa fa-check"></i><b>21</b> Regressão linear e correlação</a>
<ul>
<li class="chapter" data-level="21.1" data-path="regressao.html"><a href="regressao.html#modelo-geral-de-regressão"><i class="fa fa-check"></i><b>21.1</b> Modelo geral de regressão</a>
<ul>
<li class="chapter" data-level="21.1.1" data-path="regressao.html"><a href="regressao.html#porção-determinística"><i class="fa fa-check"></i><b>21.1.1</b> Porção determinística</a></li>
<li class="chapter" data-level="21.1.2" data-path="regressao.html"><a href="regressao.html#porção-estocástica"><i class="fa fa-check"></i><b>21.1.2</b> Porção estocástica</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="regressao.html"><a href="regressao.html#ajuste-dos-dados-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>21.2</b> Ajuste dos dados ao modelo de regressão</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="regressao.html"><a href="regressao.html#método-dos-mínimos-quadrados"><i class="fa fa-check"></i><b>21.2.1</b> Método dos mínimos quadrados</a></li>
<li class="chapter" data-level="21.2.2" data-path="regressao.html"><a href="regressao.html#variâncias-covariâncias-e-coeficientes-da-regressão"><i class="fa fa-check"></i><b>21.2.2</b> Variâncias, covariâncias e coeficientes da regressão</a></li>
<li class="chapter" data-level="21.2.3" data-path="regressao.html"><a href="regressao.html#exemplo-de-ajuste-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>21.2.3</b> Exemplo de ajuste ao modelo de regressão</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="regressao.html"><a href="regressao.html#testes-de-hipóteses-na-regressão-linear-simples"><i class="fa fa-check"></i><b>21.3</b> Testes de hipóteses na regressão linear simples</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="regressao.html"><a href="regressao.html#teste-sobre-beta_1"><i class="fa fa-check"></i><b>21.3.1</b> Teste sobre <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="21.3.2" data-path="regressao.html"><a href="regressao.html#análise-de-variância-da-regressão"><i class="fa fa-check"></i><b>21.3.2</b> Análise de variância da regressão</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="regressao.html"><a href="regressao.html#coeficiente-de-determinação-r2"><i class="fa fa-check"></i><b>21.4</b> Coeficiente de determinação <span class="math inline">\(r^2\)</span></a></li>
<li class="chapter" data-level="21.5" data-path="regressao.html"><a href="regressao.html#intervalo-de-confiança-de-y"><i class="fa fa-check"></i><b>21.5</b> Intervalo de confiança de <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="21.6" data-path="regressao.html"><a href="regressao.html#pressupostos-da-regressão-linear-simples"><i class="fa fa-check"></i><b>21.6</b> Pressupostos da regressão linear simples</a>
<ul>
<li class="chapter" data-level="21.6.1" data-path="regressao.html"><a href="regressao.html#relação-funcional-linear"><i class="fa fa-check"></i><b>21.6.1</b> Relação funcional linear</a></li>
<li class="chapter" data-level="21.6.2" data-path="regressao.html"><a href="regressao.html#independência"><i class="fa fa-check"></i><b>21.6.2</b> Independência</a></li>
<li class="chapter" data-level="21.6.3" data-path="regressao.html"><a href="regressao.html#variável-x-é-medida-sem-erros"><i class="fa fa-check"></i><b>21.6.3</b> Variável <span class="math inline">\(X\)</span> é medida sem erros</a></li>
<li class="chapter" data-level="21.6.4" data-path="regressao.html"><a href="regressao.html#distribuição-normal-dos-resíduos"><i class="fa fa-check"></i><b>21.6.4</b> Distribuição normal dos resíduos</a></li>
<li class="chapter" data-level="21.6.5" data-path="regressao.html"><a href="regressao.html#variância-residual-constante"><i class="fa fa-check"></i><b>21.6.5</b> Variância residual constante</a></li>
</ul></li>
<li class="chapter" data-level="21.7" data-path="regressao.html"><a href="regressao.html#diagnósticos-da-regressão"><i class="fa fa-check"></i><b>21.7</b> Diagnósticos da regressão</a>
<ul>
<li class="chapter" data-level="21.7.1" data-path="regressao.html"><a href="regressao.html#gráfico-de-resíduos"><i class="fa fa-check"></i><b>21.7.1</b> Gráfico de resíduos</a></li>
<li class="chapter" data-level="21.7.2" data-path="regressao.html"><a href="regressao.html#histograma-dos-resíduos"><i class="fa fa-check"></i><b>21.7.2</b> Histograma dos resíduos</a></li>
</ul></li>
<li class="chapter" data-level="21.8" data-path="regressao.html"><a href="regressao.html#coeficiente-de-correlação-de-pearson-r"><i class="fa fa-check"></i><b>21.8</b> Coeficiente de correlação de Pearson <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="21.8.1" data-path="regressao.html"><a href="regressao.html#teste-de-hipóteses-para-r"><i class="fa fa-check"></i><b>21.8.1</b> Teste de hipóteses para <span class="math inline">\(r\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="22" data-path="regresmultipla.html"><a href="regresmultipla.html"><i class="fa fa-check"></i><b>22</b> Regressão linear múltipla</a></li>
<li class="chapter" data-level="23" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>23</b> Análise de covariância</a></li>
<li class="chapter" data-level="24" data-path="repanova.html"><a href="repanova.html"><i class="fa fa-check"></i><b>24</b> Análise de variância de medidas repetidas</a></li>
<li class="part"><span><b>V Fundamentos de probabilidade</b></span></li>
<li class="chapter" data-level="25" data-path="espacoamostral.html"><a href="espacoamostral.html"><i class="fa fa-check"></i><b>25</b> O espaço de possibilidades de um experimento</a>
<ul>
<li class="chapter" data-level="25.1" data-path="espacoamostral.html"><a href="espacoamostral.html#probabilidades-de-um-evento"><i class="fa fa-check"></i><b>25.1</b> Probabilidades de um evento</a>
<ul>
<li class="chapter" data-level="25.1.1" data-path="espacoamostral.html"><a href="espacoamostral.html#estimando-as-probabilidades-de-um-evento-por-amostragem"><i class="fa fa-check"></i><b>25.1.1</b> Estimando as probabilidades de um evento por amostragem</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="probregras.html"><a href="probregras.html"><i class="fa fa-check"></i><b>26</b> Combinando as probabilidades de eventos</a>
<ul>
<li class="chapter" data-level="26.1" data-path="probregras.html"><a href="probregras.html#eventos-complexos"><i class="fa fa-check"></i><b>26.1</b> Eventos complexos</a>
<ul>
<li class="chapter" data-level="26.1.1" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-venn"><i class="fa fa-check"></i><b>26.1.1</b> Representação de eventos: diagrama de Venn</a></li>
<li class="chapter" data-level="26.1.2" data-path="probregras.html"><a href="probregras.html#probabilidade-de-eventos-simples"><i class="fa fa-check"></i><b>26.1.2</b> Probabilidade de eventos simples</a></li>
<li class="chapter" data-level="26.1.3" data-path="probregras.html"><a href="probregras.html#probabilidade-da-união-de-eventos"><i class="fa fa-check"></i><b>26.1.3</b> Probabilidade da união de eventos</a></li>
<li class="chapter" data-level="26.1.4" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-árvore"><i class="fa fa-check"></i><b>26.1.4</b> Representação de eventos: diagrama de árvore</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="27" data-path="probcondind.html"><a href="probcondind.html"><i class="fa fa-check"></i><b>27</b> Probabilidade condicional e independência</a>
<ul>
<li class="chapter" data-level="27.1" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes"><i class="fa fa-check"></i><b>27.1</b> Eventos independentes</a>
<ul>
<li class="chapter" data-level="27.1.1" data-path="probcondind.html"><a href="probcondind.html#um-exemplo-de-eventos-independentes"><i class="fa fa-check"></i><b>27.1.1</b> Um exemplo de eventos independentes</a></li>
</ul></li>
<li class="chapter" data-level="27.2" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes-vs-mutuamente-exclusivos"><i class="fa fa-check"></i><b>27.2</b> Eventos independentes <em>vs</em> mutuamente exclusivos</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="tbayes.html"><a href="tbayes.html"><i class="fa fa-check"></i><b>28</b> Teorema de Bayes: atualizando o conhecimento</a>
<ul>
<li class="chapter" data-level="28.1" data-path="tbayes.html"><a href="tbayes.html#teorema-de-bayes"><i class="fa fa-check"></i><b>28.1</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="28.2" data-path="tbayes.html"><a href="tbayes.html#teorema-da-probabilidade-total"><i class="fa fa-check"></i><b>28.2</b> Teorema da probabilidade total</a></li>
<li class="chapter" data-level="28.3" data-path="tbayes.html"><a href="tbayes.html#o-problema-da-detecção-de-espécies"><i class="fa fa-check"></i><b>28.3</b> O problema da detecção de espécies</a>
<ul>
<li class="chapter" data-level="28.3.1" data-path="tbayes.html"><a href="tbayes.html#razão-de-verossimilhança-inferência-bayesiana-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>28.3.1</b> Razão de verossimilhança, inferência bayesiana e teste de hipóteses</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>VI Modelos Probabilísticos, verossimilhança e inferência bayesiana</b></span></li>
<li class="chapter" data-level="29" data-path="va.html"><a href="va.html"><i class="fa fa-check"></i><b>29</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos discretos</em></a>
<ul>
<li class="chapter" data-level="29.1" data-path="va.html"><a href="va.html#experimento-1-sucessos-e-fracassos"><i class="fa fa-check"></i><b>29.1</b> <em>Experimento 1</em>: Sucessos e fracassos</a>
<ul>
<li><a href="va.html#a-distribuição-de-probabilidade-de-y">A distribuição de probabilidade de <span class="math inline">\(Y\)</span></a></li>
<li><a href="va.html#uma-expressão-geral-para-py-y">Uma expressão geral para <span class="math inline">\(P(Y = y)\)</span></a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#função-de-distribuição-acumulada"><i class="fa fa-check"></i>Função de distribuição acumulada</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#estruturas-previsíveis-para-um-experimento-aleatório"><i class="fa fa-check"></i>Estruturas previsíveis para um experimento aleatório</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#alterando-os-parâmetros-do-modelo"><i class="fa fa-check"></i>Alterando os parâmetros do modelo</a></li>
</ul></li>
<li class="chapter" data-level="29.2" data-path="va.html"><a href="va.html#experimento-2-o-custo-de-1-sucesso"><i class="fa fa-check"></i><b>29.2</b> <em>Experimento 2</em>: O custo de 1 sucesso</a></li>
<li class="chapter" data-level="29.3" data-path="va.html"><a href="va.html#experimento-3-uma-sequência-de-sucessos"><i class="fa fa-check"></i><b>29.3</b> <em>Experimento 3</em>: Uma sequência de sucessos</a></li>
<li class="chapter" data-level="29.4" data-path="va.html"><a href="va.html#experimento-4-quantas-marcas-na-amostra"><i class="fa fa-check"></i><b>29.4</b> <em>Experimento 4</em>: Quantas marcas na amostra!</a></li>
<li class="chapter" data-level="29.5" data-path="va.html"><a href="va.html#experimento-5-contagem-por-unidade-de-área-tempo-.."><i class="fa fa-check"></i><b>29.5</b> <em>Experimento 5</em>: Contagem por unidade de área, tempo, …..</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="vacont.html"><a href="vacont.html"><i class="fa fa-check"></i><b>30</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos contínuos</em></a>
<ul>
<li class="chapter" data-level="30.1" data-path="vacont.html"><a href="vacont.html#alguns-fenômenos-têm-distribuição-normal"><i class="fa fa-check"></i><b>30.1</b> Alguns fenômenos têm distribuição normal</a></li>
<li class="chapter" data-level="30.2" data-path="vacont.html"><a href="vacont.html#outros-são-altamente-assimétricos"><i class="fa fa-check"></i><b>30.2</b> Outros são altamente assimétricos</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="detmodel.html"><a href="detmodel.html"><i class="fa fa-check"></i><b>31</b> Alguns modelos são determinísticos</a>
<ul>
<li class="chapter" data-level="31.1" data-path="detmodel.html"><a href="detmodel.html#modelo-linear"><i class="fa fa-check"></i><b>31.1</b> Modelo linear</a></li>
<li class="chapter" data-level="31.2" data-path="detmodel.html"><a href="detmodel.html#função-potência"><i class="fa fa-check"></i><b>31.2</b> Função potência</a></li>
<li class="chapter" data-level="31.3" data-path="detmodel.html"><a href="detmodel.html#modelo-de-michaelis-menten-ou-resposta-funcional-do-tipo-ii"><i class="fa fa-check"></i><b>31.3</b> Modelo de Michaelis-Menten (ou Resposta funcional do tipo II)</a></li>
<li class="chapter" data-level="31.4" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iii"><i class="fa fa-check"></i><b>31.4</b> Resposta funcional do tipo III</a></li>
<li class="chapter" data-level="31.5" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iv"><i class="fa fa-check"></i><b>31.5</b> Resposta funcional do tipo IV</a></li>
<li class="chapter" data-level="31.6" data-path="detmodel.html"><a href="detmodel.html#função-hiperbólica"><i class="fa fa-check"></i><b>31.6</b> Função hiperbólica</a></li>
<li class="chapter" data-level="31.7" data-path="detmodel.html"><a href="detmodel.html#função-exponencial"><i class="fa fa-check"></i><b>31.7</b> Função exponencial</a></li>
<li class="chapter" data-level="31.8" data-path="detmodel.html"><a href="detmodel.html#função-logística"><i class="fa fa-check"></i><b>31.8</b> Função logística</a></li>
<li class="chapter" data-level="31.9" data-path="detmodel.html"><a href="detmodel.html#modelo-monomolecular"><i class="fa fa-check"></i><b>31.9</b> Modelo monomolecular</a></li>
<li class="chapter" data-level="31.10" data-path="detmodel.html"><a href="detmodel.html#modelo-de-ricker"><i class="fa fa-check"></i><b>31.10</b> Modelo de Ricker</a></li>
<li class="chapter" data-level="31.11" data-path="detmodel.html"><a href="detmodel.html#modelo-de-gompertz"><i class="fa fa-check"></i><b>31.11</b> Modelo de Gompertz</a></li>
<li class="chapter" data-level="31.12" data-path="detmodel.html"><a href="detmodel.html#modelo-de-von-bertalanffy"><i class="fa fa-check"></i><b>31.12</b> Modelo de von Bertalanffy</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="modelstat.html"><a href="modelstat.html"><i class="fa fa-check"></i><b>32</b> As partes estocásticas e determinísticas de um modelo estatístico</a>
<ul>
<li class="chapter" data-level="32.1" data-path="modelstat.html"><a href="modelstat.html#a-parcela-aleatória"><i class="fa fa-check"></i><b>32.1</b> A parcela aleatória</a></li>
<li class="chapter" data-level="32.2" data-path="modelstat.html"><a href="modelstat.html#a-parcela-determinística"><i class="fa fa-check"></i><b>32.2</b> A parcela determinística</a></li>
<li class="chapter" data-level="32.3" data-path="modelstat.html"><a href="modelstat.html#mais-um-modelo-binomial-taxa-de-mortalidade-em-testes-dose-resposta"><i class="fa fa-check"></i><b>32.3</b> Mais um modelo Binomial: taxa de mortalidade em testes dose-resposta</a></li>
<li class="chapter" data-level="32.4" data-path="modelstat.html"><a href="modelstat.html#o-modelo-estatístico-da-regressão-linear"><i class="fa fa-check"></i><b>32.4</b> O modelo estatístico da regressão linear</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="emv.html"><a href="emv.html"><i class="fa fa-check"></i><b>33</b> Estimando os parâmetros: a ideia da Máxima Verossimilhança</a></li>
<li class="chapter" data-level="34" data-path="aic.html"><a href="aic.html"><i class="fa fa-check"></i><b>34</b> Comparando modelos: uma questão de parcimônia</a></li>
<li class="chapter" data-level="35" data-path="statbayes.html"><a href="statbayes.html"><i class="fa fa-check"></i><b>35</b> Da verossimilhança à estatística Bayesiana</a></li>
<li class="chapter" data-level="36" data-path="varmodels.html"><a href="varmodels.html"><i class="fa fa-check"></i><b>36</b> Uma variedade de modelos estatísticos: modelando a variância</a></li>
<li class="chapter" data-level="37" data-path="nindep.html"><a href="nindep.html"><i class="fa fa-check"></i><b>37</b> Uma variedade de modelos estatísticos: modelando os resíduos</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística nas Ciências Ambientais</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="biquali" class="section level1" number="9">
<h1><span class="header-section-number">Capítulo 9</span> Análise bidimensional: variáveis qualitativas</h1>
<p>Até agora exploramos formas de representar visualmente uma única variável por vez (Capítulos <a href="varqualit.html#varqualit">3</a> e <a href="varquant.html#varquant">4</a>) e discutimos medidas para descrever algumas propriedades desta variável (Capítulo <a href="tendcentral.html#tendcentral">5</a> a <a href="escorez.html#escorez">8</a>). A partir de agora veremos como representar e resumir <strong>padrões de associação</strong> entre pares de variáveis. Segundo a natureza dos dados envolvidos, estas associações podem ser entre:</p>
<ul>
<li><p>duas variáveis qualitativas (este capítulo);</p></li>
<li><p>duas variáveis quantitativas (Capítulo <a href="biquant.html#biquant">10</a>) e;</p></li>
<li><p>uma variável qualitativa e uma quantitativa (Capítulo <a href="biquantquali.html#biquantquali">11</a>)</p></li>
</ul>
<p><strong>Exemplo</strong></p>
<p>Imagine que haverá uma obra de revitalização de uma área na região central da cidade. A obra implicará na melhoria de acesso e segurança, ferta de serviços, mas levará tempo para ser concluída e precisará passar por ações de remoção de moradias irregulares, interdição de ruas e avenidas por longos períodos, etc. A prefeitura encomenda uma pesquisa para saber a opinião dos munícipes. A cada entrevistado são feitas duas perguntas:</p>
<ol style="list-style-type: decimal">
<li>Qual sua opinião sobre a necessidade de realização da obra?</li>
</ol>
<ul class="task-list">
<li><input type="checkbox" disabled="" />
A favor</li>
<li><input type="checkbox" disabled="" />
Contra</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Você reside na região diretamente afetada:</li>
</ol>
<ul class="task-list">
<li><input type="checkbox" disabled="" />
Residente</li>
<li><input type="checkbox" disabled="" />
Não-Residente</li>
</ul>
<p>A base de dados está disponível em: <a href="https://github.com/FCopf/probest-cambientais/blob/master/datasets/Entrevista_municipes.csv" target="_blank">Entrevista_municipes.csv</a></p>
<p>Importe a tabela e veja os primeiros 12 resultados das entrevistas:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="biquali.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carrega pacotes</span></span>
<span id="cb95-2"><a href="biquali.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb95-3"><a href="biquali.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Importa base de dados </span></span>
<span id="cb95-4"><a href="biquali.html#cb95-4" aria-hidden="true" tabindex="-1"></a>mun <span class="ot">=</span> <span class="fu">read_delim</span>(<span class="st">&#39;Entrevista_municipes.csv&#39;</span>,</span>
<span id="cb95-5"><a href="biquali.html#cb95-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">delim =</span> <span class="st">&#39;,&#39;</span>)</span>
<span id="cb95-6"><a href="biquali.html#cb95-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-7"><a href="biquali.html#cb95-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">nrow</span>(mun) <span class="co"># Número de entrevistados</span></span></code></pre></div>
<table class=" lightable-paper lightable-striped" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Entrevistado
</th>
<th style="text-align:left;">
Opiniao
</th>
<th style="text-align:left;">
Moradia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: #D7261E !important;">
4
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
A favor
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: #D7261E !important;">
5
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Contra
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Não-Residente
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: #D7261E !important;">
6
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Contra
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: white !important;background-color: #D7261E !important;">
7
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
A favor
</td>
<td style="text-align:left;font-weight: bold;color: white !important;background-color: #D7261E !important;">
Não-Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
Contra
</td>
<td style="text-align:left;">
Não-Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Não-Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Não-Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Residente
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:left;">
Não-Residente
</td>
</tr>
</tbody>
</table>
<p>Após entrevistar <span class="math inline">\(200\)</span> pessoas selecionadas <em>ao acaso</em> de uma lista da moradores da cidade, é construída uma tabela com três colunas: <code>Entrevistado</code> (sequência numérica do primeiro ao último respondente), <code>Opinião</code> e <code>Moradia</code>.</p>
<p>Estão descritos acima os resultados das primeiras 12 entrevistas, onde é possível ver ao menos uma combinação de todas as possíveis respostas. O entrevistado pode ser: i) <code>A favor</code> e ser <code>Residente</code> da região; ii) <code>A favor</code> e ser <code>Não-Residente</code>, iii) <code>Contra</code> e ser <code>Residente</code>; iv) <code>Contra</code> e ser <code>Não-Residente</code>.</p>
<p>Vamos inicialmente representar cada uma das variáveis individualmente por meio de uma tabela de frequência dos 200 entrevistados.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="biquali.html#cb96-1" aria-hidden="true" tabindex="-1"></a>resumo_opiniao <span class="ot">=</span> mun <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="biquali.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Opiniao) <span class="sc">%&gt;%</span> </span>
<span id="cb96-3"><a href="biquali.html#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Op_n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb96-4"><a href="biquali.html#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Op_rel =</span> Op_n<span class="sc">/</span><span class="fu">sum</span>(Op_n))</span>
<span id="cb96-5"><a href="biquali.html#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="biquali.html#cb96-6" aria-hidden="true" tabindex="-1"></a>resumo_opiniao</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
Opiniao
</th>
<th style="text-align:right;">
Op_n
</th>
<th style="text-align:right;">
Op_rel
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A favor
</td>
<td style="text-align:right;">
144
</td>
<td style="text-align:right;">
0.72
</td>
</tr>
<tr>
<td style="text-align:left;">
Contra
</td>
<td style="text-align:right;">
56
</td>
<td style="text-align:right;">
0.28
</td>
</tr>
</tbody>
</table>
<p>Das <span class="math inline">\(200\)</span> respostas tivemos <span class="math inline">\(144\)</span> pessoas A favor (<span class="math inline">\(72\%\)</span>) e <span class="math inline">\(56\)</span> pessoas Contra (<span class="math inline">\(28\%\)</span>).</p>
<p>Com relação ao local de residência:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="biquali.html#cb97-1" aria-hidden="true" tabindex="-1"></a>resumo_morad <span class="ot">=</span> mun <span class="sc">%&gt;%</span> </span>
<span id="cb97-2"><a href="biquali.html#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Moradia) <span class="sc">%&gt;%</span> </span>
<span id="cb97-3"><a href="biquali.html#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Morad_n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb97-4"><a href="biquali.html#cb97-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Morad_rel =</span> Morad_n<span class="sc">/</span><span class="fu">sum</span>(Morad_n))</span>
<span id="cb97-5"><a href="biquali.html#cb97-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-6"><a href="biquali.html#cb97-6" aria-hidden="true" tabindex="-1"></a>resumo_morad</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
Moradia
</th>
<th style="text-align:right;">
Morad_n
</th>
<th style="text-align:right;">
Morad_rel
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Não-Residente
</td>
<td style="text-align:right;">
117
</td>
<td style="text-align:right;">
0.585
</td>
</tr>
<tr>
<td style="text-align:left;">
Residente
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
0.415
</td>
</tr>
</tbody>
</table>
<p>Temos um total de <span class="math inline">\(117\)</span> pessoas Não-Residente (<span class="math inline">\(58.5\%\)</span>) e <span class="math inline">\(83\)</span> pessoas Residente (<span class="math inline">\(41.5\%\)</span>)</p>
<p>Se visualizarmos estes totais em gráficos de barras individuais teremos:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="biquali.html#cb98-1" aria-hidden="true" tabindex="-1"></a>plt_op <span class="ot">=</span> <span class="fu">ggplot</span>(mun, <span class="fu">aes</span>(<span class="at">x =</span> Opiniao)) <span class="sc">+</span></span>
<span id="cb98-2"><a href="biquali.html#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&#39;darkblue&#39;</span>, <span class="at">color =</span> <span class="st">&#39;white&#39;</span>) <span class="sc">+</span></span>
<span id="cb98-3"><a href="biquali.html#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">150</span>)) <span class="sc">+</span></span>
<span id="cb98-4"><a href="biquali.html#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&#39;Número de respostas&#39;</span>) <span class="sc">+</span></span>
<span id="cb98-5"><a href="biquali.html#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb98-6"><a href="biquali.html#cb98-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-7"><a href="biquali.html#cb98-7" aria-hidden="true" tabindex="-1"></a>plt_morad <span class="ot">=</span> <span class="fu">ggplot</span>(mun, <span class="fu">aes</span>(<span class="at">x =</span> Moradia)) <span class="sc">+</span></span>
<span id="cb98-8"><a href="biquali.html#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&#39;darkred&#39;</span>, <span class="at">color =</span> <span class="st">&#39;white&#39;</span>) <span class="sc">+</span></span>
<span id="cb98-9"><a href="biquali.html#cb98-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">150</span>)) <span class="sc">+</span></span>
<span id="cb98-10"><a href="biquali.html#cb98-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&#39;Número de respostas&#39;</span>) <span class="sc">+</span></span>
<span id="cb98-11"><a href="biquali.html#cb98-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb98-12"><a href="biquali.html#cb98-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-13"><a href="biquali.html#cb98-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Obs: para que a linha abaixo funcione, é necessário habilitar o pacote &#39;patchwork&#39;. </span></span>
<span id="cb98-14"><a href="biquali.html#cb98-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Caso não tenha, instale e carregue com os comandos:</span></span>
<span id="cb98-15"><a href="biquali.html#cb98-15" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&#39;patchwork&#39;)</span></span>
<span id="cb98-16"><a href="biquali.html#cb98-16" aria-hidden="true" tabindex="-1"></a><span class="co"># library(patchwork)</span></span>
<span id="cb98-17"><a href="biquali.html#cb98-17" aria-hidden="true" tabindex="-1"></a>plt_op <span class="sc">+</span> plt_morad</span></code></pre></div>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-180-1.png" width="672" /></p>
<p>Existe portanto um predomínio de pessoas <code>A Favor</code> e um ligeiro predomínio de entrevistados <code>Não-Residentes</code>.</p>
<p>Estamos interessados em entender se existe alguma <strong>associação</strong> entre as respostas dadas às duas perguntas, uma questão que pode ser colocada da seguinte forma:</p>
<blockquote>
<p>Será que moradores <code>Residentes</code> tendem ter uma opinião <strong>consistentemente</strong> diferente de moradores <code>Não-residentes</code> no que se refere a ser <code>A favor</code> ou <code>Contra</code> a obra?</p>
</blockquote>
<p>Para começar a entender esta questão vamos explorar a distribuição das variáveis conjuntamente.</p>
<div id="tabelas-de-contingência" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Tabelas de contingência</h2>
<p>Tabelas de contigência são organizadas para verificarmos a associação entre duas variáveis qualitativas. São conhecidas também como tabelas de <em>dupla entrada</em>. Nas colunas estão os níveis da variável <span class="math inline">\(X\)</span> e nas linhas os níveis da variável <span class="math inline">\(Y\)</span>.</p>
<p>Para nosso exemplo, podemos fazer simplesmente:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="biquali.html#cb99-1" aria-hidden="true" tabindex="-1"></a>tcont <span class="ot">=</span> <span class="fu">table</span>(mun<span class="sc">$</span>Opiniao, mun<span class="sc">$</span>Moradia)</span>
<span id="cb99-2"><a href="biquali.html#cb99-2" aria-hidden="true" tabindex="-1"></a>tcont</span></code></pre></div>
<pre><code>##          
##           Não-Residente Residente
##   A favor            81        63
##   Contra             36        20</code></pre>
<p>Temos portanto:</p>
<ul>
<li><p>81 - A favor e Não-Residente;</p></li>
<li><p>63 - A favor e Residente;</p></li>
<li><p>36 - Contra e Não-Residente;</p></li>
<li><p>20 - Contra e Residente</p></li>
</ul>
<p>Podemos ver os totais marginais das linhas:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="biquali.html#cb101-1" aria-hidden="true" tabindex="-1"></a>tcont_linhas <span class="ot">=</span> <span class="fu">apply</span>(tcont, <span class="dv">1</span>, sum) <span class="co"># Totais das linhas</span></span>
<span id="cb101-2"><a href="biquali.html#cb101-2" aria-hidden="true" tabindex="-1"></a>tcont_linhas</span></code></pre></div>
<pre><code>## A favor  Contra 
##     144      56</code></pre>
<p>Ou os totais marginais das colunas:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="biquali.html#cb103-1" aria-hidden="true" tabindex="-1"></a>tcont_colunas <span class="ot">=</span> <span class="fu">apply</span>(tcont, <span class="dv">2</span>, sum) <span class="co"># Totais das colunas</span></span>
<span id="cb103-2"><a href="biquali.html#cb103-2" aria-hidden="true" tabindex="-1"></a>tcont_colunas</span></code></pre></div>
<pre><code>## Não-Residente     Residente 
##           117            83</code></pre>
<p>Que são justamente os totais que verificamos nas distribuições individuais.</p>
<p>Se quisermos ver as frequências relativas <em>marginais</em> podemos fazer:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="biquali.html#cb105-1" aria-hidden="true" tabindex="-1"></a>trel_linha <span class="ot">=</span> <span class="fu">prop.table</span>(tcont, <span class="dv">1</span>) <span class="co"># Frequencia relativa marginal das linhas</span></span>
<span id="cb105-2"><a href="biquali.html#cb105-2" aria-hidden="true" tabindex="-1"></a>trel_linha</span></code></pre></div>
<pre><code>##          
##           Não-Residente Residente
##   A favor     0.5625000 0.4375000
##   Contra      0.6428571 0.3571429</code></pre>
<p>Neste caso, estamos vendo as <strong>frequências relativas das linhas</strong>, isto é, cada linha nesta tabela soma <span class="math inline">\(1\)</span>. O que vemos nesta tabela é:</p>
<ul>
<li><p>dos <span class="math inline">\(144\)</span> entrevistados que são A favor, cerca de <span class="math inline">\(56.25\%\)</span> são Não-Residente, enquanto os demais <span class="math inline">\(43.75\%\)</span> são Residente</p></li>
<li><p>dos <span class="math inline">\(56\)</span> entrevistados que são Contra, cerca de <span class="math inline">\(64.29\%\)</span> são Não-Residente, enquanto os demais <span class="math inline">\(35.71\%\)</span> são Residente</p></li>
</ul>
<p>Podemos fazer exatamente a mesma coisa olhando agora para as <strong>frequências marginais por colunas</strong>:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="biquali.html#cb107-1" aria-hidden="true" tabindex="-1"></a>trel_coluna <span class="ot">=</span> <span class="fu">prop.table</span>(tcont, <span class="dv">2</span>) <span class="co"># Frequencia relativa marginal das colunas</span></span>
<span id="cb107-2"><a href="biquali.html#cb107-2" aria-hidden="true" tabindex="-1"></a>trel_coluna</span></code></pre></div>
<pre><code>##          
##           Não-Residente Residente
##   A favor     0.6923077 0.7590361
##   Contra      0.3076923 0.2409639</code></pre>
<p>Neste caso são as <strong>colunas</strong> que somam <span class="math inline">\(1\)</span>, portanto:</p>
<ul>
<li><p>dos <span class="math inline">\(117\)</span> entrevistados que são Não-Residente, cerca de <span class="math inline">\(69.23\%\)</span> são A favor, enquanto os demais <span class="math inline">\(30.77\%\)</span> são Contra</p></li>
<li><p>dos <span class="math inline">\(83\)</span> entrevistados que são Residente, cerca de <span class="math inline">\(75.9\%\)</span> são A favor, enquanto os demais <span class="math inline">\(75.9\%\)</span> são Contra</p></li>
</ul>
<p>Podemos finalmente ver a frequência relativa conjunta:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="biquali.html#cb109-1" aria-hidden="true" tabindex="-1"></a>trel_conjunta <span class="ot">=</span> <span class="fu">prop.table</span>(tcont) <span class="co"># Frequencia relativa conjunta</span></span>
<span id="cb109-2"><a href="biquali.html#cb109-2" aria-hidden="true" tabindex="-1"></a>trel_conjunta</span></code></pre></div>
<pre><code>##          
##           Não-Residente Residente
##   A favor         0.405     0.315
##   Contra          0.180     0.100</code></pre>
<p>Neste caso, o somatório das linhas é igual a:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="biquali.html#cb111-1" aria-hidden="true" tabindex="-1"></a>tcont_linhas <span class="sc">/</span> <span class="fu">sum</span>(tcont_linhas)</span></code></pre></div>
<pre><code>## A favor  Contra 
##    0.72    0.28</code></pre>
<p>E indica os valores relativos das opiniões <code>A Favor</code> e <code>Contra</code>.</p>
<p>O somatório das colunas é igual a:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="biquali.html#cb113-1" aria-hidden="true" tabindex="-1"></a>tcont_colunas <span class="sc">/</span> <span class="fu">sum</span>(tcont_colunas)</span></code></pre></div>
<pre><code>## Não-Residente     Residente 
##         0.585         0.415</code></pre>
<p>E indica os valores relativos de <code>Não-Residentes</code> e <code>Residentes</code>.</p>
<p>Na tabela de frequência relativa conjunta, o somatório total da tabela deve ser igual a <span class="math inline">\(1\)</span>.</p>
</div>
<div id="o-gráfico-de-barras-para-duas-variáveis-qualitativas" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> O gráfico de barras para duas variáveis qualitativas</h2>
<p>Existem várias formas de gerar um gráfico de barras combinando as duas variáveis. Se quisermos utilizar a própria tabela de contingência obtida a partir do comando <code>table(mun$Opiniao, mun$Moradia)</code>, podemos utilizar o comando <code>barplot()</code>. Por outro lado, se quisermos utilizar a tabela original de dados (objeto <code>mun</code>) podemos fazer uso do pacote <code>ggplot2</code>:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="biquali.html#cb115-1" aria-hidden="true" tabindex="-1"></a>plt_bar1 <span class="ot">=</span> <span class="fu">ggplot</span>(mun) <span class="sc">+</span></span>
<span id="cb115-2"><a href="biquali.html#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Moradia, <span class="at">fill =</span> Opiniao) <span class="sc">+</span></span>
<span id="cb115-3"><a href="biquali.html#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">&#39;white&#39;</span>, <span class="at">position =</span> <span class="st">&#39;dodge&#39;</span>) <span class="sc">+</span></span>
<span id="cb115-4"><a href="biquali.html#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;Contra&#39;</span> <span class="ot">=</span> <span class="st">&#39;darkred&#39;</span>,</span>
<span id="cb115-5"><a href="biquali.html#cb115-5" aria-hidden="true" tabindex="-1"></a>                               <span class="st">&#39;A favor&#39;</span> <span class="ot">=</span> <span class="st">&#39;darkblue&#39;</span>)) <span class="sc">+</span></span>
<span id="cb115-6"><a href="biquali.html#cb115-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">80</span>)) <span class="sc">+</span></span>
<span id="cb115-7"><a href="biquali.html#cb115-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&#39;Número de respostas&#39;</span>) <span class="sc">+</span></span>
<span id="cb115-8"><a href="biquali.html#cb115-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb115-9"><a href="biquali.html#cb115-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-10"><a href="biquali.html#cb115-10" aria-hidden="true" tabindex="-1"></a>plt_bar1</span></code></pre></div>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-189-1.png" width="672" /></p>
<p>Veja que nesta figura, existem mais opiniões <code>A favor</code> <strong>independente</strong> do entrevistado ser ou não residente. Este padrão é o mesmo que observamos no gráfico da variável <code>Opinião</code> isoladamente. Isto sugere que <strong>não existe</strong> associação entre as variáveis <code>Opinião</code> e <code>Moradia</code>. Isto é, a opinião de um entrevistado sobre a construção da obra <strong>não depende</strong> do seu local de moradia.</p>
<hr />
<blockquote>
<p>Exemplos de associações entre duas variáveis</p>
</blockquote>
<hr />
<p>Abaixo são apresentadas situações em que <strong>existe</strong> uma associação.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-191-1.png" width="672" /></p>
<p>Em todos estes exemplos, note que a relação entre as opiniões <code>A favor</code> ou <code>Contra</code> <em>depende</em> se o entrevistado é ou não Residente na região. Todos estes padrões configuram uma <strong>associação</strong> entre as variáveis <code>Opinião</code> e <code>Moradia</code>.</p>
<ul>
<li><p>Figura A: Não-Residentes tendem a ser <code>A favor</code> e Residentes são em sua maioria <code>Contra</code>;</p></li>
<li><p>Figura B: Todos tendem a ser <code>Contra</code>, mas a diferença de opiniões é maior entre os Residentes;</p></li>
<li><p>Figura C: Não-Residentes tendem a ser <code>Contra</code>, enquanto não parece haver diferenças entre os Residentes;</p></li>
<li><p>Figura D: Residentes tendem a ser <code>A favor</code>, enquanto não parece haver diferenças entre os Residentes;</p></li>
</ul>
</div>
<div id="medindo-a-discrepância-com-o-índice-de-chi2-de-pearson" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Medindo a discrepância com o índice de <span class="math inline">\(\chi^2\)</span> de Pearson</h2>
<p>O índice de qui-quadrado (<span class="math inline">\(\chi^2\)</span>) mede a discrepância entre os valores <strong>observados</strong> e os valores <strong>esperados</strong> em uma tabela de contingência.</p>
<p>Digamos que um município tenha <span class="math inline">\(20\%\)</span> de sua população morando em área Rural e os outros <span class="math inline">\(80\%\)</span> em área Urbana. Se fizermos uma amostragem <em>ao acaso</em> dos moradores é esperado que esta frequência relativa se reflita na amostra. Neste caso se sorteamos <span class="math inline">\(200\)</span> pessoas, seria esperado:</p>
<ul>
<li><p>Zona Rural: <span class="math inline">\(40\)</span> moradores</p></li>
<li><p>Zona Urbana <span class="math inline">\(160\)</span> moradores</p></li>
</ul>
<table>
<thead>
<tr>
<th style="text-align:left;">
Moradia
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Rural
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
Urbana
</td>
<td style="text-align:right;">
160
</td>
</tr>
</tbody>
</table>
<p>Entretando, se fazemos um sorteio ao acaso, haverá alguma variação ao redor destes valores. O <span class="math inline">\(\chi^2\)</span> mede esta discrepância entre as frequências observadas (<span class="math inline">\(o\)</span>) e esperadas (<span class="math inline">\(e\)</span>) para cada célula da tabela:</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{n}\frac{(o_i - e_i)^2}{e_i}\]</span>
Para uma tabela de frequências, devemos determinar portanto os valores de <span class="math inline">\(o_i\)</span> e <span class="math inline">\(e_i\)</span>.</p>
<p>Suponha que uma amostra de <span class="math inline">\(200\)</span> moradores tenha resultado em:</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Moradia_obs
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Rural
</td>
<td style="text-align:right;">
31
</td>
</tr>
<tr>
<td style="text-align:left;">
Urbana
</td>
<td style="text-align:right;">
169
</td>
</tr>
</tbody>
</table>
<p>As frequências observadas e esperadas serão:</p>
<ul>
<li>Zona Rural:</li>
</ul>
<p><span class="math inline">\(o_{Rural} = 31\)</span></p>
<p><span class="math inline">\(e_{Rural} = 0.2 \times 200 = 40\)</span></p>
<ul>
<li>Zona Urbana</li>
</ul>
<p><span class="math inline">\(o_{Urbana} = 169\)</span></p>
<p><span class="math inline">\(e_{Urbana} = 0.8 \times 200 = 160\)</span></p>
<p>De modo que o valor de <span class="math inline">\(\chi^2\)</span> será:</p>
<p><span class="math inline">\(\chi^2 = \frac{(31 - 40)^2}{40} + \frac{(169 - 160)^2}{160} = \frac{(-9)^2}{40} + \frac{(9)^2}{160} = 2.025 + 0.50625 = 2.53125\)</span></p>
</div>
<div id="o-índice-de-chi2-em-uma-tabela-de-contigência" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> O índice de <span class="math inline">\(\chi^2\)</span> em uma tabela de contigência</h2>
<p>No exemplo acima, as contagens esperadas foram definidas a partir de um modelo que dizia que as populações rurais e urbanas se dividiam nas proporções <span class="math inline">\(20\%:80\%\)</span>. Em uma tabela de contigência, a hipótese em verificação é a de que <strong>não há associação entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span></strong>. Se for assim, é esperado que as frequências conjuntas sejam <em>p</em>orporcionais às frequências marginais*. Vamos apresentar esta ideia utilizando uma notação geral para tabelas de contingência e em seguida discutir com um exemplo.</p>
<p>A tabela abaixo apresenta <span class="math inline">\(r\)</span> linhas por <span class="math inline">\(s\)</span> colunas com as contagens de todas as combinações dos níveis da variável <span class="math inline">\(X\)</span> (Níveis <span class="math inline">\(A_{1}\)</span> a <span class="math inline">\(A_{r}\)</span>) e da variável <span class="math inline">\(Y\)</span> (Níveis <span class="math inline">\(B_{1}\)</span> a <span class="math inline">\(B_{s}\)</span>). Os totais marginais de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> são expressos respectivamente na última coluna e na última linha.</p>
<table>
<thead>
<tr class="header">
<th align="left">X ⟍ Y</th>
<th align="center"><span class="math inline">\(B_{1}\)</span></th>
<th align="center"><span class="math inline">\(B_{2}\)</span></th>
<th align="center"><span class="math inline">\(\cdots\)</span></th>
<th align="center"><span class="math inline">\(B_{j}\)</span></th>
<th align="center"><span class="math inline">\(\cdots\)</span></th>
<th align="center"><span class="math inline">\(B_{s}\)</span></th>
<th align="center">Totais em <span class="math inline">\(X\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(A_{1}\)</span></td>
<td align="center"><span class="math inline">\(n_{11}\)</span></td>
<td align="center"><span class="math inline">\(n_{12}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{1j}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{1s}\)</span></td>
<td align="center"><span class="math inline">\(n_{1.}\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(A_{2}\)</span></td>
<td align="center"><span class="math inline">\(n_{21}\)</span></td>
<td align="center"><span class="math inline">\(n_{22}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{2j}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{2s}\)</span></td>
<td align="center"><span class="math inline">\(n_{2.}\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(A_{i}\)</span></td>
<td align="center"><span class="math inline">\(n_{i1}\)</span></td>
<td align="center"><span class="math inline">\(n_{i2}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{ij}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{is}\)</span></td>
<td align="center"><span class="math inline">\(n_{i.}\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
<td align="center"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(A_{r}\)</span></td>
<td align="center"><span class="math inline">\(n_{r1}\)</span></td>
<td align="center"><span class="math inline">\(n_{r2}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{rj}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{rs}\)</span></td>
<td align="center"><span class="math inline">\(n_{r.}\)</span></td>
</tr>
<tr class="odd">
<td align="left"><strong>Totais em <span class="math inline">\(Y\)</span></strong></td>
<td align="center"><span class="math inline">\(n_{.1}\)</span></td>
<td align="center"><span class="math inline">\(n_{.2}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{.j}\)</span></td>
<td align="center"><span class="math inline">\(\cdots\)</span></td>
<td align="center"><span class="math inline">\(n_{rs}\)</span></td>
<td align="center"><span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<p>Sob a hipótese de não associação entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> teremos que:</p>
<p><span class="math inline">\(\frac{n_{i1}}{n_{.1}} = \frac{n_{i2}}{n_{.2}} = \cdots = \frac{n_{is}}{n_{.s}} = \frac{n_{i.}}{n}\)</span></p>
<p>e assim:</p>
<p><span class="math inline">\(\frac{n_{ij}}{n_{.j}} = \frac{n_{i.}}{n}\)</span></p>
<p>Deste modo:</p>
<p><span class="math inline">\(n_{ij}^{e} = \frac{n_{i.} \times n_{.j}}{n}\)</span></p>
<hr />
<p>A notação <span class="math inline">\(n_{ij}^{e}\)</span> está sendo utilizada para denotar que a expressão acima determina a contagem de cada célula da tabela <strong>sob a hipótese de não associação</strong> e portanto, se refere ao <strong>valor esperado</strong> de <span class="math inline">\(n_{ij}\)</span>.</p>
<hr />
<p>Tendo definido os valores esperados em uma tabela de contingência de <span class="math inline">\(r \times s\)</span>, o <span class="math inline">\(\chi^2\)</span> é dado por:</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{r}\sum_{j=1}^{s}\frac{(n_{ij} - n_{ij}^{e})^2}{n_{ij}^{e}}\]</span></p>
<p><strong>Retornando ao exemplo das entrevistas</strong></p>
<p>A tabela de contingência contendo os dados <strong>observados</strong> do início do capítulo pode ser escrita como:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Não-Residente</th>
<th>Residente</th>
<th>Total Opinião</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A favor</td>
<td>81</td>
<td>63</td>
<td>144</td>
</tr>
<tr class="even">
<td>Contra</td>
<td>36</td>
<td>20</td>
<td>56</td>
</tr>
<tr class="odd">
<td>Total Moradia</td>
<td>117</td>
<td>83</td>
<td>200</td>
</tr>
</tbody>
</table>
<p>Os Valores esperados na linha <span class="math inline">\(i\)</span> e coluna <span class="math inline">\(j\)</span> são:</p>
<ul>
<li>Linha <span class="math inline">\(1\)</span> - Coluna <span class="math inline">\(1\)</span> (<code>Não-Residente</code> - <code>A favor</code>):</li>
</ul>
<p><span class="math inline">\(n_{ii}^{e} = \frac{n_{1.} \times n_{.1}}{n} = \frac{144 \times 117}{200} = 84.24\)</span></p>
<ul>
<li>Linha <span class="math inline">\(1\)</span> - Coluna <span class="math inline">\(2\)</span> (<code>Residente</code> - <code>A favor</code>):</li>
</ul>
<p><span class="math inline">\(n_{ii}^{e} = \frac{n_{1.} \times n_{.2}}{n} = \frac{144 \times 83}{200} = 59.76\)</span></p>
<ul>
<li>Linha <span class="math inline">\(2\)</span> - Coluna <span class="math inline">\(1\)</span> (<code>Não-Residente</code> - <code>Contra</code>):</li>
</ul>
<p><span class="math inline">\(n_{ii}^{e} = \frac{n_{2.} \times n_{.1}}{n} = \frac{56 \times 117}{200} = 32.76\)</span></p>
<ul>
<li>Linha <span class="math inline">\(2\)</span> - Coluna <span class="math inline">\(2\)</span> (<code>Residente</code> - <code>Contra</code>):</li>
</ul>
<p><span class="math inline">\(n_{ii}^{e} = \frac{n_{2.} \times n_{.2}}{n} = \frac{56 \times 83}{200} = 23.24\)</span></p>
<p>De modo que a tabela com os valores <strong>esperados</strong> será:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Não-Residente</th>
<th>Residente</th>
<th>Total Opinião</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A favor</td>
<td>84.24</td>
<td>59.76</td>
<td>144</td>
</tr>
<tr class="even">
<td>Contra</td>
<td>32.76</td>
<td>23.24</td>
<td>56</td>
</tr>
<tr class="odd">
<td>Total Moradia</td>
<td>117</td>
<td>83</td>
<td>200</td>
</tr>
</tbody>
</table>
<p>Finalmente, o valor <span class="math inline">\(\chi^2\)</span> pode ser obtido por:</p>
<p><span class="math inline">\(\chi^2 = \frac{(81 - 84.24)^2}{84.24} + \frac{(36 - 32.76)^2}{84.24} + \frac{(63 - 59.76)^2}{84.24} + \frac{(20 - 23.24)^2}{84.24} = 1.072\)</span></p>
</div>
<div id="valores-de-chi2-quando-existe-associação" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Valores de <span class="math inline">\(\chi^2\)</span> quando existe associação</h2>
<p>O valor de <span class="math inline">\(\chi^2\)</span> será zero somente se os valores observados forem <strong>exatamente</strong> igauis aos valores esperados. Pequenas discrepâncias irão gerar valores de <span class="math inline">\(\chi^2\)</span> acima de zero. Os valores se tornarão mais altos à medida que aumentam as diferenças entre <span class="math inline">\(n_{ij}\)</span> e <span class="math inline">\(n_{ij}^e\)</span>.</p>
<p>Abaixo estão diferentes exemplos em que existe associação entre <code>Opinião</code> e <code>Moradia</code>. Compare os valores e os gráficos abaixo os que fizemos no exemplo do capítulo e veja que todos os valores de <span class="math inline">\(\chi^2\)</span> são mais elevados.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-196-1.png" width="672" style="display: block; margin: auto auto auto 0;" /></p>
<ul>
<li>Tente aplicar a fórmula do <span class="math inline">\(\chi^2\)</span> para chegar aos resultados apresentados em cada exemplo.</li>
</ul>
</div>
<div id="variações-do-índice-de-chi2" class="section level2" number="9.6">
<h2><span class="header-section-number">9.6</span> Variações do índice de <span class="math inline">\(\chi^2\)</span></h2>
<p>O valor de <span class="math inline">\(\chi^2\)</span> aumenta com o tamanho da amostra, o que torna difícil comparações entre diferentes estudos. Para corrigir este efeito existe o <strong>coeficiente de contigência de Pearson (<span class="math inline">\(C\)</span>)</strong> que é baseado no resultado de <span class="math inline">\(\chi^2\)</span></p>
<p><span class="math display">\[C = \sqrt{\frac{\chi^2}{\chi^2 + n}}\]</span></p>
<p>em que <span class="math inline">\(n\)</span> é o tamanho da amostra. O valor máximo de <span class="math inline">\(C\)</span> depende do número de linhas (<span class="math inline">\(r\)</span>) e de colunas (<span class="math inline">\(s\)</span>) na tabela de contingêcia, deste modo podemos ainda definir um outro coeficiente que varia entre <span class="math inline">\(0\)</span> e <span class="math inline">\(1\)</span>:</p>
<p><span class="math display">\[T = \sqrt{\frac{\frac{\chi^2}{n}}{(r-1) \times (s-1)}}\]</span>
O valor <span class="math inline">\(T = 0\)</span> ocorre quando não há associação (<span class="math inline">\(\chi^2 = 0\)</span>) e o valor máximo de <span class="math inline">\(T = 1\)</span> só será atingido quando houver associação e <span class="math inline">\(r = s\)</span></p>
<p>Todos estes índices aumentam conforme aumenta o grau de associação entre as variáveis. Entretanto, não dissemos <strong>em que ponto</strong> passamos a aceitar a hipótese de associação as variáveis <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>. Iremos tratar deste assunto na seção sobre estatística inferencial. Ao tratarmos deste ponto é importante termos claro o que siginifica uma associação (ou dependêcia) entre duas variáveis qualitativas e como o índice de <span class="math inline">\(\chi^2\)</span> mede esta associação.</p>
</div>
<div id="obtendo-o-índice-de-chi2-de-uma-tabela-de-dados" class="section level2" number="9.7">
<h2><span class="header-section-number">9.7</span> Obtendo o índice de <span class="math inline">\(\chi^2\)</span> de uma tabela de dados</h2>
<p>A função para o cálculo do <span class="math inline">\(\chi^2\)</span> no R é <code>chisq.test</code> e pode ser utilizada a partir da tabela de contigência gerada pela função <code>table</code>:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="biquali.html#cb116-1" aria-hidden="true" tabindex="-1"></a>tcont <span class="ot">=</span> <span class="fu">table</span>(mun<span class="sc">$</span>Opiniao, mun<span class="sc">$</span>Moradia)</span>
<span id="cb116-2"><a href="biquali.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tcont)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  tcont
## X-squared = 0.76697, df = 1, p-value = 0.3812</code></pre>
<p>O resultado mostra o o valor de <span class="math inline">\(\chi^2\)</span> calculado (<code>X-squared</code>) e outras duas quantias denominadas de <strong>graus de liberdade</strong> (<code>df</code>) e <strong>valor de p</strong> (<code>p-value</code>), sobre as quais falaremos na seção sobre Inferência estatística (Capítulos <a href="popamostra.html#popamostra">12</a> a <a href="testet.html#testet">18</a>).</p>
<p>Note que o resultado é diferente do que obtivemos neste capítulo. Isto ocorre pois, por padrão, a função utiliza a <strong>correção de Yates</strong> (<a target="_blank" href="https://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity">veja aqui</a>), em que <span class="math inline">\(\chi_{Yates}^{2}\)</span> é calculado por:</p>
<p><span class="math display">\[\chi_{Yates}^{2} = \sum_{i=1}^{r}\sum_{j=1}^{s}\frac{(|n_{ij} - n_{ij}^{e}| - 0,5)^2}{n_{ij}^{e}}\]</span></p>
<p>O termo <span class="math inline">\(|n_{ij} - n_{ij}^{e}|\)</span> se refere ao módulo da distância entre os valores observados e calculados.</p>
<p>Esta correção será abordada ao falarmos de <strong>testes de hipóteses para variáveis categóricas</strong>. Por hora, se quisermos obter exatamente os resultados descritos no exemplo deste capítulo, basta fazermos:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="biquali.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tcont, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tcont
## X-squared = 1.0724, df = 1, p-value = 0.3004</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="escorez.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="biquant.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["probest-cambientais.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
