<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais</title>
  <meta name="description" content="Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais" />
  
  <meta name="twitter:description" content="Capítulo 10 Introdução ao Teste de Hipóteses | Estatística nas Ciências Ambientais" />
  

<meta name="author" content="Fabio Cop Ferreira" />
<meta name="author" content="fabiocopf@gmail.com; fcferreira@unifesp.br" />
<meta name="author" content="Instituto do Mar, Universidade Federal de São Paulo" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="inferenc.html"/>
<link rel="next" href="testet.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.19/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Estatística nas Ciências Ambientais</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Apresentação</a></li>
<li class="part"><span><b>I Estatística descritiva</b></span></li>
<li class="chapter" data-level="1" data-path="estrdados.html"><a href="estrdados.html"><i class="fa fa-check"></i><b>1</b> Estrutura e tipo de dados</a>
<ul>
<li class="chapter" data-level="1.1" data-path="estrdados.html"><a href="estrdados.html#unidades-amostrais-e-descritores"><i class="fa fa-check"></i><b>1.1</b> Unidades amostrais e descritores</a></li>
<li class="chapter" data-level="1.2" data-path="estrdados.html"><a href="estrdados.html#tipos-de-dados"><i class="fa fa-check"></i><b>1.2</b> Tipos de dados</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="estrdados.html"><a href="estrdados.html#variáveis-qualitativas"><i class="fa fa-check"></i><b>1.2.1</b> Variáveis qualitativas</a></li>
<li class="chapter" data-level="1.2.2" data-path="estrdados.html"><a href="estrdados.html#variáveis-quantitativas"><i class="fa fa-check"></i><b>1.2.2</b> Variáveis quantitativas</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="estrdados.html"><a href="estrdados.html#níveis-de-mensuração"><i class="fa fa-check"></i><b>1.3</b> Níveis de mensuração</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="procdados.html"><a href="procdados.html"><i class="fa fa-check"></i><b>2</b> Processamento de dados</a>
<ul>
<li class="chapter" data-level="2.1" data-path="procdados.html"><a href="procdados.html#criando-seu-projeto-de-trabalho-no-rstudio"><i class="fa fa-check"></i><b>2.1</b> Criando seu projeto de trabalho no RStudio</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="procdados.html"><a href="procdados.html#iniciando-o-projeto-intro_estatistica"><i class="fa fa-check"></i><b>2.1.1</b> Iniciando o projeto <code>Intro_estatistica</code></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="procdados.html"><a href="procdados.html#inserindo-uma-base-de-dados-no-diretório-do-projeto"><i class="fa fa-check"></i><b>2.2</b> Inserindo uma base de dados no diretório do projeto</a></li>
<li class="chapter" data-level="2.3" data-path="procdados.html"><a href="procdados.html#preparando-o-ambiente-de-trabalho"><i class="fa fa-check"></i><b>2.3</b> Preparando o ambiente de trabalho</a></li>
<li class="chapter" data-level="2.4" data-path="procdados.html"><a href="procdados.html#carregando-os-pacotes"><i class="fa fa-check"></i><b>2.4</b> Carregando os pacotes</a></li>
<li class="chapter" data-level="2.5" data-path="procdados.html"><a href="procdados.html#importanto-a-base-de-dados"><i class="fa fa-check"></i><b>2.5</b> Importanto a base de dados</a></li>
<li class="chapter" data-level="2.6" data-path="procdados.html"><a href="procdados.html#verificando-a-base-de-dados"><i class="fa fa-check"></i><b>2.6</b> Verificando a base de dados</a></li>
<li class="chapter" data-level="2.7" data-path="procdados.html"><a href="procdados.html#visualizando-a-base-de-dados"><i class="fa fa-check"></i><b>2.7</b> Visualizando a base de dados</a></li>
<li class="chapter" data-level="2.8" data-path="procdados.html"><a href="procdados.html#selecionando-colunas-da-tabela"><i class="fa fa-check"></i><b>2.8</b> Selecionando colunas da tabela</a></li>
<li class="chapter" data-level="2.9" data-path="procdados.html"><a href="procdados.html#filtrando-linhas-da-tabela"><i class="fa fa-check"></i><b>2.9</b> Filtrando linhas da tabela</a></li>
<li class="chapter" data-level="2.10" data-path="procdados.html"><a href="procdados.html#adicionando-ou-modificando-colunas"><i class="fa fa-check"></i><b>2.10</b> Adicionando ou modificando colunas</a></li>
<li class="chapter" data-level="2.11" data-path="procdados.html"><a href="procdados.html#renomeando-colunas"><i class="fa fa-check"></i><b>2.11</b> Renomeando colunas</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="resqualit.html"><a href="resqualit.html"><i class="fa fa-check"></i><b>3</b> Descrevendo variáveis qualitativas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="resqualit.html"><a href="resqualit.html#representação-em-tabelas-de-frequência"><i class="fa fa-check"></i><b>3.1</b> Representação em tabelas de frequência</a></li>
<li class="chapter" data-level="3.2" data-path="resqualit.html"><a href="resqualit.html#reordenando-categorias"><i class="fa fa-check"></i><b>3.2</b> Reordenando categorias</a></li>
<li class="chapter" data-level="3.3" data-path="resqualit.html"><a href="resqualit.html#representação-gráfica"><i class="fa fa-check"></i><b>3.3</b> Representação gráfica</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="descrit.html"><a href="descrit.html"><i class="fa fa-check"></i><b>4</b> Apresentando informações em tabelas e gráficos</a>
<ul>
<li class="chapter" data-level="4.1" data-path="descrit.html"><a href="descrit.html#tipos-de-dados-1"><i class="fa fa-check"></i><b>4.1</b> Tipos de dados</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="descrit.html"><a href="descrit.html#dados-quantitativos-e-qualitativos"><i class="fa fa-check"></i><b>4.1.1</b> Dados quantitativos e qualitativos</a></li>
<li class="chapter" data-level="4.1.2" data-path="descrit.html"><a href="descrit.html#níveis-de-mensuração-1"><i class="fa fa-check"></i><b>4.1.2</b> Níveis de mensuração</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="descrit.html"><a href="descrit.html#tabelas-resumo"><i class="fa fa-check"></i><b>4.2</b> Tabelas resumo</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="descrit.html"><a href="descrit.html#combinando-duas-variáveis"><i class="fa fa-check"></i><b>4.2.1</b> Combinando duas variáveis</a></li>
<li class="chapter" data-level="4.2.2" data-path="descrit.html"><a href="descrit.html#tabelas-de-frequência-para-variáveis-quantitativas"><i class="fa fa-check"></i><b>4.2.2</b> Tabelas de frequência para variáveis quantitativas</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="descrit.html"><a href="descrit.html#visualização-gráfica"><i class="fa fa-check"></i><b>4.3</b> Visualização gráfica</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="descrit.html"><a href="descrit.html#gráficos-de-barras"><i class="fa fa-check"></i><b>4.3.1</b> Gráficos de barras</a></li>
<li class="chapter" data-level="4.3.2" data-path="descrit.html"><a href="descrit.html#histogramas"><i class="fa fa-check"></i><b>4.3.2</b> Histogramas</a></li>
<li class="chapter" data-level="4.3.3" data-path="descrit.html"><a href="descrit.html#gráficos-de-linhas"><i class="fa fa-check"></i><b>4.3.3</b> Gráficos de linhas</a></li>
<li class="chapter" data-level="4.3.4" data-path="descrit.html"><a href="descrit.html#gráficos-de-dispersão"><i class="fa fa-check"></i><b>4.3.4</b> Gráficos de dispersão</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="posicao.html"><a href="posicao.html"><i class="fa fa-check"></i><b>5</b> Descrevendo populações e amostras</a>
<ul>
<li class="chapter" data-level="5.1" data-path="posicao.html"><a href="posicao.html#população-amostra-e-unidade-amostral"><i class="fa fa-check"></i><b>5.1</b> População, amostra e unidade amostral</a></li>
<li class="chapter" data-level="5.2" data-path="posicao.html"><a href="posicao.html#distribuições-de-frequência"><i class="fa fa-check"></i><b>5.2</b> Distribuições de frequência</a></li>
<li class="chapter" data-level="5.3" data-path="posicao.html"><a href="posicao.html#parâmetros-e-estimadores"><i class="fa fa-check"></i><b>5.3</b> Parâmetros e estimadores</a></li>
<li class="chapter" data-level="5.4" data-path="posicao.html"><a href="posicao.html#amostragem-e-inferência"><i class="fa fa-check"></i><b>5.4</b> Amostragem e inferência</a></li>
<li class="chapter" data-level="5.5" data-path="posicao.html"><a href="posicao.html#medidas-de-tendência-central"><i class="fa fa-check"></i><b>5.5</b> Medidas de tendência central</a></li>
<li class="chapter" data-level="5.6" data-path="posicao.html"><a href="posicao.html#medidas-de-variação"><i class="fa fa-check"></i><b>5.6</b> Medidas de variação</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="posicao.html"><a href="posicao.html#exempificando-os-cálculos"><i class="fa fa-check"></i><b>5.6.1</b> Exempificando os cálculos</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="posicao.html"><a href="posicao.html#medidas-de-posição"><i class="fa fa-check"></i><b>5.7</b> Medidas de posição</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="posicao.html"><a href="posicao.html#quartis"><i class="fa fa-check"></i><b>5.7.1</b> Quartis</a></li>
<li class="chapter" data-level="5.7.2" data-path="posicao.html"><a href="posicao.html#índice-z"><i class="fa fa-check"></i><b>5.7.2</b> Índice Z</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="posicao.html"><a href="posicao.html#volume-dos-reservatórios-da-grande-são-paulo-visualizando-medidas-de-posição-e-variação"><i class="fa fa-check"></i><b>5.8</b> Volume dos reservatórios da Grande São Paulo: visualizando medidas de posição e variação</a></li>
</ul></li>
<li class="part"><span><b>II Amostragem e Inferência Estatística</b></span></li>
<li class="chapter" data-level="6" data-path="amostrmedias.html"><a href="amostrmedias.html"><i class="fa fa-check"></i><b>6</b> Amostrando uma População Estatística</a>
<ul>
<li class="chapter" data-level="6.1" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-simples"><i class="fa fa-check"></i><b>6.1</b> Amostragem aleatória simples</a></li>
<li class="chapter" data-level="6.2" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-aleatória-estratificada"><i class="fa fa-check"></i><b>6.2</b> Amostragem aleatória estratificada</a></li>
<li class="chapter" data-level="6.3" data-path="amostrmedias.html"><a href="amostrmedias.html#amostragem-sistemática"><i class="fa fa-check"></i><b>6.3</b> Amostragem sistemática</a></li>
<li class="chapter" data-level="6.4" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral-acurácia-e-precisão"><i class="fa fa-check"></i><b>6.4</b> Erro amostral, acurácia e precisão</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-amostral"><i class="fa fa-check"></i><b>6.4.1</b> Erro amostral</a></li>
<li class="chapter" data-level="6.4.2" data-path="amostrmedias.html"><a href="amostrmedias.html#acurácia"><i class="fa fa-check"></i><b>6.4.2</b> Acurácia</a></li>
<li class="chapter" data-level="6.4.3" data-path="amostrmedias.html"><a href="amostrmedias.html#precisão"><i class="fa fa-check"></i><b>6.4.3</b> Precisão</a></li>
<li class="chapter" data-level="6.4.4" data-path="amostrmedias.html"><a href="amostrmedias.html#erro-padrão-da-média"><i class="fa fa-check"></i><b>6.4.4</b> Erro padrão da média</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="normdist.html"><a href="normdist.html"><i class="fa fa-check"></i><b>7</b> Alguns fenômenos têm distribuição normal</a>
<ul>
<li class="chapter" data-level="7.1" data-path="normdist.html"><a href="normdist.html#o-modelo-normal-de-probabilidades"><i class="fa fa-check"></i><b>7.1</b> O modelo normal de probabilidades</a></li>
<li class="chapter" data-level="7.2" data-path="normdist.html"><a href="normdist.html#entendendo-a-função-normal-de-densidade-de-probabilidade"><i class="fa fa-check"></i><b>7.2</b> Entendendo a função normal de densidade de probabilidade</a></li>
<li class="chapter" data-level="7.3" data-path="normdist.html"><a href="normdist.html#fazendo-predições-com-a-função-normal-de-densidade"><i class="fa fa-check"></i><b>7.3</b> Fazendo predições com a função normal de densidade</a></li>
<li class="chapter" data-level="7.4" data-path="normdist.html"><a href="normdist.html#a-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>7.4</b> A distribuição normal padronizada</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="normdist.html"><a href="normdist.html#probabilidades-em-uma-distribuição-normal-padronizada"><i class="fa fa-check"></i><b>7.4.1</b> Probabilidades em uma distribuição normal padronizada</a></li>
<li class="chapter" data-level="7.4.2" data-path="normdist.html"><a href="normdist.html#tabela-z"><i class="fa fa-check"></i><b>7.4.2</b> Tabela <span class="math inline">\(Z\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="normdist.html"><a href="normdist.html#exercícios-resolvidos"><i class="fa fa-check"></i><b>7.5</b> Exercícios resolvidos</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="normdist.html"><a href="normdist.html#distribuição-de-comprimento"><i class="fa fa-check"></i><b>7.5.1</b> Distribuição de comprimento</a></li>
<li class="chapter" data-level="7.5.2" data-path="normdist.html"><a href="normdist.html#intervalos-em-uma-distribuição-normal"><i class="fa fa-check"></i><b>7.5.2</b> Intervalos em uma distribuição normal</a></li>
<li class="chapter" data-level="7.5.3" data-path="normdist.html"><a href="normdist.html#quantos-desvios-padrões"><i class="fa fa-check"></i><b>7.5.3</b> Quantos desvios padrões?</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="normdist.html"><a href="normdist.html#exercícios-propostos"><i class="fa fa-check"></i><b>7.6</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tcl.html"><a href="tcl.html"><i class="fa fa-check"></i><b>8</b> Distribuição das médias amostrais</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tcl.html"><a href="tcl.html#teorema-central-do-limite"><i class="fa fa-check"></i><b>8.1</b> Teorema Central do Limite</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="tcl.html"><a href="tcl.html#probabilidades-na-amostra-original-e-na-distribuição-de-médias"><i class="fa fa-check"></i><b>8.1.1</b> Probabilidades na amostra original e na distribuição de médias</a></li>
<li class="chapter" data-level="8.1.2" data-path="tcl.html"><a href="tcl.html#distribuição-não-normais"><i class="fa fa-check"></i><b>8.1.2</b> Distribuição não-normais</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tcl.html"><a href="tcl.html#exercícios-resolvidos-1"><i class="fa fa-check"></i><b>8.2</b> Exercícios resolvidos:</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tcl.html"><a href="tcl.html#tamanho-médio-de-robalos-no-mercado-de-peixes"><i class="fa fa-check"></i><b>8.2.1</b> Tamanho médio de robalos no mercado de peixes</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tcl.html"><a href="tcl.html#exercícios-propostos-1"><i class="fa fa-check"></i><b>8.3</b> Exercícios propostos</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="inferenc.html"><a href="inferenc.html"><i class="fa fa-check"></i><b>9</b> Inferindo sobre uma População Estatística</a>
<ul>
<li class="chapter" data-level="9.1" data-path="inferenc.html"><a href="inferenc.html#estimação-pontual-e-estimação-intervalar"><i class="fa fa-check"></i><b>9.1</b> Estimação pontual e estimação intervalar</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="inferenc.html"><a href="inferenc.html#intervalo-de-confiança"><i class="fa fa-check"></i><b>9.1.1</b> Intervalo de confiança</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="inferenc.html"><a href="inferenc.html#introdução-à-suficiência-amostral"><i class="fa fa-check"></i><b>9.2</b> Introdução à suficiência amostral</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="inferenc.html"><a href="inferenc.html#nível-de-acurácia-desejado-margem-de-erro-e-nível-de-confiança-na-estimativa"><i class="fa fa-check"></i><b>9.2.1</b> Nível de acurácia desejado (margem de erro) e nível de confiança na estimativa</a></li>
<li class="chapter" data-level="9.2.2" data-path="inferenc.html"><a href="inferenc.html#determinando-o-tamanho-de-uma-amostra"><i class="fa fa-check"></i><b>9.2.2</b> Determinando o tamanho de uma amostra</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="th.html"><a href="th.html"><i class="fa fa-check"></i><b>10</b> Introdução ao Teste de Hipóteses</a>
<ul>
<li class="chapter" data-level="10.1" data-path="th.html"><a href="th.html#probabilidade-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>10.1</b> Probabilidade e teste de hipóteses</a></li>
<li class="chapter" data-level="10.2" data-path="th.html"><a href="th.html#exemplificando-um-teste-de-hipóteses-o-teste-z"><i class="fa fa-check"></i><b>10.2</b> Exemplificando um teste de hipóteses: o teste z</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="th.html"><a href="th.html#tomada-de-decisão-sobre-h_0-nível-de-significância"><i class="fa fa-check"></i><b>10.2.1</b> Tomada de decisão sobre <span class="math inline">\(H_0\)</span>: nível de significância</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="th.html"><a href="th.html#erros-de-decisão-em-um-teste-de-hipóteses"><i class="fa fa-check"></i><b>10.3</b> Erros de decisão em um teste de hipóteses</a></li>
<li class="chapter" data-level="10.4" data-path="th.html"><a href="th.html#exemplo-de-um-teste-de-hipótese-teste-t-para-uma-média-populacional"><i class="fa fa-check"></i><b>10.4</b> Exemplo de um teste de hipótese: teste t para uma média populacional</a></li>
<li class="chapter" data-level="10.5" data-path="th.html"><a href="th.html#graus-de-liberdade"><i class="fa fa-check"></i><b>10.5</b> Graus de liberdade</a></li>
<li class="chapter" data-level="10.6" data-path="th.html"><a href="th.html#probabilidades-no-teste-t-de-student-a-tabela-t"><i class="fa fa-check"></i><b>10.6</b> Probabilidades no teste <span class="math inline">\(t\)</span> de Student: a tabela <span class="math inline">\(t\)</span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="testet.html"><a href="testet.html"><i class="fa fa-check"></i><b>11</b> Teste t para duas amostras</a>
<ul>
<li class="chapter" data-level="11.1" data-path="testet.html"><a href="testet.html#teste-t-para-comparação-de-duas-médias-independentes"><i class="fa fa-check"></i><b>11.1</b> Teste t para comparação de duas médias independentes</a></li>
</ul></li>
<li class="part"><span><b>III Modelos Lineares Clássicos</b></span></li>
<li class="chapter" data-level="12" data-path="regressao.html"><a href="regressao.html"><i class="fa fa-check"></i><b>12</b> Regressão linear e correlação</a>
<ul>
<li class="chapter" data-level="12.1" data-path="regressao.html"><a href="regressao.html#modelo-geral-de-regressão"><i class="fa fa-check"></i><b>12.1</b> Modelo geral de regressão</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="regressao.html"><a href="regressao.html#porção-determinística"><i class="fa fa-check"></i><b>12.1.1</b> Porção determinística</a></li>
<li class="chapter" data-level="12.1.2" data-path="regressao.html"><a href="regressao.html#porção-estocástica"><i class="fa fa-check"></i><b>12.1.2</b> Porção estocástica</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="regressao.html"><a href="regressao.html#ajuste-dos-dados-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>12.2</b> Ajuste dos dados ao modelo de regressão</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="regressao.html"><a href="regressao.html#método-dos-mínimos-quadrados"><i class="fa fa-check"></i><b>12.2.1</b> Método dos mínimos quadrados</a></li>
<li class="chapter" data-level="12.2.2" data-path="regressao.html"><a href="regressao.html#variâncias-covariâncias-e-coeficientes-da-regressão"><i class="fa fa-check"></i><b>12.2.2</b> Variâncias, covariâncias e coeficientes da regressão</a></li>
<li class="chapter" data-level="12.2.3" data-path="regressao.html"><a href="regressao.html#exemplo-de-ajuste-ao-modelo-de-regressão"><i class="fa fa-check"></i><b>12.2.3</b> Exemplo de ajuste ao modelo de regressão</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="regressao.html"><a href="regressao.html#testes-de-hipóteses-na-regressão-linear-simples"><i class="fa fa-check"></i><b>12.3</b> Testes de hipóteses na regressão linear simples</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="regressao.html"><a href="regressao.html#teste-sobre-beta_1"><i class="fa fa-check"></i><b>12.3.1</b> Teste sobre <span class="math inline">\(\beta_1\)</span></a></li>
<li class="chapter" data-level="12.3.2" data-path="regressao.html"><a href="regressao.html#análise-de-variância-da-regressão"><i class="fa fa-check"></i><b>12.3.2</b> Análise de variância da regressão</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="regressao.html"><a href="regressao.html#coeficiente-de-determinação-r2"><i class="fa fa-check"></i><b>12.4</b> Coeficiente de determinação <span class="math inline">\(r^2\)</span></a></li>
<li class="chapter" data-level="12.5" data-path="regressao.html"><a href="regressao.html#intervalo-de-confiança-de-y"><i class="fa fa-check"></i><b>12.5</b> Intervalo de confiança de <span class="math inline">\(Y\)</span></a></li>
<li class="chapter" data-level="12.6" data-path="regressao.html"><a href="regressao.html#pressupostos-da-regressão-linear-simples"><i class="fa fa-check"></i><b>12.6</b> Pressupostos da regressão linear simples</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="regressao.html"><a href="regressao.html#relação-funcional-linear"><i class="fa fa-check"></i><b>12.6.1</b> Relação funcional linear</a></li>
<li class="chapter" data-level="12.6.2" data-path="regressao.html"><a href="regressao.html#independência"><i class="fa fa-check"></i><b>12.6.2</b> Independência</a></li>
<li class="chapter" data-level="12.6.3" data-path="regressao.html"><a href="regressao.html#variável-x-é-medida-sem-erros"><i class="fa fa-check"></i><b>12.6.3</b> Variável <span class="math inline">\(X\)</span> é medida sem erros</a></li>
<li class="chapter" data-level="12.6.4" data-path="regressao.html"><a href="regressao.html#distribuição-normal-dos-resíduos"><i class="fa fa-check"></i><b>12.6.4</b> Distribuição normal dos resíduos</a></li>
<li class="chapter" data-level="12.6.5" data-path="regressao.html"><a href="regressao.html#variância-residual-constante"><i class="fa fa-check"></i><b>12.6.5</b> Variância residual constante</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="regressao.html"><a href="regressao.html#diagnósticos-da-regressão"><i class="fa fa-check"></i><b>12.7</b> Diagnósticos da regressão</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="regressao.html"><a href="regressao.html#gráfico-de-resíduos"><i class="fa fa-check"></i><b>12.7.1</b> Gráfico de resíduos</a></li>
<li class="chapter" data-level="12.7.2" data-path="regressao.html"><a href="regressao.html#histograma-dos-resíduos"><i class="fa fa-check"></i><b>12.7.2</b> Histograma dos resíduos</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="regressao.html"><a href="regressao.html#coeficiente-de-correlação-de-pearson-r"><i class="fa fa-check"></i><b>12.8</b> Coeficiente de correlação de Pearson <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="12.8.1" data-path="regressao.html"><a href="regressao.html#teste-de-hipóteses-para-r"><i class="fa fa-check"></i><b>12.8.1</b> Teste de hipóteses para <span class="math inline">\(r\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="regresmultipla.html"><a href="regresmultipla.html"><i class="fa fa-check"></i><b>13</b> Regressão linear múltipla</a></li>
<li class="chapter" data-level="14" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>14</b> Análise de variância de um fator</a>
<ul>
<li class="chapter" data-level="14.1" data-path="anova.html"><a href="anova.html#o-modelo-da-anova"><i class="fa fa-check"></i><b>14.1</b> O modelo da ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anovafatorial.html"><a href="anovafatorial.html"><i class="fa fa-check"></i><b>15</b> Análise de variância fatorial</a></li>
<li class="chapter" data-level="16" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>16</b> Análise de covariância</a></li>
<li class="chapter" data-level="17" data-path="repanova.html"><a href="repanova.html"><i class="fa fa-check"></i><b>17</b> Análise de variância de medidas repetidas</a></li>
<li class="part"><span><b>IV Fundamentos de probabilidade</b></span></li>
<li class="chapter" data-level="18" data-path="espacoamostral.html"><a href="espacoamostral.html"><i class="fa fa-check"></i><b>18</b> O espaço de possibilidades de um experimento</a>
<ul>
<li class="chapter" data-level="18.1" data-path="espacoamostral.html"><a href="espacoamostral.html#probabilidades-de-um-evento"><i class="fa fa-check"></i><b>18.1</b> Probabilidades de um evento</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="espacoamostral.html"><a href="espacoamostral.html#estimando-as-probabilidades-de-um-evento-por-amostragem"><i class="fa fa-check"></i><b>18.1.1</b> Estimando as probabilidades de um evento por amostragem</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="probregras.html"><a href="probregras.html"><i class="fa fa-check"></i><b>19</b> Combinando as probabilidades de eventos</a>
<ul>
<li class="chapter" data-level="19.1" data-path="probregras.html"><a href="probregras.html#eventos-complexos"><i class="fa fa-check"></i><b>19.1</b> Eventos complexos</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-venn"><i class="fa fa-check"></i><b>19.1.1</b> Representação de eventos: diagrama de Venn</a></li>
<li class="chapter" data-level="19.1.2" data-path="probregras.html"><a href="probregras.html#probabilidade-de-eventos-simples"><i class="fa fa-check"></i><b>19.1.2</b> Probabilidade de eventos simples</a></li>
<li class="chapter" data-level="19.1.3" data-path="probregras.html"><a href="probregras.html#probabilidade-da-união-de-eventos"><i class="fa fa-check"></i><b>19.1.3</b> Probabilidade da união de eventos</a></li>
<li class="chapter" data-level="19.1.4" data-path="probregras.html"><a href="probregras.html#representação-de-eventos-diagrama-de-árvore"><i class="fa fa-check"></i><b>19.1.4</b> Representação de eventos: diagrama de árvore</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="probcondind.html"><a href="probcondind.html"><i class="fa fa-check"></i><b>20</b> Probabilidade condicional e independência</a>
<ul>
<li class="chapter" data-level="20.1" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes"><i class="fa fa-check"></i><b>20.1</b> Eventos independentes</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="probcondind.html"><a href="probcondind.html#um-exemplo-de-eventos-independentes"><i class="fa fa-check"></i><b>20.1.1</b> Um exemplo de eventos independentes</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="probcondind.html"><a href="probcondind.html#eventos-independentes-vs-mutuamente-exclusivos"><i class="fa fa-check"></i><b>20.2</b> Eventos independentes <em>vs</em> mutuamente exclusivos</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="tbayes.html"><a href="tbayes.html"><i class="fa fa-check"></i><b>21</b> Teorema de Bayes: atualizando o conhecimento</a>
<ul>
<li class="chapter" data-level="21.1" data-path="tbayes.html"><a href="tbayes.html#teorema-de-bayes"><i class="fa fa-check"></i><b>21.1</b> Teorema de Bayes</a></li>
<li class="chapter" data-level="21.2" data-path="tbayes.html"><a href="tbayes.html#teorema-da-probabilidade-total"><i class="fa fa-check"></i><b>21.2</b> Teorema da probabilidade total</a></li>
<li class="chapter" data-level="21.3" data-path="tbayes.html"><a href="tbayes.html#o-problema-da-detecção-de-espécies"><i class="fa fa-check"></i><b>21.3</b> O problema da detecção de espécies</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="tbayes.html"><a href="tbayes.html#razão-de-verossimilhança-inferência-bayesiana-e-teste-de-hipóteses"><i class="fa fa-check"></i><b>21.3.1</b> Razão de verossimilhança, inferência bayesiana e teste de hipóteses</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Modelos Probabilísticos, verossimilhança e inferência bayesiana</b></span></li>
<li class="chapter" data-level="22" data-path="va.html"><a href="va.html"><i class="fa fa-check"></i><b>22</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos discretos</em></a>
<ul>
<li class="chapter" data-level="22.1" data-path="va.html"><a href="va.html#experimento-1-sucessos-e-fracassos"><i class="fa fa-check"></i><b>22.1</b> <em>Experimento 1</em>: Sucessos e fracassos</a>
<ul>
<li><a href="va.html#a-distribuição-de-probabilidade-de-y">A distribuição de probabilidade de <span class="math inline">\(Y\)</span></a></li>
<li><a href="va.html#uma-expressão-geral-para-py-y">Uma expressão geral para <span class="math inline">\(P(Y = y)\)</span></a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#função-de-distribuição-acumulada"><i class="fa fa-check"></i>Função de distribuição acumulada</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#estruturas-previsíveis-para-um-experimento-aleatório"><i class="fa fa-check"></i>Estruturas previsíveis para um experimento aleatório</a></li>
<li class="chapter" data-level="" data-path="va.html"><a href="va.html#alterando-os-parâmetros-do-modelo"><i class="fa fa-check"></i>Alterando os parâmetros do modelo</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="va.html"><a href="va.html#experimento-2-o-custo-de-1-sucesso"><i class="fa fa-check"></i><b>22.2</b> <em>Experimento 2</em>: O custo de 1 sucesso</a></li>
<li class="chapter" data-level="22.3" data-path="va.html"><a href="va.html#experimento-3-uma-sequência-de-sucessos"><i class="fa fa-check"></i><b>22.3</b> <em>Experimento 3</em>: Uma sequência de sucessos</a></li>
<li class="chapter" data-level="22.4" data-path="va.html"><a href="va.html#experimento-4-quantas-marcas-na-amostra"><i class="fa fa-check"></i><b>22.4</b> <em>Experimento 4</em>: Quantas marcas na amostra!</a></li>
<li class="chapter" data-level="22.5" data-path="va.html"><a href="va.html#experimento-5-contagem-por-unidade-de-área-tempo-.."><i class="fa fa-check"></i><b>22.5</b> <em>Experimento 5</em>: Contagem por unidade de área, tempo, …..</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="vacont.html"><a href="vacont.html"><i class="fa fa-check"></i><b>23</b> As variáveis são aleatórias, não imprevisíveis! - <em>Modelos contínuos</em></a>
<ul>
<li class="chapter" data-level="23.1" data-path="vacont.html"><a href="vacont.html#alguns-fenômenos-têm-distribuição-normal"><i class="fa fa-check"></i><b>23.1</b> Alguns fenômenos têm distribuição normal</a></li>
<li class="chapter" data-level="23.2" data-path="vacont.html"><a href="vacont.html#outros-são-altamente-assimétricos"><i class="fa fa-check"></i><b>23.2</b> Outros são altamente assimétricos</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="detmodel.html"><a href="detmodel.html"><i class="fa fa-check"></i><b>24</b> Alguns modelos são determinísticos</a>
<ul>
<li class="chapter" data-level="24.1" data-path="detmodel.html"><a href="detmodel.html#modelo-linear"><i class="fa fa-check"></i><b>24.1</b> Modelo linear</a></li>
<li class="chapter" data-level="24.2" data-path="detmodel.html"><a href="detmodel.html#função-potência"><i class="fa fa-check"></i><b>24.2</b> Função potência</a></li>
<li class="chapter" data-level="24.3" data-path="detmodel.html"><a href="detmodel.html#modelo-de-michaelis-menten-ou-resposta-funcional-do-tipo-ii"><i class="fa fa-check"></i><b>24.3</b> Modelo de Michaelis-Menten (ou Resposta funcional do tipo II)</a></li>
<li class="chapter" data-level="24.4" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iii"><i class="fa fa-check"></i><b>24.4</b> Resposta funcional do tipo III</a></li>
<li class="chapter" data-level="24.5" data-path="detmodel.html"><a href="detmodel.html#resposta-funcional-do-tipo-iv"><i class="fa fa-check"></i><b>24.5</b> Resposta funcional do tipo IV</a></li>
<li class="chapter" data-level="24.6" data-path="detmodel.html"><a href="detmodel.html#função-hiperbólica"><i class="fa fa-check"></i><b>24.6</b> Função hiperbólica</a></li>
<li class="chapter" data-level="24.7" data-path="detmodel.html"><a href="detmodel.html#função-exponencial"><i class="fa fa-check"></i><b>24.7</b> Função exponencial</a></li>
<li class="chapter" data-level="24.8" data-path="detmodel.html"><a href="detmodel.html#função-logística"><i class="fa fa-check"></i><b>24.8</b> Função logística</a></li>
<li class="chapter" data-level="24.9" data-path="detmodel.html"><a href="detmodel.html#modelo-monomolecular"><i class="fa fa-check"></i><b>24.9</b> Modelo monomolecular</a></li>
<li class="chapter" data-level="24.10" data-path="detmodel.html"><a href="detmodel.html#modelo-de-ricker"><i class="fa fa-check"></i><b>24.10</b> Modelo de Ricker</a></li>
<li class="chapter" data-level="24.11" data-path="detmodel.html"><a href="detmodel.html#modelo-de-gompertz"><i class="fa fa-check"></i><b>24.11</b> Modelo de Gompertz</a></li>
<li class="chapter" data-level="24.12" data-path="detmodel.html"><a href="detmodel.html#modelo-de-von-bertalanffy"><i class="fa fa-check"></i><b>24.12</b> Modelo de von Bertalanffy</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="modelstat.html"><a href="modelstat.html"><i class="fa fa-check"></i><b>25</b> As partes estocásticas e determinísticas de um modelo estatístico</a>
<ul>
<li class="chapter" data-level="25.1" data-path="modelstat.html"><a href="modelstat.html#a-parcela-aleatória"><i class="fa fa-check"></i><b>25.1</b> A parcela aleatória</a></li>
<li class="chapter" data-level="25.2" data-path="modelstat.html"><a href="modelstat.html#a-parcela-determinística"><i class="fa fa-check"></i><b>25.2</b> A parcela determinística</a></li>
<li class="chapter" data-level="25.3" data-path="modelstat.html"><a href="modelstat.html#mais-um-modelo-binomial-taxa-de-mortalidade-em-testes-dose-resposta"><i class="fa fa-check"></i><b>25.3</b> Mais um modelo Binomial: taxa de mortalidade em testes dose-resposta</a></li>
<li class="chapter" data-level="25.4" data-path="modelstat.html"><a href="modelstat.html#o-modelo-estatístico-da-regressão-linear"><i class="fa fa-check"></i><b>25.4</b> O modelo estatístico da regressão linear</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="emv.html"><a href="emv.html"><i class="fa fa-check"></i><b>26</b> Estimando os parâmetros: a ideia da Máxima Verossimilhança</a></li>
<li class="chapter" data-level="27" data-path="aic.html"><a href="aic.html"><i class="fa fa-check"></i><b>27</b> Comparando modelos: uma questão de parcimônia</a></li>
<li class="chapter" data-level="28" data-path="statbayes.html"><a href="statbayes.html"><i class="fa fa-check"></i><b>28</b> Da verossimilhança à estatística Bayesiana</a></li>
<li class="chapter" data-level="29" data-path="varmodels.html"><a href="varmodels.html"><i class="fa fa-check"></i><b>29</b> Uma variedade de modelos estatísticos: modelando a variância</a></li>
<li class="chapter" data-level="30" data-path="nindep.html"><a href="nindep.html"><i class="fa fa-check"></i><b>30</b> Uma variedade de modelos estatísticos: modelando os resíduos</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estatística nas Ciências Ambientais</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="th" class="section level1" number="10">
<h1><span class="header-section-number">Capítulo 10</span> Introdução ao Teste de Hipóteses</h1>
<p>Um dos objetivos centrais em estatística é fazer inferências válidas para a <strong>população</strong> examinando as características de uma <strong>amostra</strong>. Geralmente, a teoria disponível para um determinado campo do conhecimento científico nos permite fazer afirmações sobre determinado fenômeno, tais como:</p>
<blockquote>
<p><em>“a fragmentação de habitats reduz a diversidade em <span class="math inline">\(x\)</span> espécies”</em>;</p>
</blockquote>
<blockquote>
<p><em>“em níveis elevados de poluentes, a taxa de sobrevivência de um determinado organismo cai em <span class="math inline">\(y\%\)</span>”</em>;</p>
</blockquote>
<blockquote>
<p><em>“a remoção da área de mangue implica na redução em <span class="math inline">\(m\%\)</span> da captura de carbono”</em>.</p>
</blockquote>
<p>Todas estas afirmações são <strong>hipóteses</strong>, sobre um ou mais parâmetros de uma população estatística. A experimentação nos permite, com base na amostra, tirar conclusões sobre determitada hipótese. Mais especificamente, queremos saber se os dados em mãos nos permitem ou não refutar uma hipótese inicial.</p>
<p>Vamos a um exemplo simples. Se desejamos fazer uma inferência sobre um parâmetro da população estatística (ex.: sua média <span class="math inline">\(\mu\)</span>), devemos iniciar com uma afirmação sobre a posição deste parâmetro, que denominamos de <strong>hipótese nula</strong> (<span class="math inline">\(H_0\)</span>).</p>
<blockquote>
<p>Ex. Um modelo de climático sugere que a pluviosidade média entre junho e agosto nas cidades litorâneas do estado de São Paulo seja de <span class="math inline">\(110\)</span> mm/mês.</p>
</blockquote>
<p>Um cientista acredita que o modelo têm falhas e resolve tomar algumas observações sobre chuva mensal a fim de testar esta afirmação. Este cientista iria iniciar por formalizar suas <strong>hipóteses estatísticas</strong>.</p>
<p>Inicialmente será necessário estabelecer a <strong>hipótese nula</strong>, que neste exemplo será:</p>
<p><span class="math inline">\(H_0: \mu = 110\)</span> mm de chuva</p>
<p>Se uma análise estatística concluir que a hipótese nula é <strong>falsa</strong>, então deveremos ter uma hipótese <strong>alternativa</strong> (<span class="math inline">\(H_a\)</span>). Assim, no caso de rejeição de <span class="math inline">\(H_0\)</span> passaremos a assumir <span class="math inline">\(H_a\)</span> como <strong>verdadeira</strong>.</p>
<p>A hipótese alternativa neste exemplo será:</p>
<p><span class="math inline">\(H_a: \mu \ne 110\)</span> mm de chuva</p>
<p>Note que as hipóteses nula e alternativa se referem a predições sobre a posição da média populaçional <span class="math inline">\(\mu\)</span>. Como não temos acesso à <span class="math inline">\(\mu\)</span>, nossa opção é tomar amostras do fenômeno, medindo a quantidade de chuva em diferentes localidades e calcular a média amostral <span class="math inline">\(\overline{X}\)</span>.</p>
<div id="probabilidade-e-teste-de-hipóteses" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Probabilidade e teste de hipóteses</h2>
<p>A média <span class="math inline">\(\overline{X}\)</span> de uma amostra será nossa melhor evidência a respeito de <span class="math inline">\(\mu\)</span>. Tendo este valor, podemos nos perguntar:</p>
<blockquote>
<p>O valor obtido de <span class="math inline">\(\overline{X}\)</span> é condizente com o esperado segundo <span class="math inline">\(H_0\)</span>?</p>
</blockquote>
<p>Podemos racionalizar que se <span class="math inline">\(\overline{X}\)</span> estiver muito próximo a <span class="math inline">\(\mu\)</span>, não haveria evidências para rejeitar <span class="math inline">\(H_0\)</span>. Por outro lado, um valor de <span class="math inline">\(\overline{X}\)</span> muito distante de <span class="math inline">\(\mu\)</span> irá colocar em dúvida a afirmação feita em <span class="math inline">\(H_0\)</span>. O ponto relevante aqui é: <em>quão distante de <span class="math inline">\(\mu\)</span> deve estar <span class="math inline">\(\overline{X}\)</span> para que rejeitemos <span class="math inline">\(H_0\)</span>?</em></p>
<p>Esta resposta poderá ser respondida <strong>somente</strong> com o auxílio de um modelo probabilístico aplicado ao experimento em questão. Seja <span class="math inline">\(H_0\)</span> verdadeira, é esperado que a probabilidade de <span class="math inline">\(\overline{X}\)</span> estar próximo a <span class="math inline">\(\mu\)</span> é alta. Portanto, uma pergunta melhor formulada seria:</p>
<blockquote>
<p>Sendo <span class="math inline">\(H_0\)</span> <strong>verdadeira</strong>, qual é a probabilidade de que uma determinada média amostral <span class="math inline">\(\overline{X}\)</span> esteja tão ou mais distante de <span class="math inline">\(\mu\)</span> quanto o observado em nossa amostra particular?</p>
</blockquote>
<p>Uma vez que estamos falando da distribuição de médias amostrais, vale retomar o que determina o <strong>Teorema Central do Limite (TCL)</strong>. Segundo o TLC, a distribuição das médias amostrais tenderá a uma distribuição normal com média <span class="math inline">\(\mu\)</span> e desvio padrão <span class="math inline">\(\sigma_{\mu} = \frac{\sigma}{\sqrt{n}}\)</span>.</p>
<p>Desta forma, para um <span class="math inline">\(H_0\)</span> verdadeiro, seria esperado que a distribuição das médias amostrais resultantes de um procedimento experimental tivesse o formato de um distribuição normal, centrada em <span class="math inline">\(110\)</span> mm.</p>
<p>Digamos ainda que o modelo climático estabeleça que o desvio padrão para a quantidade de chuva seja <span class="math inline">\(\sigma = 30\)</span>. Neste caso, o desvio padrão esperado para as médias amostrais seria de <span class="math inline">\(\sigma_{\mu} = \frac{30}{\sqrt{n}}\)</span>. Por se tratar do desvio padrão da médias amostrais, <span class="math inline">\(\sigma_{\mu}\)</span> é denominado de <strong>erro padrão da média</strong> (Capítulo <a href="amostrmedias.html#amostrmedias">6</a>).</p>
<p>Feito isto, temos em mãos o <strong>modelo probabilístico</strong> que, aliado a uma amostra particular, nos permitirá concluir se há evidências para rejeitar <span class="math inline">\(H_0\)</span> em favor de <span class="math inline">\(H_a\)</span>.</p>
<p>Segundo a distribuição normal, a probabilidade do valor observado <span class="math inline">\(\overline{X}\)</span> estar <strong>tão ou mais distante</strong> de <span class="math inline">\(\mu\)</span> na distribuição <span class="math inline">\(Z\)</span> é calculando por:</p>
<p><span class="math display">\[z = \frac{\overline{X} - \mu}{\sigma_{\overline{X}}}\]</span></p>
<p>O valor de <span class="math inline">\(z\)</span> calculato é chamado de <strong>estatśitica do teste</strong>. Com o uso da Tabela <span class="math inline">\(Z\)</span>, esta estatística será utilizada para encontrar:</p>
<p><span class="math display">\[P(Z \ge z) = P(\overline{X} \ge \mu)\]</span></p>
<p>Como nossa pergunta se refere à <strong>distância</strong> entre <span class="math inline">\(\overline{X}\)</span> e <span class="math inline">\(\mu\)</span>, devemos encontar também <span class="math inline">\(P(Z \le -z)\)</span>, de modo que a probabilidade que nos interessa será representada pela área destacada na figura abaixo que nos dá <span class="math inline">\(P(Z \ge |z|)\)</span>.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-169-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Valores de <span class="math inline">\(\overline{X}\)</span> muito próximos a <span class="math inline">\(\mu\)</span> resultarão em valores de <span class="math inline">\(z\)</span> próximos a <strong>zero</strong>. Neste caso, a probabilidade de <span class="math inline">\(\overline{X}\)</span> estar tão ou mais distante de <span class="math inline">\(\mu\)</span> é alta. Se <span class="math inline">\(\overline{X}\)</span> estiver muito <strong>distante</strong> de <span class="math inline">\(\mu\)</span> o valor calculado <span class="math inline">\(z\)</span> será grande e, consequentemente, estará associado a uma probabilidade muito baixa:</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-170-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>Iremos aceitar ou rejeitar <span class="math inline">\(H_0\)</span> na medida que esta probabilidade estiver acima (aceita <span class="math inline">\(H_0\)</span>) ou abaixo (rejeita <span class="math inline">\(H_0\)</span>) de um limite <em>pré-estabelecido</em> que denominamos de <strong>nível de significância - <span class="math inline">\(\alpha\)</span></strong>.</p>
</div>
<div id="exemplificando-um-teste-de-hipóteses-o-teste-z" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Exemplificando um teste de hipóteses: o teste z</h2>
<p>Digamos que o número de batimentos cardíacos por minuto de um adulto em repouso tenha média <span class="math inline">\(\mu = 65\)</span> e desvio padrão <span class="math inline">\(\sigma = 9\)</span>. Você imagina que o sedentarismo altera o batimento médio de um adulto. Para testar esta suposição você deve inicialmente determinar as hipóteses nula e alternativa:</p>
<p><span class="math inline">\(H_0: \mu = 65\)</span> batimentos por minuto</p>
<p><span class="math inline">\(H_a: \mu \ne 65\)</span> batimentos por minuto</p>
<p>Em seguida você determina o nível de significância (<span class="math inline">\(\alpha\)</span>) do teste. Vamos determinar que queremos fazer o teste ao nível de significância <span class="math inline">\(\alpha = 0,05\)</span>.</p>
<blockquote>
<p>IMPORTANTE: O nível de significância <span class="math inline">\(\alpha\)</span> deve ser determinado <strong>antes</strong> da tomada de dados.</p>
</blockquote>
<p>Finalmente, você seleciona <em>ao acaso</em> <span class="math inline">\(n = 15\)</span> pessoas de hábito sedentário e mede seus batimentos cardíacos.</p>
<p>Os resultados obtidos desta amotra <em>aleatória</em> são:</p>
<p>Amostra: 65, 73, 56, 71, 69, 69, 68, 59, 73, 68, 69, 64, 67, 64, 66</p>
<p>que nos dá uma média amostral de:</p>
<p><span class="math inline">\(\overline{X} = \frac{\sum{X_i}}{n} = \frac{65+73+56+71+69+69+68+59+73+68+69+64+67+64+66}{15} = 66.73\)</span> batimentos por minuto;</p>
<p>e um erro padrão de:</p>
<p><span class="math inline">\(\sigma_{\mu} = \frac{\sigma}{\sqrt{n}} = \frac{9}{3.87} = 2.32\)</span></p>
<p>Com estes resultados encontramos o valor correspondente de Z.</p>
<p><span class="math inline">\(z = \frac{\overline{X} - \mu}{\sigma_{\mu}} = \frac{66.73 - 65}{2.32} = 0.75\)</span></p>
<p>Utilizando a Tabela Z, encontramos a probabilidade de obtermos valores tão ou mais extremos que <span class="math inline">\(-0.75\)</span> e <span class="math inline">\(+0.75\)</span>.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-172-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Com isto, a probabilidade de encontarmos valores tão ou mais extermos que <span class="math inline">\(\overline{X} = 66.73\)</span> foi calculada em <span class="math inline">\(0.227 + 0.227 =\)</span> <strong>0.453</strong>.</p>
<p>Neste exemplo, a <strong>estatística do teste</strong> foi <span class="math inline">\(z = 0.75\)</span> o a probabilidade associada <span class="math inline">\(p = 0.453\)</span>.</p>
<hr />
<p>No R fazemos:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="th.html#cb77-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">65</span>, <span class="dv">73</span>, <span class="dv">56</span>, <span class="dv">71</span>, <span class="dv">69</span>, <span class="dv">69</span>, <span class="dv">68</span>, <span class="dv">59</span>, <span class="dv">73</span>, <span class="dv">68</span>, <span class="dv">69</span>, <span class="dv">64</span>, <span class="dv">67</span>, <span class="dv">64</span>, <span class="dv">66</span>)</span>
<span id="cb77-2"><a href="th.html#cb77-2" aria-hidden="true" tabindex="-1"></a>Xm <span class="ot">&lt;-</span> <span class="fu">mean</span>(X)</span>
<span id="cb77-3"><a href="th.html#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> Xm, <span class="at">mean =</span> <span class="dv">65</span>, <span class="at">sd =</span> <span class="dv">9</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">15</span>), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.4557231</code></pre>
<div id="tomada-de-decisão-sobre-h_0-nível-de-significância" class="section level3" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Tomada de decisão sobre <span class="math inline">\(H_0\)</span>: nível de significância</h3>
<p>No exemplo acima, obtivemos <span class="math inline">\(p =\)</span> <strong>0.453</strong>. Isto significa que:</p>
<blockquote>
<p>sendo <span class="math inline">\(H_0\)</span> <strong>verdadeira</strong>, existe uma probabilidade igual a <span class="math inline">\(0.453\)</span> de que a média de uma amostra com <span class="math inline">\(n = 15\)</span> esteja tão ou mais distante de <span class="math inline">\(\mu = 65\)</span> como observado neste experimento.</p>
</blockquote>
<p>Se aceitarmos que esta probabilidade é <strong>alta</strong>, então não há motivo para buscar por outras explicações. Por outro lado, se concluirmo que esta probabilidade é <strong>baixa</strong>, estamos dizendo que resultado obtido é <strong>improvável</strong> segundo a hipótese nula. Neste caso, temos espaço para buscar por hipóteses <strong>alternativas</strong> que possam explicar o fenômeno.</p>
<p>Para decidir se a probabilidade obtida é alta ou baixa, devemos compará-la ao nível de significância <span class="math inline">\(\alpha\)</span> pré-estabelecido. <span class="math inline">\(H_0\)</span> será aceita somente se a probabilidade encontrada for <strong>maior</strong> que <span class="math inline">\(\alpha\)</span>. Por outro lado, se nossa probabilidade for <strong>menor ou igual</strong> a <span class="math inline">\(\alpha\)</span>, considerarmos os resultados improváveis segundo a hipótese nula e <strong>rejeitamos</strong> <span class="math inline">\(H_0\)</span> em favor de <span class="math inline">\(H_a\)</span>.</p>
<p>Um nível crítico comumente utilizado é <span class="math inline">\(\alpha = 0.05\)</span>. No exemplo acima a probabilidade foi de 0.453, um valor muito acima de <span class="math inline">\(0.05\)</span>. Dizemos portanto, que a média amostral <span class="math inline">\(\overline{X}\)</span> não está tão distante do <span class="math inline">\(\mu\)</span> a ponto de rejeitarmos <span class="math inline">\(H_0\)</span>.</p>
<blockquote>
<p>Concluimos que, neste exemplo, <span class="math inline">\(\overline{X} = 66.73\)</span> não nos fornece evidência suficiente para rejeitar <span class="math inline">\(H_0\)</span>.</p>
</blockquote>
</div>
</div>
<div id="erros-de-decisão-em-um-teste-de-hipóteses" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Erros de decisão em um teste de hipóteses</h2>
<p>A interpretação da probabilidade final esta associada à situação em que <span class="math inline">\(H_0\)</span> seja verdadeira.</p>
<p>Isto nos leva perguntar: <em>o que esperar caso <span class="math inline">\(H_0\)</span> seja falsa</em>?</p>
<p>Como não sabemos de fato, de <span class="math inline">\(H_0\)</span> é verdadeira ou não, a tomada de decisão sobre um resultado de um teste estatístico pode nos levar às seguintes situações:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center"><span class="math inline">\(H_0\)</span> Verdadeira</th>
<th align="center"><span class="math inline">\(H_0\)</span> Falsa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(H_0\)</span> é rejeitada</td>
<td align="center"><span class="math inline">\(\alpha\)</span> (<span class="math inline">\(\textbf{Erro Tipo I}\)</span>)</td>
<td align="center">Decisão correta (<span class="math inline">\(1-\beta\)</span>)</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(H_0\)</span> é aceita</td>
<td align="center">Decisão correta (<span class="math inline">\(1-\alpha\)</span>)</td>
<td align="center"><span class="math inline">\(\beta\)</span> (<span class="math inline">\(\textbf{Erro Tipo II}\)</span>)</td>
</tr>
</tbody>
</table>
<p>A tabela acima nos mostra os tipos de erros aos quais estamos sujeitos ao realizar um teste de hipótese.</p>
<p>Eventualmente, podemos rejeitar <span class="math inline">\(H_0\)</span>, ainda que ela seja verdadeira. O nivel de significância adotado, estabele que a probabilidade disto acontecer é <span class="math inline">\(\alpha\)</span>. Se rejeitarmos <span class="math inline">\(H_0\)</span> quando ela é verdadeira, estaremos incorrendo em um erro de decisão que denominamos de <strong>Erro Tipo I</strong>. Consequentemente, temos uma probabilidade de <span class="math inline">\(1 - \alpha\)</span> de aceitar corretamente <span class="math inline">\(H_0\)</span> quando ela é verdadeira. Estabelecer um <span class="math inline">\(\alpha = 0,05\)</span> nos garante que iremos incorrer no erro do tipo I em somente <span class="math inline">\(5\%\)</span> das vezes que o experimento for realizado.</p>
<p>Um outra situação ocorre quando aceitamos erroneamente a hipótese nula que é <strong>falsa</strong>, incorrendo no <strong>Erro Tipo II</strong>. O erro do tipo II tem probabilidade <span class="math inline">\(\beta\)</span> de acontecer. O complementar desta probabilidade (<span class="math inline">\(1-\beta\)</span>) é denominado de <strong>Poder do Teste</strong>. Um teste poderoso é portanto, aquele que tem elevada probabilidade de rejeitar <span class="math inline">\(H_0\)</span> quando ela é falsa.</p>
<p>As figuras abaixo representam as distribuições das médias amostrais e os erros do tipos I e II quando o <span class="math inline">\(H_0\)</span> é verdadeira (<span class="math inline">\(\mu_a = \mu\)</span>) e quando <span class="math inline">\(H_0\)</span> é falsa (<span class="math inline">\(\mu_a &gt; \mu\)</span>).</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-174-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Idealmente em um teste estatístico, seria interessante reduzir ao máximo os erros do tipo I e II. Ao reduzirmos o erro do tipo I, diminuindo <span class="math inline">\(\alpha\)</span> teremos um teste mais rigoroso que raramente iria errar ao rejeitar um <span class="math inline">\(H_0\)</span> verdadeiro (Figura A). Entretanto, este teste também <strong>raramente</strong> iria rejeitar <span class="math inline">\(H_0\)</span> ainda que ele seja falso (Figura B). Consequentemente, ao diminuir o valor de <span class="math inline">\(\alpha\)</span> ficamos menos propensos a cometer o erro do tipo I, porém <strong>mais propensos</strong> a incorrer no erro tipo II, isto é, não rejeitar uma <span class="math inline">\(H_0\)</span> falsa.</p>
<p>Dadas estas características, o único modo que reduzir os dois tipos de erros <strong>simultaneamente</strong> é aumentando o tamanho amostral <span class="math inline">\(n\)</span> pois, neste caso, reduzimos o erro padrão (<span class="math inline">\(\sigma_{\overline{X}}\)</span>) e consequentemente a sobreposição entre as duas curvas acima.</p>
</div>
<div id="exemplo-de-um-teste-de-hipótese-teste-t-para-uma-média-populacional" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Exemplo de um teste de hipótese: teste t para uma média populacional</h2>
<p>O <strong>teste <span class="math inline">\(z\)</span></strong> que utilizamos anteriormente assume que a distribuição das médias amostrais é normalmente distribuída e que a variância populacional <span class="math inline">\(\sigma\)</span> seja conhecida. Não temos entretanto, conhecimento sobre o valor de <span class="math inline">\(\sigma\)</span>, podendo somente estimá-lo pelo desvio padrão <strong>amostral</strong> <span class="math inline">\(s\)</span>. Adicionalmente, assumir que a distribuição das médias seja normalmente distribuída, como prevê o Teorema do Limite Central requer que tenhamos amostras grandes (os livros sugerem <span class="math inline">\(n \ge 30\)</span>).</p>
<p>Ao falar de estimação intervalar (Capítulo <a href="inferenc.html#inferenc">9</a>) apresentamos outra distribuição de probabilidade, a <strong>distribuição t de Student</strong>. Dissemos que esta distribuição descreve melhor o comportamento das médias amostrais quando as amostras são pequenas e a variância amostral é desconhecida.</p>
<p>Seguindo este raciocínio, apresentamos o <strong>teste t</strong> para comparar uma média populacional. Este teste é muito similar ao teset <span class="math inline">\(z\)</span> apresentado anteriormente.</p>
<p>Considere um exemplo simples. Dados do Banco Central do Brasil dizem que moedas de <span class="math inline">\(R\$ 0,10\)</span> da segunda geração pesam 4.8 gramas. Você tem <span class="math inline">\(8\)</span> moedas no bolso e resolve testar essa afirmação pesando cada moeda. Os pesos obtidos são: <span class="math inline">\(X = 5.1, 5, 4.8, 5, 5, 4.9, 4.9, 4.7\)</span>.</p>
<p>Inicialmente, devemos estabelecer nossa hipótese nula (<span class="math inline">\(H_0\)</span>), nossa hipótese alternativa (<span class="math inline">\(H_a\)</span>) e o nível se significância <span class="math inline">\(\alpha\)</span>. Iremos estabelecer <span class="math inline">\(\alpha = 0,05\)</span> e as hipóteses como:</p>
<p><span class="math inline">\(H_0: \mu = 4.8\)</span> gramas</p>
<p><span class="math inline">\(H_a: \mu \ne 4.8\)</span> gramas</p>
<p>Como não conhecemos <span class="math inline">\(\sigma\)</span> e temos uma amostra pequena, a posição das médias amostrais seguirá uma distribuição <span class="math inline">\(t\)</span> de Student e a estatística do teste será:</p>
<p><span class="math display">\[t = \frac{\overline{X} - \mu}{s_{\overline{X}}}\]</span></p>
<p>sendo o erro padrão amostral obtido por:</p>
<p><span class="math display">\[s_{\overline{X}} = \frac{s}{\sqrt{n}}\]</span></p>
<p>O cálculo de <span class="math inline">\(t\)</span> é muito similar ao escore z. No entanto, substituímos <span class="math inline">\(\sigma\)</span> por <span class="math inline">\(s\)</span>. Como visto no capítulo <a href="inferenc.html#inferenc">9</a>, as distribuições de <span class="math inline">\(t\)</span> e de <span class="math inline">\(Z\)</span> são muto similares. Entretanto, para amostras pequenas e quando <span class="math inline">\(\sigma\)</span> é desconhecido, a curva de <span class="math inline">\(t\)</span> nos fornece uma melhor estimativa das probabilidades associadas a distribuição das médias amostrais.</p>
<p>Para este exemplo, temos uma amostra de tamanho <span class="math inline">\(n = 8\)</span> com média <span class="math inline">\(\overline{X} = 4.925\)</span>g e desvio padrão <span class="math inline">\(s = 0.13\)</span>g. O valor de <span class="math inline">\(t\)</span> pode ser calculado por:</p>
<p><span class="math display">\[t_{c} = \frac{\overline{X} - \mu}{s_{\overline{X}}} = \frac{\overline{X} - \mu}{\frac{s}{\sqrt{n}}} = \frac{4.925  - 4.8}{\frac{0.13}{\sqrt{8}}} = 2.76\]</span></p>
<p>Assim como fizemos para a distribuição <span class="math inline">\(Z\)</span>, devemos encontrar a probabilidade de obtermos um valor tão ou maior que o módulo de <span class="math inline">\(t_c\)</span>. Na figura abaixo, nosso resultado fica:</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-176-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>A probabilidade de encontrarmos um valor de <span class="math inline">\(t_c\)</span> tão ou mais extremo segundo a hipótese nula foi de <span class="math inline">\(p = 0.028\)</span>. Uma vez que este valor é <strong>menor</strong> que o nível crítico <span class="math inline">\(\alpha = 0,05\)</span>, concluímos que existe evidência suficiente para <strong>rejeitar</strong> <span class="math inline">\(H_0\)</span> e <strong>aceitar</strong> a hipótese alternativa de que as moedas de <span class="math inline">\(10\)</span> centavos <strong>não</strong> provém de uma população estatística com <span class="math inline">\(\mu = 4,8\)</span> gramas. Nossa conclusão é portanto, que as moedas de <span class="math inline">\(R\$ 0,10\)</span> são mais <strong>pesadas</strong> que <span class="math inline">\(4,8\)</span> gramas.</p>
<p>No R, o teste t discutido acima pode ser realizado por:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="th.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(X, <span class="at">mu =</span> <span class="fl">4.8</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  X
## t = 2.7584, df = 7, p-value = 0.02816
## alternative hypothesis: true mean is not equal to 4.8
## 95 percent confidence interval:
##  4.817844 5.032156
## sample estimates:
## mean of x 
##     4.925</code></pre>
<p>Nos comandos acima, <span class="math inline">\(X\)</span> é a amostra e o argumento ‘mu’ é o valor da média populacional <em>segundo <span class="math inline">\(H_0\)</span></em>. Como resultados temos a indicação de que fizemos um <em>teste <span class="math inline">\(t\)</span></em> para uma amostra (<em>One Sample t-test</em>), o valor de <span class="math inline">\(t\)</span> calculado (<span class="math inline">\(t = 2.76\)</span>), os graus de liberdade (<span class="math inline">\(df = 8 - 1 = 7\)</span>) e o valor de <span class="math inline">\(p = 0.028\)</span>. Nestes resultados, podemos ver ainda o valor da média amostral (<span class="math inline">\(\overline{X} = 4.925\)</span>) e o intervalo de confiança a <span class="math inline">\(95\%\)</span> (<span class="math inline">\(4.82 - 5.03\)</span>)</p>
</div>
<div id="graus-de-liberdade" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Graus de liberdade</h2>
<p>A distribuição <span class="math inline">\(t\)</span> como várias outras distribuições amostrais utilizadas em inferência estatística, muda seu formato em função do que chamamos de <strong>graus de liberdade</strong> (<span class="math inline">\(gl\)</span>). Os graus de liberdade têm relação com o tamanho amostral. No caso do teste <span class="math inline">\(t\)</span> para <span class="math inline">\(1\)</span> amostra, esta relação é simplesmente: <span class="math inline">\(gl = n-1\)</span>.</p>
<p>À medida que os graus de liberdade aumentam, o formato da distribuição <span class="math inline">\(t\)</span> se assemelha ao formato da distribuição Normal padronizada. De fato, para graus de liberdades altos (ex. <span class="math inline">\(n \ge 30\)</span>), os formatos das distribuições <span class="math inline">\(Z\)</span> e <span class="math inline">\(t\)</span> são praticamente indistinguíveis. Na prática, isto faz que as distribuição <span class="math inline">\(Z\)</span> <strong>raramente</strong> seja utilizada.</p>
<p><img src="probest-cambientais_files/figure-html/unnamed-chunk-178-1.png" width="672" /></p>
</div>
<div id="probabilidades-no-teste-t-de-student-a-tabela-t" class="section level2" number="10.6">
<h2><span class="header-section-number">10.6</span> Probabilidades no teste <span class="math inline">\(t\)</span> de Student: a tabela <span class="math inline">\(t\)</span></h2>
<p>A rejeição/aceitação da hipótese nula em um teste t pode ser feita por meio da obtenção do <em>valor de p</em> ou pela comparação do <span class="math inline">\(t\)</span> calculado com valores críticos de referência para determinado nível de significância. O primeiro caso foi o que apresentamos acima e depende de um software estatístico para obtermos valores exatos de <span class="math inline">\(p\)</span>. O segundo caso, pode ser feito com auxílio da Tabela t, em críticos de <span class="math inline">\(t\)</span> são disponibilizados para diferentes níveis de significância e graus de liberdade.</p>
<p>O uso ta tabela <span class="math inline">\(t\)</span> têm finalidade, em grande parte didática, uma vez que a aplicação do teste fora da sala de aula será invariavelmente conduzido por meio de um software estatístico. po este motivo vamos apresentá-lo aqui rapidamente.</p>
<p>Na tabela t que disponibilizamos, a primeira coluna mostra os <em>graus de liberdade</em> de <span class="math inline">\(1\)</span> a <span class="math inline">\(120\)</span>. O cabeçalho da tabela de <span class="math inline">\(90\%\)</span> a <span class="math inline">\(0,1\%\)</span> mostra a área na distribuição de <span class="math inline">\(t\)</span> nas caldas inferior e superior.</p>
<p>Vamos retornar ao exemplo da moedas de <span class="math inline">\(R\$0,10\)</span> para exemplificar sua utilização. Neste exemplo a tinhamos <span class="math inline">\(8\)</span> (<span class="math inline">\(gl = 7\)</span> graus de liberdade) e o teste foi feito com <span class="math inline">\(\alpha =0,05\)</span>. Se buscarmos na linha <span class="math inline">\(gl = 7\)</span> e a coluna <span class="math inline">\(5\%\)</span> (<span class="math inline">\(\alpha = 0,05\)</span>), encontraremos o valor <span class="math inline">\(t = 2,3646\)</span>. Este é o chamado <span class="math inline">\(t\)</span> <strong>crítico</strong>. Acima deste valor e abaixo de sua contraparte negativa temos exatamente <span class="math inline">\(5\%\)</span> da área na disribuição <span class="math inline">\(t\)</span>. Deste modo qualquer valor calulado <strong>maior</strong> que <span class="math inline">\(t\)</span> crítico estará mais para a extremidade da distribuição e consequentemente estará associado a <strong>menores</strong> valores de probabilidade. Neste sentido:</p>
<ul>
<li><span class="math inline">\(t_{calculado} \ge t\)</span> crítico leva a <em>rejeição</em> de <span class="math inline">\(H_0\)</span></li>
<li><span class="math inline">\(t_{calculado} &lt; t\)</span> crítico leva a <em>aceitação</em> de <span class="math inline">\(H_0\)</span></li>
</ul>
<p>O resultado do teste estatístico em nosso exemplo foi <span class="math inline">\(t_c = 2.76\)</span> que é <strong>maior</strong> que <span class="math inline">\(2,3646\)</span>. Isto nos leva à mesma decisão anterior (<strong>rejeitar</strong> <span class="math inline">\(H_0\)</span>), ainda que por meio da tabela <span class="math inline">\(t\)</span> não tenhamos o valor exato de probabilidade.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="inferenc.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="testet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["probest-cambientais.pdf", "probest-cambientais.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
